UPDATE questions SET answers = '["hier Religionsfreiheit gilt.", "die Menschen Steuern zahlen.", "die Menschen das Wahlrecht haben.", "hier Meinungsfreiheit gilt."]'::jsonb, correct_answer = 4 WHERE id = 1;
UPDATE questions SET answers = '["Geschichtsunterricht teilnimmt.", "Religionsunterricht teilnimmt.", "Politikunterricht teilnimmt.", "Sprachunterricht teilnimmt."]'::jsonb, correct_answer = 2 WHERE id = 2;
UPDATE questions SET answers = '["Alle Einwohner/innen und der Staat müssen sich an die Gesetze halten.", "Der Staat muss sich nicht an die Gesetze halten.", "Nur Deutsche müssen die Gesetze befolgen.", "Die Gerichte machen die Gesetze."]'::jsonb, correct_answer = 1 WHERE id = 3;
UPDATE questions SET answers = '["Waffenbesitz", "Faustrecht", "Meinungsfreiheit", "Selbstjustiz"]'::jsonb, correct_answer = 3 WHERE id = 4;
UPDATE questions SET answers = '["Man darf Geld annehmen, wenn man dafür eine bestimmte Kandidatin/einen bestimmten Kandidaten wählt.", "Nur Personen, die noch nie im Gefängnis waren, dürfen wählen.", "Die Wählerin/der Wähler darf bei der Wahl weder beeinflusst noch zu einer bestimmten Stimmabgabe gezwungen werden und keine Nachteile durch die Wahl haben.", "Alle wahlberechtigten Personen müssen wählen."]'::jsonb, correct_answer = 3 WHERE id = 5;
UPDATE questions SET answers = '["Volksgesetz", "Bundesgesetz", "Deutsches Gesetz", "Grundgesetz"]'::jsonb, correct_answer = 4 WHERE id = 6;
UPDATE questions SET answers = '["Glaubens- und Gewissensfreiheit", "Unterhaltung", "Arbeit", "Wohnung"]'::jsonb, correct_answer = 1 WHERE id = 7;
UPDATE questions SET answers = '["Die Würde des Menschen ist unantastbar.", "Alle sollen gleich viel Geld haben.", "Jeder Mensch darf seine Meinung sagen.", "Alle sind vor dem Gesetz gleich."]'::jsonb, correct_answer = 2 WHERE id = 8;
UPDATE questions SET answers = '["Schutz der Familie", "Menschenwürde", "Asyl", "Meinungsfreiheit"]'::jsonb, correct_answer = 3 WHERE id = 9;
UPDATE questions SET answers = '["die Prügelstrafe", "die Folter", "die Todesstrafe", "die Geldstrafe"]'::jsonb, correct_answer = 4 WHERE id = 10;
UPDATE questions SET answers = '["Grundgesetz", "Bundesverfassung", "Gesetzbuch", "Verfassungsvertrag"]'::jsonb, correct_answer = 1 WHERE id = 11;
UPDATE questions SET answers = '["Ja, wenn mehr als die Hälfte der Abgeordneten im Bundestag dafür sind.", "Ja, aber dazu müssen zwei Drittel der Abgeordneten im Bundestag dafür sein.", "Nein, denn die Pressefreiheit ist ein Grundrecht. Sie kann nicht abgeschafft werden.", "Nein, denn nur der Bundesrat kann die Pressefreiheit abschaffen."]'::jsonb, correct_answer = 3 WHERE id = 12;
UPDATE questions SET answers = '["die regierenden Parteien.", "die Fraktion mit den meisten Abgeordneten.", "alle Parteien, die bei der letzten Wahl die 5%-Hürde erreichen konnten.", "alle Abgeordneten, die nicht zu der Regierungspartei/den Regierungsparteien gehören."]'::jsonb, correct_answer = 4 WHERE id = 13;
UPDATE questions SET answers = '["Passanten auf der Straße beschimpfen darf.", "meine Meinung in Leserbriefen äußern kann.", "Nazi-Symbole tragen darf.", "meine Meinung sagen darf, solange ich der Regierung nicht widerspreche."]'::jsonb, correct_answer = 2 WHERE id = 14;
UPDATE questions SET answers = '["Militärdienst", "Zwangsarbeit", "freie Berufswahl", "Arbeit im Ausland"]'::jsonb, correct_answer = 2 WHERE id = 15;
UPDATE questions SET answers = '["bei der öffentlichen Verbreitung falscher Behauptungen über einzelne Personen", "bei Meinungsäußerungen über die Bundesregierung", "bei Diskussionen über Religionen", "bei Kritik am Staat"]'::jsonb, correct_answer = 1 WHERE id = 16;
UPDATE questions SET answers = '["Meinungsfreiheit der Einwohnerinnen und Einwohner.", "Petitionen der Bürgerinnen und Bürger.", "Versammlungsfreiheit der Einwohnerinnen und Einwohner.", "Ungleichbehandlung der Bürgerinnen und Bürger durch den Staat."]'::jsonb, correct_answer = 4 WHERE id = 17;
UPDATE questions SET answers = '["die Unantastbarkeit der Menschenwürde", "das Recht auf Leben", "Religionsfreiheit", "Meinungsfreiheit"]'::jsonb, correct_answer = 1 WHERE id = 18;
UPDATE questions SET answers = '["Man darf sich seinen Wohnort selbst aussuchen.", "Man kann seinen Beruf wechseln.", "Man darf sich für eine andere Religion entscheiden.", "Man darf sich in der Öffentlichkeit nur leicht bekleidet bewegen."]'::jsonb, correct_answer = 1 WHERE id = 19;
UPDATE questions SET answers = '["tolerant.", "rechtsstaatlich orientiert.", "gesetzestreu.", "verfassungswidrig."]'::jsonb, correct_answer = 4 WHERE id = 20;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 1 WHERE id = 21;
UPDATE questions SET answers = '["Monarchie", "Diktatur", "Republik", "Fürstentum"]'::jsonb, correct_answer = 3 WHERE id = 22;
UPDATE questions SET answers = '["in kleinen Familienunternehmen beschäftigt.", "ehrenamtlich für ein Bundesland tätig.", "selbstständig mit einer eigenen Firma tätig.", "bei einer Firma oder Behörde beschäftigt."]'::jsonb, correct_answer = 4 WHERE id = 23;
UPDATE questions SET answers = '["14", "15", "16", "17"]'::jsonb, correct_answer = 3 WHERE id = 24;
UPDATE questions SET answers = '["Elsass-Lothringen", "Nordrhein-Westfalen", "Mecklenburg-Vorpommern", "Sachsen-Anhalt"]'::jsonb, correct_answer = 1 WHERE id = 25;
UPDATE questions SET answers = '["eine kommunistische Republik.", "ein demokratischer und sozialer Bundesstaat.", "eine kapitalistische und soziale Monarchie.", "ein sozialer und sozialistischer Bundesstaat."]'::jsonb, correct_answer = 2 WHERE id = 26;
UPDATE questions SET answers = '["ein sozialistischer Staat.", "ein Bundesstaat.", "eine Diktatur.", "eine Monarchie."]'::jsonb, correct_answer = 2 WHERE id = 27;
UPDATE questions SET answers = '["das Militär", "die Wirtschaft", "das wahlberechtigte Volk", "die Verwaltung"]'::jsonb, correct_answer = 3 WHERE id = 28;
UPDATE questions SET answers = '["Löwe", "Adler", "Bär", "Pferd"]'::jsonb, correct_answer = 2 WHERE id = 29;
UPDATE questions SET answers = '["regelmäßige Wahlen", "Pressezensur", "Meinungsfreiheit", "verschiedene Parteien"]'::jsonb, correct_answer = 2 WHERE id = 30;
UPDATE questions SET answers = '["Einheit.", "Koalition.", "Ministerium.", "Fraktion."]'::jsonb, correct_answer = 2 WHERE id = 31;
UPDATE questions SET answers = '["Gesetzgebung", "Regierung", "Presse", "Rechtsprechung"]'::jsonb, correct_answer = 3 WHERE id = 32;
UPDATE questions SET answers = '["sind Staat und Religionsgemeinschaften voneinander getrennt.", "bilden die Religionsgemeinschaften den Staat.", "ist der Staat abhängig von den Religionsgemeinschaften.", "bilden Staat und Religionsgemeinschaften eine Einheit."]'::jsonb, correct_answer = 1 WHERE id = 33;
UPDATE questions SET answers = '["eine Demokratie", "ein Rechtsstaat", "eine Monarchie", "ein Sozialstaat"]'::jsonb, correct_answer = 3 WHERE id = 34;
UPDATE questions SET answers = '["Kirchensteuer", "Sozialabgaben", "Spendengeldern", "Vereinsbeiträgen"]'::jsonb, correct_answer = 2 WHERE id = 35;
UPDATE questions SET answers = '["die Krankenversicherung", "die Autoversicherung", "die Gebäudeversicherung", "die Haftpflichtversicherung"]'::jsonb, correct_answer = 1 WHERE id = 36;
UPDATE questions SET answers = '["Erste Ministerin/Erster Minister", "Premierministerin/Premierminister", "Senatorin/Senator", "Ministerpräsidentin/Ministerpräsident"]'::jsonb, correct_answer = 1 WHERE id = 37;
UPDATE questions SET answers = '["Staatenverbund", "Bundesstaat", "Staatenbund", "Zentralstaat"]'::jsonb, correct_answer = 2 WHERE id = 38;
UPDATE questions SET answers = '["einen eigenen Außenminister / eine eigene Außenministerin", "eine eigene Währung", "eine eigene Armee", "eine eigene Regierung"]'::jsonb, correct_answer = 4 WHERE id = 39;
UPDATE questions SET answers = '["Völker, hört die Signale …", "Einigkeit und Recht und Freiheit …", "Freude schöner Götterfunken …", "Deutschland einig Vaterland …"]'::jsonb, correct_answer = 2 WHERE id = 40;
UPDATE questions SET answers = '["weil dadurch die unterschiedlichen Meinungen der Bürger und Bürgerinnen vertreten werden", "damit Bestechung in der Politik begrenzt wird", "um politische Demonstrationen zu verhindern", "um wirtschaftlichen Wettbewerb anzuregen"]'::jsonb, correct_answer = 1 WHERE id = 41;
UPDATE questions SET answers = '["die Regierung", "das Parlament", "die Gerichte", "die Polizei"]'::jsonb, correct_answer = 2 WHERE id = 42;
UPDATE questions SET answers = '["wenn ihr Wahlkampf zu teuer ist", "wenn sie gegen die Verfassung kämpft", "wenn sie Kritik am Staatsoberhaupt äußert", "wenn ihr Programm eine neue Richtung vorschlägt"]'::jsonb, correct_answer = 2 WHERE id = 43;
UPDATE questions SET answers = '["Abgeordnete des EU-Parlaments", "den Bundespräsidenten / die Bundespräsidentin", "Landtagsabgeordnete", "Bundestagsabgeordnete"]'::jsonb, correct_answer = 2 WHERE id = 44;
UPDATE questions SET answers = '["Sozialversicherung", "Unfallversicherung", "Hausratversicherung", "Haftpflicht- und Feuerversicherung"]'::jsonb, correct_answer = 1 WHERE id = 45;
UPDATE questions SET answers = '["Er baut Straßen und Schulen.", "Er verkauft Lebensmittel und Kleidung.", "Er versorgt alle Einwohner und Einwohnerinnen kostenlos mit Zeitungen.", "Er produziert Autos und Busse."]'::jsonb, correct_answer = 1 WHERE id = 46;
UPDATE questions SET answers = '["Er bezahlt für alle Staatsangehörigen Urlaubsreisen.", "Er zahlt Kindergeld.", "Er unterstützt Museen.", "Er fördert Sportler und Sportlerinnen."]'::jsonb, correct_answer = 1 WHERE id = 47;
UPDATE questions SET answers = '["der Bundesrat", "der Bundespräsident / die Bundespräsidentin", "die Bürgerversammlung", "die Regierung"]'::jsonb, correct_answer = 3 WHERE id = 48;
UPDATE questions SET answers = '["die Lehrer und Lehrerinnen", "die Bundesländer", "das Familienministerium", "die Universitäten"]'::jsonb, correct_answer = 2 WHERE id = 49;
UPDATE questions SET answers = '["freie Zentralwirtschaft.", "soziale Marktwirtschaft.", "gelenkte Zentralwirtschaft.", "Planwirtschaft."]'::jsonb, correct_answer = 2 WHERE id = 50;
UPDATE questions SET answers = '["Menschen sich kritisch über die Regierung äußern können.", "Bürger friedlich demonstrieren gehen dürfen.", "Menschen von einer Privatpolizei ohne Grund verhaftet werden.", "jemand ein Verbrechen begeht und deshalb verhaftet wird."]'::jsonb, correct_answer = 3 WHERE id = 51;
UPDATE questions SET answers = '["Volke aus.", "Bundestag aus.", "preußischen König aus.", "Bundesverfassungsgericht aus."]'::jsonb, correct_answer = 1 WHERE id = 52;
UPDATE questions SET answers = '["Der Staat hat Recht.", "Es gibt nur rechte Parteien.", "Die Bürger und Bürgerinnen entscheiden über Gesetze.", "Der Staat muss die Gesetze einhalten."]'::jsonb, correct_answer = 4 WHERE id = 53;
UPDATE questions SET answers = '["Legislative", "Judikative", "Exekutive", "Direktive"]'::jsonb, correct_answer = 4 WHERE id = 54;
UPDATE questions SET answers = '["den Bundestagssitz in Berlin", "das Bundesverfassungsgericht in Karlsruhe", "das Bundesratsgebäude in Berlin", "das Bundeskanzleramt in Berlin"]'::jsonb, correct_answer = 1 WHERE id = 55;
UPDATE questions SET answers = '["Pfarramt", "Ordnungsamt", "Finanzamt", "Auswärtiges Amt"]'::jsonb, correct_answer = 2 WHERE id = 56;
UPDATE questions SET answers = '["der / die älteste Abgeordnete im Parlament", "der Ministerpräsident / die Ministerpräsidentin des größten Bundeslandes", "ein Abgeordneter / eine Abgeordnete der stärksten Fraktion", "ein ehemaliger Bundeskanzler / eine ehemalige Bundeskanzlerin"]'::jsonb, correct_answer = 3 WHERE id = 57;
UPDATE questions SET answers = '["der Präsident / die Präsidentin des Bundesverfassungsgerichtes", "der Bundespräsident / die Bundespräsidentin", "der Bundesratspräsident / die Bundesratspräsidentin", "der Bundestagspräsident / die Bundestagspräsidentin"]'::jsonb, correct_answer = 2 WHERE id = 58;
UPDATE questions SET answers = '["CDU und SSW", "PDS und WASG", "CSU und FDP", "Bündnis 90/Die Grünen und SPD"]'::jsonb, correct_answer = 2 WHERE id = 59;
UPDATE questions SET answers = '["Exekutive.", "Legislative.", "Direktive.", "Judikative."]'::jsonb, correct_answer = 2 WHERE id = 60;
UPDATE questions SET answers = '["Der König / die Königin herrscht über das Volk.", "Das Bundesverfassungsgericht steht über der Verfassung.", "Die Interessenverbände üben die Souveränität zusammen mit der Regierung aus.", "Die Staatsgewalt geht vom Volke aus."]'::jsonb, correct_answer = 4 WHERE id = 61;
UPDATE questions SET answers = '["Kommunalwahl.", "Landtagswahl.", "Europawahl.", "Bundestagswahl."]'::jsonb, correct_answer = 2 WHERE id = 62;
UPDATE questions SET answers = '["die Polizei", "die Gerichte", "das Finanzamt", "die Ministerien"]'::jsonb, correct_answer = 2 WHERE id = 63;
UPDATE questions SET answers = '["vier Besatzungszonen.", "einen Oststaat und einen Weststaat.", "16 Kantone.", "Bund, Länder und Kommunen."]'::jsonb, correct_answer = 4 WHERE id = 64;
UPDATE questions SET answers = '["Gesetze zu entwerfen.", "die Bundesregierung zu kontrollieren.", "den Bundeskanzler / die Bundeskanzlerin zu wählen.", "das Bundeskabinett zu bilden."]'::jsonb, correct_answer = 4 WHERE id = 65;
UPDATE questions SET answers = '["Friedrich von Schiller", "Clemens Brentano", "Johann Wolfgang von Goethe", "Heinrich Hoffmann von Fallersleben"]'::jsonb, correct_answer = 4 WHERE id = 66;
UPDATE questions SET answers = '["Verteidigungspolitik", "Außenpolitik", "Wirtschaftspolitik", "Schulpolitik"]'::jsonb, correct_answer = 4 WHERE id = 67;
UPDATE questions SET answers = '["weil es in Deutschland nur staatliche Schulen gibt", "weil alle Schüler und Schülerinnen einen Schulabschluss haben müssen", "weil es in den Bundesländern verschiedene Schulen gibt", "weil es nach dem Grundgesetz seine Aufgabe ist"]'::jsonb, correct_answer = 4 WHERE id = 68;
UPDATE questions SET answers = '["Stadträte", "Landräte", "Gemeinden und Kommunen", "Bezirksämter"]'::jsonb, correct_answer = 3 WHERE id = 69;
UPDATE questions SET answers = '["Er / Sie führt die Regierungsgeschäfte.", "Er / Sie kontrolliert die Regierungspartei.", "Er / Sie wählt die Minister / Ministerinnen aus.", "Er / Sie schlägt den Kanzler / die Kanzlerin zur Wahl vor."]'::jsonb, correct_answer = 4 WHERE id = 70;
UPDATE questions SET answers = '["in Bonn, weil sich dort das Bundeskanzleramt und der Bundestag befinden.", "in Berlin, weil sich dort das Bundeskanzleramt und der Bundestag befinden.", "auf Schloss Meseberg, dem Gästehaus der Bundesregierung, um Staatsgäste zu empfangen.", "auf Schloss Bellevue, dem Amtssitz des Bundespräsidenten / der Bundespräsidentin, um Staatsgäste zu empfangen."]'::jsonb, correct_answer = 2 WHERE id = 71;
UPDATE questions SET answers = '["Gerhard Schröder", "Jürgen Rüttgers", "Klaus Wowereit", "Olaf Scholz"]'::jsonb, correct_answer = 4 WHERE id = 72;
UPDATE questions SET answers = '["CDU/CSU und SPD.", "Die Linke und Bündnis 90/Die Grünen.", "FDP und SPD.", "Die Linke und FDP."]'::jsonb, correct_answer = 1 WHERE id = 73;
UPDATE questions SET answers = '["Bundesversammlung", "Volkskammer", "Bundestag", "Bundesgerichtshof"]'::jsonb, correct_answer = 3 WHERE id = 74;
UPDATE questions SET answers = '["Frank-Walter Steinmeier", "Norbert Lammert", "Wolfgang Thierse", "Edmund Stoiber"]'::jsonb, correct_answer = 1 WHERE id = 75;
UPDATE questions SET answers = '["Christliche Deutsche Union", "Club Deutscher Unternehmer", "Christlicher Deutscher Umweltschutz", "Christlich Demokratische Union"]'::jsonb, correct_answer = 4 WHERE id = 76;
UPDATE questions SET answers = '["die deutsche Polizei", "ein deutscher Hafen", "eine deutsche Bürgerinitiative", "die deutsche Armee"]'::jsonb, correct_answer = 4 WHERE id = 77;
UPDATE questions SET answers = '["Sozialistische Partei Deutschlands", "Sozialpolitische Partei Deutschlands", "Sozialdemokratische Partei Deutschlands", "Sozialgerechte Partei Deutschlands"]'::jsonb, correct_answer = 3 WHERE id = 78;
UPDATE questions SET answers = '["Friedliche Demonstrative Partei", "Freie Deutschland Partei", "Führende Demokratische Partei", "Freie Demokratische Partei"]'::jsonb, correct_answer = 4 WHERE id = 79;
UPDATE questions SET answers = '["Oberlandesgericht", "Amtsgericht", "Bundesverfassungsgericht", "Verwaltungsgericht"]'::jsonb, correct_answer = 3 WHERE id = 80;
UPDATE questions SET answers = '["der Bundesrat", "die Bundesversammlung", "das Volk", "der Bundestag"]'::jsonb, correct_answer = 4 WHERE id = 81;
UPDATE questions SET answers = '["der Bundestagspräsident / die Bundestagspräsidentin", "der Bundespräsident / die Bundespräsidentin", "der Bundeskanzler / die Bundeskanzlerin", "der Bundesratspräsident / die Bundesratspräsidentin"]'::jsonb, correct_answer = 3 WHERE id = 82;
UPDATE questions SET answers = '["das Volk", "die Bundesversammlung", "der Bundestag", "die Bundesregierung"]'::jsonb, correct_answer = 3 WHERE id = 83;
UPDATE questions SET answers = '["regiert das Land.", "entwirft die Gesetze.", "repräsentiert das Land.", "überwacht die Einhaltung der Gesetze."]'::jsonb, correct_answer = 3 WHERE id = 84;
UPDATE questions SET answers = '["die Abgeordneten des Bundestages", "die Minister und Ministerinnen der Bundesregierung", "die Regierungsvertreter der Bundesländer", "die Parteimitglieder"]'::jsonb, correct_answer = 3 WHERE id = 85;
UPDATE questions SET answers = '["die Bundesversammlung", "der Bundesrat", "das Bundesparlament", "das Bundesverfassungsgericht"]'::jsonb, correct_answer = 1 WHERE id = 86;
UPDATE questions SET answers = '["der Bundeskanzler / die Bundeskanzlerin", "der Bundespräsident / die Bundespräsidentin", "der Bundesratspräsident / die Bundesratspräsidentin", "der Bundestagspräsident / die Bundestagspräsidentin"]'::jsonb, correct_answer = 2 WHERE id = 87;
UPDATE questions SET answers = '["kontrolliert die Regierung.", "entscheidet, wer Bundesminister / Bundesministerin wird.", "bestimmt, wer im Bundesrat sitzt.", "schlägt die Regierungschefs / Regierungschefinnen der Länder vor."]'::jsonb, correct_answer = 1 WHERE id = 88;
UPDATE questions SET answers = '["Verband", "Ältestenrat", "Fraktion", "Opposition"]'::jsonb, correct_answer = 3 WHERE id = 89;
UPDATE questions SET answers = '["den Bundesrat.", "die Bundesversammlung.", "den Bundestag.", "die Bundesregierung."]'::jsonb, correct_answer = 1 WHERE id = 90;
UPDATE questions SET answers = '["schwieriger, wenn sich dadurch die Mehrheit im Bundestag ändert.", "leichter, wenn dadurch neue Parteien in den Bundesrat kommen.", "schwieriger, wenn dadurch die Mehrheit im Bundesrat verändert wird.", "leichter, wenn es sich um ein reiches Bundesland handelt."]'::jsonb, correct_answer = 3 WHERE id = 91;
UPDATE questions SET answers = '["Christlich Sichere Union", "Christlich Süddeutsche Union", "Christlich Sozialer Unternehmerverband", "Christlich Soziale Union"]'::jsonb, correct_answer = 4 WHERE id = 92;
UPDATE questions SET answers = '["mehr Sitze erhält die Partei im Parlament.", "weniger Erststimmen kann sie haben.", "mehr Direktkandidaten der Partei ziehen ins Parlament ein.", "größer ist das Risiko, eine Koalition bilden zu müssen."]'::jsonb, correct_answer = 1 WHERE id = 93;
UPDATE questions SET answers = '["16", "18", "21", "23"]'::jsonb, correct_answer = 2 WHERE id = 94;
UPDATE questions SET answers = '["Wahlpflicht", "Schulpflicht", "Schweigepflicht", "Religionspflicht"]'::jsonb, correct_answer = 2 WHERE id = 95;
UPDATE questions SET answers = '["einen Reisepass", "einen Personalausweis", "einen Sozialversicherungsausweis", "einen Führerschein"]'::jsonb, correct_answer = 2 WHERE id = 96;
UPDATE questions SET answers = '["Sozialversicherung", "Sozialhilfe", "Kindergeld", "Wohngeld"]'::jsonb, correct_answer = 1 WHERE id = 97;
UPDATE questions SET answers = '["kann die Regierung ihre Mehrheit verlieren.", "dürfen sie nicht mehr an den Sitzungen des Parlaments teilnehmen.", "muss der Bundespräsident / die Bundespräsidentin zuvor sein / ihr Einverständnis geben.", "dürfen die Wähler / Wählerinnen dieser Abgeordneten noch einmal wählen."]'::jsonb, correct_answer = 1 WHERE id = 98;
UPDATE questions SET answers = '["Arbeitgeber / Arbeitgeberinnen und Arbeitnehmer / Arbeitnehmerinnen", "nur Arbeitnehmer / Arbeitnehmerinnen", "alle Staatsangehörigen", "nur Arbeitgeber / Arbeitgeberinnen"]'::jsonb, correct_answer = 1 WHERE id = 99;
UPDATE questions SET answers = '["die gesetzliche Rentenversicherung", "die Lebensversicherung", "die Arbeitslosenversicherung", "die Pflegeversicherung"]'::jsonb, correct_answer = 2 WHERE id = 100;
UPDATE questions SET answers = '["Jugendlichen.", "Arbeitnehmer und Arbeitnehmerinnen.", "Rentner und Rentnerinnen.", "Arbeitgeber und Arbeitgeberinnen."]'::jsonb, correct_answer = 2 WHERE id = 101;
UPDATE questions SET answers = '["Bundesadler", "Bundesverdienstkreuz", "Vaterländischen Verdienstorden", "Ehrentitel „Held der Deutschen Demokratischen Republik“"]'::jsonb, correct_answer = 2 WHERE id = 102;
UPDATE questions SET answers = '["der Bundestagsfraktionen von CDU und CSU", "von SPD, FDP und Bündnis 90/Die Grünen in einer Regierung", "von CSU, Die LINKE und Bündnis 90/Die Grünen in einer Regierung", "der Bundestagsfraktionen von CDU und SPD"]'::jsonb, correct_answer = 2 WHERE id = 103;
UPDATE questions SET answers = '["Die Frau ist lange krank und arbeitsunfähig.", "Die Frau kam oft zu spät zur Arbeit.", "Die Frau erledigt private Sachen während der Arbeitszeit.", "Die Frau bekommt ein Kind und ihr Chef weiß das."]'::jsonb, correct_answer = 4 WHERE id = 104;
UPDATE questions SET answers = '["Sie helfen alten Menschen bei der Stimmabgabe in der Wahlkabine.", "Sie schreiben die Wahlbenachrichtigungen vor der Wahl.", "Sie geben Zwischenergebnisse an die Medien weiter.", "Sie zählen die Stimmen nach dem Ende der Wahl."]'::jsonb, correct_answer = 4 WHERE id = 105;
UPDATE questions SET answers = '["Sie helfen Kindern und alten Menschen beim Wählen.", "Sie schreiben Karten und Briefe mit der Angabe des Wahllokals.", "Sie geben Zwischenergebnisse an Journalisten weiter.", "Sie zählen die Stimmen nach dem Ende der Wahl."]'::jsonb, correct_answer = 4 WHERE id = 106;
UPDATE questions SET answers = '["2 Jahre", "4 Jahre", "6 Jahre", "8 Jahre"]'::jsonb, correct_answer = 2 WHERE id = 107;
UPDATE questions SET answers = '["in der Bundesrepublik Deutschland wohnt und wählen möchte.", "Bürger / Bürgerin der Bundesrepublik Deutschland ist und mindestens 18 Jahre alt ist.", "seit mindestens 3 Jahren in der Bundesrepublik Deutschland lebt.", "Bürger / Bürgerin der Bundesrepublik Deutschland ist und mindestens 21 Jahre alt ist."]'::jsonb, correct_answer = 2 WHERE id = 108;
UPDATE questions SET answers = '["alle drei Jahre", "alle vier Jahre", "alle fünf Jahre", "alle sechs Jahre"]'::jsonb, correct_answer = 2 WHERE id = 109;
UPDATE questions SET answers = '["2 Jahre", "3 Jahre", "4 Jahre", "5 Jahre"]'::jsonb, correct_answer = 3 WHERE id = 110;
UPDATE questions SET answers = '["Alle deutschen Staatsangehörigen dürfen wählen, wenn sie das Mindestalter erreicht haben.", "Nur verheiratete Personen dürfen wählen.", "Nur Personen mit einem festen Arbeitsplatz dürfen wählen.", "Alle Einwohner und Einwohnerinnen in Deutschland müssen wählen."]'::jsonb, correct_answer = 1 WHERE id = 111;
UPDATE questions SET answers = '["speziell.", "geheim.", "berufsbezogen.", "geschlechtsabhängig."]'::jsonb, correct_answer = 2 WHERE id = 112;
UPDATE questions SET answers = '["die meisten Stimmen bekommt.", "die meisten Männer mehrheitlich gewählt haben.", "die meisten Stimmen bei den Arbeitern / Arbeiterinnen bekommen hat.", "die meisten Erststimmen für ihren Kanzlerkandidaten / ihre Kanzlerkandidatin erhalten hat."]'::jsonb, correct_answer = 1 WHERE id = 113;
UPDATE questions SET answers = '["eine Pflicht.", "ein Recht.", "ein Zwang.", "eine Last."]'::jsonb, correct_answer = 2 WHERE id = 114;
UPDATE questions SET answers = '["Man kann gewählt werden.", "Man muss wählen gehen.", "Man kann wählen.", "Man muss zur Auszählung der Stimmen gehen."]'::jsonb, correct_answer = 3 WHERE id = 115;
UPDATE questions SET answers = '["aktive Wahlkampagne.", "aktives Wahlverfahren.", "aktiver Wahlkampf.", "aktives Wahlrecht."]'::jsonb, correct_answer = 4 WHERE id = 116;
UPDATE questions SET answers = '["3 %", "4 %", "5 %", "6 %"]'::jsonb, correct_answer = 3 WHERE id = 117;
UPDATE questions SET answers = '["Wer wählen darf, muss wählen.", "Alle die wollen, können wählen.", "Wer nicht wählt, verliert das Recht zu wählen.", "Wer wählen darf, kann wählen."]'::jsonb, correct_answer = 4 WHERE id = 118;
UPDATE questions SET answers = '["Alle verurteilten Straftäter / Straftäterinnen dürfen nicht wählen.", "Wenn ich wählen gehen möchte, muss mein Arbeitgeber / meine Arbeitgeberin mir frei geben.", "Jede Person kann ohne Zwang entscheiden, ob sie wählen möchte und wen sie wählen möchte.", "Ich kann frei entscheiden, wo ich wählen gehen möchte."]'::jsonb, correct_answer = 3 WHERE id = 119;
UPDATE questions SET answers = '["Zensuswahlrecht.", "Dreiklassenwahlrecht.", "Mehrheits- und Verhältniswahlrecht.", "allgemeines Männerwahlrecht."]'::jsonb, correct_answer = 3 WHERE id = 120;
UPDATE questions SET answers = '["5 %-Hürde.", "Zulassungsgrenze.", "Basiswert.", "Richtlinie."]'::jsonb, correct_answer = 1 WHERE id = 121;
UPDATE questions SET answers = '["frei, gleich, geheim.", "offen, sicher, frei.", "geschlossen, gleich, sicher.", "sicher, offen, freiwillig."]'::jsonb, correct_answer = 1 WHERE id = 122;
UPDATE questions SET answers = '["Abstimmungsregelung im Bundestag für kleine Parteien", "Anwesenheitskontrolle im Bundestag für Abstimmungen", "Mindestanteil an Wählerstimmen, um ins Parlament zu kommen", "Anwesenheitskontrolle im Bundesrat für Abstimmungen"]'::jsonb, correct_answer = 3 WHERE id = 123;
UPDATE questions SET answers = '["des Bundeskanzlers / der Bundeskanzlerin.", "der Parlamente der Länder.", "des Parlaments für Deutschland.", "des Bundespräsidenten / der Bundespräsidentin."]'::jsonb, correct_answer = 3 WHERE id = 124;
UPDATE questions SET answers = '["die Bürger und Bürgerinnen zu zwingen, ihre Stimme abzugeben.", "nach dem Willen der Wählermehrheit den Wechsel der Regierung zu ermöglichen.", "im Land bestehende Gesetze beizubehalten.", "den Armen mehr Macht zu geben."]'::jsonb, correct_answer = 2 WHERE id = 125;
UPDATE questions SET answers = '["eine Wahlbenachrichtigung von der Gemeinde", "eine Wahlerlaubnis vom Bundespräsidenten / von der Bundespräsidentin", "eine Benachrichtigung von der Bundesversammlung", "eine Benachrichtigung vom Pfarramt"]'::jsonb, correct_answer = 1 WHERE id = 126;
UPDATE questions SET answers = '["die Programme von vielen kleinen Parteien viele Gemeinsamkeiten haben.", "die Bürger und Bürgerinnen bei vielen kleinen Parteien die Orientierung verlieren können.", "viele kleine Parteien die Regierungsbildung erschweren.", "die kleinen Parteien nicht so viel Geld haben, um die Politiker und Politikerinnen zu bezahlen."]'::jsonb, correct_answer = 3 WHERE id = 127;
UPDATE questions SET answers = '["Abgeordnete.", "Kanzler / Kanzlerinnen.", "Botschafter / Botschafterinnen.", "Ministerpräsidenten / Ministerpräsidentinnen."]'::jsonb, correct_answer = 1 WHERE id = 128;
UPDATE questions SET answers = '["der Bundeskanzler / die Bundeskanzlerin.", "der Ministerpräsident / die Ministerpräsidentin eines Bundeslandes.", "der Bundestag.", "der Bundespräsident / die Bundespräsidentin."]'::jsonb, correct_answer = 3 WHERE id = 129;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 1 WHERE id = 130;
UPDATE questions SET answers = '["der Leiter / die Leiterin einer Schule.", "der Chef / die Chefin einer Bank.", "das Oberhaupt einer Gemeinde.", "der / die Vorsitzende einer Partei."]'::jsonb, correct_answer = 3 WHERE id = 131;
UPDATE questions SET answers = '["Sie arbeiten als Soldaten / Soldatinnen.", "Sie arbeiten freiwillig und unbezahlt in Vereinen und Verbänden.", "Sie arbeiten in der Bundesregierung.", "Sie arbeiten in einem Krankenhaus und verdienen dabei Geld."]'::jsonb, correct_answer = 2 WHERE id = 132;
UPDATE questions SET answers = '["Der Ehemann wählt für seine Frau mit.", "Man kann durch Briefwahl seine Stimme abgeben.", "Man kann am Wahltag telefonisch seine Stimme abgeben.", "Kinder ab dem Alter von 14 Jahren dürfen wählen."]'::jsonb, correct_answer = 2 WHERE id = 133;
UPDATE questions SET answers = '["Ich beteilige mich an einer Bürgerinitiative für die Erhaltung der Buslinie oder gründe selber eine Initiative.", "Ich werde Mitglied in einem Sportverein und trainiere Radfahren.", "Ich wende mich an das Finanzamt, weil ich als Steuerzahler / Steuerzahlerin ein Recht auf die Buslinie habe.", "Ich schreibe einen Brief an das Forstamt der Gemeinde."]'::jsonb, correct_answer = 1 WHERE id = 134;
UPDATE questions SET answers = '["große Unternehmen", "kleine Unternehmen", "Selbständige", "Arbeitnehmer und Arbeitnehmerinnen"]'::jsonb, correct_answer = 4 WHERE id = 135;
UPDATE questions SET answers = '["falscher Nebenkostenabrechnung.", "ungerechtfertigter Kündigung durch Ihren Chef / Ihre Chefin.", "Problemen mit den Nachbarn / Nachbarinnen.", "Schwierigkeiten nach einem Verkehrsunfall."]'::jsonb, correct_answer = 2 WHERE id = 136;
UPDATE questions SET answers = '["das Familiengericht", "das Strafgericht", "das Arbeitsgericht", "das Amtsgericht"]'::jsonb, correct_answer = 3 WHERE id = 137;
UPDATE questions SET answers = '["weiter arbeiten und freundlich zum Chef / zur Chefin sein", "ein Mahnverfahren gegen den Arbeitgeber / die Arbeitgeberin führen", "Kündigungsschutzklage erheben", "den Arbeitgeber / die Arbeitgeberin bei der Polizei anzeigen"]'::jsonb, correct_answer = 3 WHERE id = 138;
UPDATE questions SET answers = '["zu einer anderen Religion übertritt.", "eine Straftat begangen hat und angeklagt wird.", "eine andere Meinung als die der Regierung vertritt.", "sein Auto falsch geparkt hat und es abgeschleppt wird."]'::jsonb, correct_answer = 2 WHERE id = 139;
UPDATE questions SET answers = '["entscheidet mit Richtern / Richterinnen über Schuld und Strafe.", "gibt Bürgern / Bürgerinnen rechtlichen Rat.", "stellt Urkunden aus.", "verteidigt den Angeklagten / die Angeklagte."]'::jsonb, correct_answer = 1 WHERE id = 140;
UPDATE questions SET answers = '["ein Rechtsanwalt / eine Rechtsanwältin", "ein Richter / eine Richterin", "ein Schöffe / eine Schöffin", "ein Staatsanwalt / eine Staatsanwältin"]'::jsonb, correct_answer = 1 WHERE id = 141;
UPDATE questions SET answers = '["vertritt Bürger und Bürgerinnen vor einem Gericht.", "arbeitet an einem Gericht und spricht Urteile.", "ändert Gesetze.", "betreut Jugendliche vor Gericht."]'::jsonb, correct_answer = 2 WHERE id = 142;
UPDATE questions SET answers = '["Judikative.", "Exekutive.", "Operative.", "Legislative."]'::jsonb, correct_answer = 1 WHERE id = 143;
UPDATE questions SET answers = '["vollziehenden Gewalt.", "rechtsprechenden Gewalt.", "planenden Gewalt.", "gesetzgebenden Gewalt."]'::jsonb, correct_answer = 2 WHERE id = 144;
UPDATE questions SET answers = '["Judikative.", "Exekutive.", "Presse.", "Legislative."]'::jsonb, correct_answer = 1 WHERE id = 145;
UPDATE questions SET answers = '["Programm", "Prozedur", "Protokoll", "Prozess"]'::jsonb, correct_answer = 4 WHERE id = 146;
UPDATE questions SET answers = '["Deutschland regieren", "Recht sprechen", "Pläne erstellen", "Gesetze erlassen"]'::jsonb, correct_answer = 2 WHERE id = 147;
UPDATE questions SET answers = '["das Land zu verteidigen", "die Bürgerinnen und Bürger abzuhören", "die Gesetze zu beschließen", "die Einhaltung von Gesetzen zu überwachen"]'::jsonb, correct_answer = 4 WHERE id = 148;
UPDATE questions SET answers = '["alle in Deutschland geborenen Einwohner / Einwohnerinnen über 18 Jahre", "alle deutschen Staatsangehörigen älter als 24 und jünger als 70 Jahre", "alle Personen, die seit mindestens 5 Jahren in Deutschland leben", "nur Personen mit einem abgeschlossenen Jurastudium"]'::jsonb, correct_answer = 2 WHERE id = 149;
UPDATE questions SET answers = '["der Stellvertreter / die Stellvertreterin des Stadtoberhaupts.", "ein ehrenamtlicher Richter / eine ehrenamtliche Richterin.", "ein Mitglied eines Gemeinderats.", "eine Person, die Jura studiert hat."]'::jsonb, correct_answer = 2 WHERE id = 150;
UPDATE questions SET answers = '["Großbritannien", "die Bundesrepublik Deutschland", "die DDR", "die USA"]'::jsonb, correct_answer = 3 WHERE id = 151;
UPDATE questions SET answers = '["1918 bis 1923", "1932 bis 1950", "1933 bis 1945", "1945 bis 1989"]'::jsonb, correct_answer = 3 WHERE id = 152;
UPDATE questions SET answers = '["Tod Adolf Hitlers", "Beginn des Berliner Mauerbaus", "Wahl von Konrad Adenauer zum Bundeskanzler", "Ende des Zweiten Weltkriegs in Europa"]'::jsonb, correct_answer = 4 WHERE id = 153;
UPDATE questions SET answers = '["1933", "1945", "1949", "1961"]'::jsonb, correct_answer = 2 WHERE id = 154;
UPDATE questions SET answers = '["1888 bis 1918", "1921 bis 1934", "1933 bis 1945", "1949 bis 1963"]'::jsonb, correct_answer = 3 WHERE id = 155;
UPDATE questions SET answers = '["1923", "1927", "1933", "1936"]'::jsonb, correct_answer = 3 WHERE id = 156;
UPDATE questions SET answers = '["eine Diktatur.", "einen demokratischen Staat.", "eine Monarchie.", "ein Fürstentum."]'::jsonb, correct_answer = 1 WHERE id = 157;
UPDATE questions SET answers = '["Diktatur", "Demokratie.", "Monarchie.", "Räterepublik."]'::jsonb, correct_answer = 1 WHERE id = 158;
UPDATE questions SET answers = '["freie Wahlen", "Pressezensur", "willkürliche Verhaftungen", "Verfolgung der Juden"]'::jsonb, correct_answer = 1 WHERE id = 159;
UPDATE questions SET answers = '["der Erste Weltkrieg", "der Zweite Weltkrieg", "der Vietnamkrieg", "der Golfkrieg"]'::jsonb, correct_answer = 2 WHERE id = 160;
UPDATE questions SET answers = '["des staatlichen Rassismus", "der Meinungsfreiheit", "der allgemeinen Religionsfreiheit", "der Entwicklung der Demokratie"]'::jsonb, correct_answer = 1 WHERE id = 161;
UPDATE questions SET answers = '["eine Goldmedaille bei den Olympischen Spielen 1936.", "den Bau des Reichstagsgebäudes.", "den Aufbau der Wehrmacht.", "das Attentat auf Hitler am 20. Juli 1944."]'::jsonb, correct_answer = 4 WHERE id = 162;
UPDATE questions SET answers = '["1925", "1930", "1938", "1945"]'::jsonb, correct_answer = 3 WHERE id = 163;
UPDATE questions SET answers = '["Mit dem Angriff auf Polen beginnt der Zweite Weltkrieg.", "Die Nationalsozialisten verlieren eine Wahl und lösen den Reichstag auf.", "Jüdische Geschäfte und Synagogen werden durch Nationalsozialisten und ihre Anhänger zerstört.", "Hitler wird Reichspräsident und lässt alle Parteien verbieten."]'::jsonb, correct_answer = 3 WHERE id = 164;
UPDATE questions SET answers = '["Konrad Adenauer", "Kurt Georg Kiesinger", "Helmut Schmidt", "Willy Brandt"]'::jsonb, correct_answer = 1 WHERE id = 165;
UPDATE questions SET answers = '["bei den Montagsdemonstrationen 1989 in der DDR", "beim Arbeiteraufstand 1953 in der DDR", "bei den Demonstrationen 1968 in der Bundesrepublik Deutschland", "bei den Anti-Atomkraft-Demonstrationen 1985 in der Bundesrepublik Deutschland"]'::jsonb, correct_answer = 1 WHERE id = 166;
UPDATE questions SET answers = '["Sowjetunion, Großbritannien, Polen, Schweden", "Frankreich, Sowjetunion, Italien, Japan", "USA, Sowjetunion, Spanien, Portugal", "USA, Sowjetunion, Großbritannien, Frankreich"]'::jsonb, correct_answer = 4 WHERE id = 167;
UPDATE questions SET answers = '["USA", "Sowjetunion", "Frankreich", "Japan"]'::jsonb, correct_answer = 4 WHERE id = 168;
UPDATE questions SET answers = '["1939", "1945", "1949", "1951"]'::jsonb, correct_answer = 3 WHERE id = 169;
UPDATE questions SET answers = '["das Recht zur freien Entfaltung der Persönlichkeit", "Pressefreiheit", "das Verbot von Parteien", "den Schutz der Menschenwürde"]'::jsonb, correct_answer = 3 WHERE id = 170;
UPDATE questions SET answers = '["steuert sich allein nach Angebot und Nachfrage.", "wird vom Staat geplant und gesteuert, Angebot und Nachfrage werden nicht berücksichtigt.", "richtet sich nach der Nachfrage im Ausland.", "richtet sich nach Angebot und Nachfrage, aber der Staat sorgt für einen sozialen Ausgleich."]'::jsonb, correct_answer = 4 WHERE id = 171;
UPDATE questions SET answers = '["amerikanischen Besatzungszone.", "französischen Besatzungszone.", "britischen Besatzungszone.", "sowjetischen Besatzungszone."]'::jsonb, correct_answer = 4 WHERE id = 172;
UPDATE questions SET answers = '["des Nordatlantikpakts (NATO).", "der Vereinten Nationen (VN).", "der Europäischen Union (EU).", "des Warschauer Pakts."]'::jsonb, correct_answer = 3 WHERE id = 173;
UPDATE questions SET answers = '["1947", "1949", "1953", "1956"]'::jsonb, correct_answer = 2 WHERE id = 174;
UPDATE questions SET answers = '["3", "4", "5", "6"]'::jsonb, correct_answer = 2 WHERE id = 175;
UPDATE questions SET answers = '["1=Großbritannien, 2=Sowjetunion, 3=Frankreich, 4=USA", "1=Sowjetunion, 2=Großbritannien, 3=USA, 4=Frankreich", "1=Großbritannien, 2=Sowjetunion, 3=USA, 4=Frankreich", "1=Großbritannien, 2=USA, 3=Sowjetunion, 4=Frankreich"]'::jsonb, correct_answer = 3 WHERE id = 176;
UPDATE questions SET answers = '["München", "Berlin", "Dresden", "Frankfurt/Oder"]'::jsonb, correct_answer = 2 WHERE id = 177;
UPDATE questions SET answers = '["Für Frankreich war eine Versorgung der West-Berliner Bevölkerung mit dem Flugzeug kostengünstiger.", "Die amerikanischen Soldaten / Soldatinnen hatten beim Landtransport Angst vor Überfällen.", "Für Großbritannien war die Versorgung über die Luftbrücke schneller.", "Die Sowjetunion unterbrach den gesamten Verkehr auf dem Landwege."]'::jsonb, correct_answer = 4 WHERE id = 178;
UPDATE questions SET answers = '["mit dem Tod Adolf Hitlers", "durch die bedingungslose Kapitulation Deutschlands", "mit dem Rückzug der Deutschen aus den besetzten Gebieten", "durch eine Revolution in Deutschland"]'::jsonb, correct_answer = 2 WHERE id = 179;
UPDATE questions SET answers = '["Ludwig Erhard.", "Willy Brandt.", "Konrad Adenauer.", "Gerhard Schröder."]'::jsonb, correct_answer = 3 WHERE id = 180;
UPDATE questions SET answers = '["Er hat sich den ehemaligen Alliierten unterworfen.", "Er bat Polen und die polnischen Juden um Vergebung.", "Er zeigte seine Demut vor dem Warschauer Pakt.", "Er sprach ein Gebet am Grab des Unbekannten Soldaten."]'::jsonb, correct_answer = 2 WHERE id = 181;
UPDATE questions SET answers = '["KPD und SPD", "SPD und CDU", "CDU und FDP", "KPD und CSU"]'::jsonb, correct_answer = 1 WHERE id = 182;
UPDATE questions SET answers = '["40er Jahre", "50er Jahre", "70er Jahre", "80er Jahre"]'::jsonb, correct_answer = 2 WHERE id = 183;
UPDATE questions SET answers = '["Damit wird die Zeit nach der Wende im Jahr 1989 bezeichnet.", "Damit wurde der Beginn des Zweiten Weltkrieges bezeichnet.", "Darunter verstand man das Ende des Zweiten Weltkrieges und den Beginn des Wiederaufbaus.", "Damit ist die Stunde gemeint, in der die Uhr von der Sommerzeit auf die Winterzeit umgestellt wird."]'::jsonb, correct_answer = 3 WHERE id = 184;
UPDATE questions SET answers = '["des Warschauer Pakts gegen den Westen.", "Norddeutschlands gegen Süddeutschland.", "Nazi-Deutschlands gegen die Alliierten.", "Europas gegen die USA."]'::jsonb, correct_answer = 1 WHERE id = 185;
UPDATE questions SET answers = '["45413", "45460", "45493", "45605"]'::jsonb, correct_answer = 2 WHERE id = 186;
UPDATE questions SET answers = '["Preußen", "Bundesrepublik Deutschland", "DDR", "„Drittes Reich“"]'::jsonb, correct_answer = 3 WHERE id = 187;
UPDATE questions SET answers = '["1953", "1956", "1959", "1961"]'::jsonb, correct_answer = 4 WHERE id = 188;
UPDATE questions SET answers = '["1919", "1933", "1961", "1990"]'::jsonb, correct_answer = 3 WHERE id = 189;
UPDATE questions SET answers = '["Dritter Deutscher Rundfunk", "Die Deutsche Republik", "Dritte Deutsche Republik", "Deutsche Demokratische Republik"]'::jsonb, correct_answer = 4 WHERE id = 190;
UPDATE questions SET answers = '["1987", "1989", "1992", "1995"]'::jsonb, correct_answer = 2 WHERE id = 191;
UPDATE questions SET answers = '["Brandenburg", "Bayern", "Saarland", "Hessen"]'::jsonb, correct_answer = 1 WHERE id = 192;
UPDATE questions SET answers = '["ohne Bürgermeister.", "ein eigener Staat.", "durch eine Mauer geteilt.", "nur mit dem Flugzeug erreichbar."]'::jsonb, correct_answer = 3 WHERE id = 193;
UPDATE questions SET answers = '["Einheit.", "Nation.", "Bundesländer.", "Städte."]'::jsonb, correct_answer = 1 WHERE id = 194;
UPDATE questions SET answers = '["Hessen", "Sachsen-Anhalt", "Nordrhein-Westfalen", "Saarland"]'::jsonb, correct_answer = 2 WHERE id = 195;
UPDATE questions SET answers = '["von einer Diktatur zur Demokratie.", "von einer liberalen Marktwirtschaft zum Sozialismus.", "von einer Monarchie zur Sozialdemokratie.", "von einem religiösen Staat zu einem kommunistischen Staat."]'::jsonb, correct_answer = 1 WHERE id = 196;
UPDATE questions SET answers = '["Thüringen", "Hessen", "Bayern", "Bremen"]'::jsonb, correct_answer = 1 WHERE id = 197;
UPDATE questions SET answers = '["Bayern", "Niedersachsen", "Sachsen", "Baden-Württemberg"]'::jsonb, correct_answer = 3 WHERE id = 198;
UPDATE questions SET answers = '["das Parlament.", "das Ministerium für Staatssicherheit.", "eine regierende Partei.", "das Ministerium für Volksbildung."]'::jsonb, correct_answer = 2 WHERE id = 199;
UPDATE questions SET answers = '["Hessen", "Schleswig-Holstein", "Mecklenburg-Vorpommern", "Saarland"]'::jsonb, correct_answer = 3 WHERE id = 200;
UPDATE questions SET answers = '["Niedersachsen, Nordrhein-Westfalen, Hessen, Schleswig-Holstein, Brandenburg", "Mecklenburg-Vorpommern, Brandenburg, Sachsen, Sachsen-Anhalt, Thüringen", "Bayern, Baden-Württemberg, Rheinland-Pfalz, Thüringen, Sachsen", "Sachsen, Thüringen, Hessen, Niedersachsen, Brandenburg"]'::jsonb, correct_answer = 2 WHERE id = 201;
UPDATE questions SET answers = '["zu den Westmächten", "zum Warschauer Pakt", "zur NATO", "zu den blockfreien Staaten"]'::jsonb, correct_answer = 2 WHERE id = 202;
UPDATE questions SET answers = '["Marktwirtschaft", "Planwirtschaft", "Angebot und Nachfrage", "Kapitalismus"]'::jsonb, correct_answer = 2 WHERE id = 203;
UPDATE questions SET answers = '["Die Bundesrepublik Deutschland hat die DDR besetzt.", "Die heutigen fünf östlichen Bundesländer sind der Bundesrepublik Deutschland beigetreten.", "Die westlichen Bundesländer sind der DDR beigetreten.", "Die DDR hat die Bundesrepublik Deutschland besetzt."]'::jsonb, correct_answer = 2 WHERE id = 204;
UPDATE questions SET answers = '["zur Europäischen Union.", "zum Warschauer Pakt.", "zur OPEC.", "zur Europäischen Verteidigungsgemeinschaft."]'::jsonb, correct_answer = 1 WHERE id = 205;
UPDATE questions SET answers = '["In der Bundesrepublik waren Demonstrationen nur am Montag erlaubt.", "Montags waren Demonstrationen gegen das DDR-Regime.", "Am ersten Montag im Monat trafen sich in der Bundesrepublik Deutschland Demonstranten.", "Montags demonstrierte man in der DDR gegen den Westen."]'::jsonb, correct_answer = 2 WHERE id = 206;
UPDATE questions SET answers = '["in der NATO", "im Rheinbund", "im Warschauer Pakt", "im Europabündnis"]'::jsonb, correct_answer = 3 WHERE id = 207;
UPDATE questions SET answers = '["der Geheimdienst im „Dritten Reich“", "eine berühmte deutsche Gedenkstätte", "der Geheimdienst der DDR", "ein deutscher Sportverein während des Zweiten Weltkrieges"]'::jsonb, correct_answer = 3 WHERE id = 208;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 1 WHERE id = 209;
UPDATE questions SET answers = '["der feierliche Beitritt zum Warschauer Pakt", "landesweite Streiks und ein Volksaufstand", "der 1. SED-Parteitag", "der erste Besuch Fidel Castros"]'::jsonb, correct_answer = 2 WHERE id = 210;
UPDATE questions SET answers = '["Helmut Kohl", "Willy Brandt", "Michail Gorbatschow", "Ludwig Erhard"]'::jsonb, correct_answer = 2 WHERE id = 211;
UPDATE questions SET answers = '["Bundesstaat Deutschland", "Bundesländer Deutschland", "Bundesrepublik Deutschland", "Bundesbezirk Deutschland"]'::jsonb, correct_answer = 3 WHERE id = 212;
UPDATE questions SET answers = '["70 Millionen", "78 Millionen", "80 Millionen", "90 Millionen"]'::jsonb, correct_answer = 3 WHERE id = 213;
UPDATE questions SET answers = '["schwarz-rot-gold", "rot-weiß-schwarz", "schwarz-rot-grün", "schwarz-gelb-rot"]'::jsonb, correct_answer = 1 WHERE id = 214;
UPDATE questions SET answers = '["Gerhard Schröder", "Helmut Kohl", "Konrad Adenauer", "Helmut Schmidt"]'::jsonb, correct_answer = 2 WHERE id = 215;
UPDATE questions SET answers = '["die Fahne der Stadt Berlin.", "der Bundesadler.", "der Reichsadler.", "die Reichskrone."]'::jsonb, correct_answer = 2 WHERE id = 216;
UPDATE questions SET answers = '["1919 bis 1927", "1933 bis 1945", "1949 bis 1990", "1945 bis 1961"]'::jsonb, correct_answer = 3 WHERE id = 217;
UPDATE questions SET answers = '["4", "5", "6", "7"]'::jsonb, correct_answer = 2 WHERE id = 218;
UPDATE questions SET answers = '["1933.", "1949.", "1971.", "1990."]'::jsonb, correct_answer = 4 WHERE id = 219;
UPDATE questions SET answers = '["an das Ende des Zweiten Weltkrieges", "an die Verabschiedung des Grundgesetzes", "an die Wiedervereinigung Deutschlands", "an die Opfer des Nationalsozialismus"]'::jsonb, correct_answer = 4 WHERE id = 220;
UPDATE questions SET answers = '["Deutsche können in viele Länder Europas ohne Passkontrolle reisen.", "Alle Menschen können ohne Personenkontrolle in Deutschland einreisen.", "Deutsche können ohne Passkontrolle in jedes Land reisen.", "Deutsche können in jedem Land mit dem Euro bezahlen."]'::jsonb, correct_answer = 1 WHERE id = 221;
UPDATE questions SET answers = '["Ungarn", "Portugal", "Spanien", "Schweiz"]'::jsonb, correct_answer = 4 WHERE id = 222;
UPDATE questions SET answers = '["Rumänien", "Bulgarien", "Polen", "Griechenland"]'::jsonb, correct_answer = 3 WHERE id = 223;
UPDATE questions SET answers = '["Europäische Unternehmen", "Europäische Union", "Einheitliche Union", "Euro Union"]'::jsonb, correct_answer = 2 WHERE id = 224;
UPDATE questions SET answers = '["Tschechien", "Norwegen", "Spanien", "Österreich"]'::jsonb, correct_answer = 4 WHERE id = 225;
UPDATE questions SET answers = '["2", "1", "4", "3"]'::jsonb, correct_answer = 1 WHERE id = 226;
UPDATE questions SET answers = '["Finnland", "Dänemark", "Norwegen", "Schweden"]'::jsonb, correct_answer = 2 WHERE id = 227;
UPDATE questions SET answers = '["NATO-Osterweiterung", "EU-Osterweiterung", "Europäische Gemeinschaft", "Europäische Gemeinschaft"]'::jsonb, correct_answer = 1 WHERE id = 228;
UPDATE questions SET answers = '["Spanien", "Bulgarien", "Norwegen", "Luxemburg"]'::jsonb, correct_answer = 4 WHERE id = 229;
UPDATE questions SET answers = '["5 Jahre.", "6 Jahre.", "7 Jahre.", "8 Jahre."]'::jsonb, correct_answer = 1 WHERE id = 230;
UPDATE questions SET answers = '["Damit sind amerikanische Einwanderer in Europa gemeint.", "Der Begriff meint den Einwanderungsstopp nach Europa.", "Damit sind europäische Auswanderer in den USA gemeint.", "Der Begriff meint den Zusammenschluss europäischer Staaten zur EU."]'::jsonb, correct_answer = 4 WHERE id = 231;
UPDATE questions SET answers = '["die Europäische Kommission", "die Länder, die in die EU eintreten dürfen", "die europäische Verfassung", "die Abgeordneten des Europäischen Parlaments"]'::jsonb, correct_answer = 4 WHERE id = 232;
UPDATE questions SET answers = '["Tschechien", "Bulgarien", "Griechenland", "Portugal"]'::jsonb, correct_answer = 1 WHERE id = 233;
UPDATE questions SET answers = '["London", "Paris", "Berlin", "Straßburg"]'::jsonb, correct_answer = 4 WHERE id = 234;
UPDATE questions SET answers = '["Freundschaft zwischen England und Deutschland", "Reisefreiheit in alle Länder der EU", "Frieden und Sicherheit in den Ländern der EU", "einheitliche Feiertage in den Ländern der EU"]'::jsonb, correct_answer = 3 WHERE id = 235;
UPDATE questions SET answers = '["21", "23", "25", "27"]'::jsonb, correct_answer = 4 WHERE id = 236;
UPDATE questions SET answers = '["Beitritt Deutschlands zur NATO", "Gründung der Europäischen Wirtschaftsgemeinschaft (EWG)", "Verpflichtung Deutschlands zu Reparationsleistungen", "Festlegung der Oder-Neiße-Linie als Ostgrenze"]'::jsonb, correct_answer = 2 WHERE id = 237;
UPDATE questions SET answers = '["Paris, London und Den Haag", "Straßburg, Luxemburg und Brüssel", "Rom, Bern und Wien", "Bonn, Zürich und Mailand"]'::jsonb, correct_answer = 2 WHERE id = 238;
UPDATE questions SET answers = '["durch die „Hamburger Verträge“", "durch die „Römischen Verträge“", "durch die „Pariser Verträge“", "durch die „Londoner Verträge“"]'::jsonb, correct_answer = 2 WHERE id = 239;
UPDATE questions SET answers = '["1995", "1998", "2002", "2005"]'::jsonb, correct_answer = 3 WHERE id = 240;
UPDATE questions SET answers = '["Sie muss an ihre Krankenkasse schreiben.", "Sie muss nichts tun, denn sie bekommt automatisch Elterngeld.", "Sie muss einen Antrag bei der Elterngeldstelle stellen.", "Sie muss das Arbeitsamt um Erlaubnis bitten."]'::jsonb, correct_answer = 3 WHERE id = 241;
UPDATE questions SET answers = '["der Staat", "die Bundesländer", "die Eltern / die Erziehungsberechtigten", "die Schulen"]'::jsonb, correct_answer = 3 WHERE id = 242;
UPDATE questions SET answers = '["Sie müssen nichts tun. Man darf in Deutschland jederzeit überall demonstrieren.", "Sie müssen die Demonstration anmelden.", "Sie können gar nichts tun, denn Demonstrationen sind in Deutschland grundsätzlich verboten.", "Maik und Sybille müssen einen neuen Verein gründen, weil nur Vereine demonstrieren dürfen."]'::jsonb, correct_answer = 2 WHERE id = 243;
UPDATE questions SET answers = '["das Abitur", "ein Diplom", "die Prokura", "eine Gesellenprüfung"]'::jsonb, correct_answer = 1 WHERE id = 244;
UPDATE questions SET answers = '["Hans (20 Jahre) und Marie (19 Jahre)", "Tom (20 Jahre) und Klaus (45 Jahre)", "Sofie (35 Jahre) und Lisa (40 Jahre)", "Anne (13 Jahre) und Tim (25 Jahre)"]'::jsonb, correct_answer = 4 WHERE id = 245;
UPDATE questions SET answers = '["16", "18", "19", "21"]'::jsonb, correct_answer = 2 WHERE id = 246;
UPDATE questions SET answers = '["Elternzeit", "Geburtsvorbereitung", "Mutterschutz", "Wochenbett"]'::jsonb, correct_answer = 3 WHERE id = 247;
UPDATE questions SET answers = '["des Staates.", "der Eltern.", "der Großeltern.", "der Schulen."]'::jsonb, correct_answer = 2 WHERE id = 248;
UPDATE questions SET answers = '["der Staat", "die Eltern", "die Verwandten", "die Schulen"]'::jsonb, correct_answer = 2 WHERE id = 249;
UPDATE questions SET answers = '["katholisch ist.", "gut ausgebildet ist.", "eine Frau ist.", "Mitglied einer Partei ist."]'::jsonb, correct_answer = 2 WHERE id = 250;
UPDATE questions SET answers = '["geht das niemanden etwas an.", "geht das nur die Familie etwas an.", "kann man dafür nicht bestraft werden.", "kann man dafür bestraft werden."]'::jsonb, correct_answer = 4 WHERE id = 251;
UPDATE questions SET answers = '["darf man zur gleichen Zeit nur mit einem Partner / einer Partnerin verheiratet sein.", "kann man mehrere Ehepartner / Ehepartnerinnen gleichzeitig haben.", "darf man nicht wieder heiraten, wenn man einmal verheiratet war.", "darf eine Frau nicht wieder heiraten, wenn ihr Mann gestorben ist."]'::jsonb, correct_answer = 1 WHERE id = 252;
UPDATE questions SET answers = '["beim Einwohnermeldeamt", "beim Standesamt", "beim Ordnungsamt", "beim Gewerbeamt"]'::jsonb, correct_answer = 1 WHERE id = 253;
UPDATE questions SET answers = '["Der Scheidungsprozess dauert ein Jahr.", "Mann und Frau sind ein Jahr verheiratet, dann ist die Scheidung möglich.", "Das Besuchsrecht für die Kinder gilt ein Jahr.", "Mann und Frau führen mindestens ein Jahr getrennt ihr eigenes Leben. Danach ist die Scheidung möglich."]'::jsonb, correct_answer = 4 WHERE id = 254;
UPDATE questions SET answers = '["Ordnungsamt.", "Schulamt.", "Jugendamt.", "Gesundheitsamt."]'::jsonb, correct_answer = 3 WHERE id = 255;
UPDATE questions SET answers = '["eine Erlaubnis der Polizei", "eine Genehmigung einer Partei", "eine Genehmigung des Einwohnermeldeamts", "eine Gaststättenerlaubnis von der zuständigen Behörde"]'::jsonb, correct_answer = 4 WHERE id = 256;
UPDATE questions SET answers = '["einer Hochschule.", "einem Abendgymnasium.", "einer Hauptschule.", "einer Privatuniversität."]'::jsonb, correct_answer = 2 WHERE id = 257;
UPDATE questions SET answers = '["Es entscheidet, welche Schule das Kind besucht.", "Es kann ein Kind, das geschlagen wird oder hungern muss, aus der Familie nehmen.", "Es bezahlt das Kindergeld an die Eltern.", "Es kontrolliert, ob das Kind einen Kindergarten besucht."]'::jsonb, correct_answer = 2 WHERE id = 258;
UPDATE questions SET answers = '["Rentenberechnung.", "Lehrstellensuche.", "Steuererklärung.", "Krankenversicherung."]'::jsonb, correct_answer = 2 WHERE id = 259;
UPDATE questions SET answers = '["Recht auf unbegrenzte Freizeit.", "Wahlfreiheit für alle Fächer.", "Anspruch auf Schulgeld.", "Anwesenheitspflicht."]'::jsonb, correct_answer = 4 WHERE id = 260;
UPDATE questions SET answers = '["einer Hochschule", "einem Abendgymnasium", "einer Hauptschule", "einer Privatuniversität"]'::jsonb, correct_answer = 2 WHERE id = 261;
UPDATE questions SET answers = '["Niemand darf z.B. wegen einer Behinderung benachteiligt werden.", "Man darf andere Personen benachteiligen, wenn ausreichende persönliche Gründe hierfür vorliegen.", "Niemand darf gegen Personen klagen, wenn sie benachteiligt wurden.", "Es ist für alle Gesetz, benachteiligten Gruppen jährlich Geld zu spenden."]'::jsonb, correct_answer = 1 WHERE id = 262;
UPDATE questions SET answers = '["werden bestraft.", "werden wie Erwachsene behandelt.", "teilen die Strafe mit ihren Eltern.", "werden nicht bestraft."]'::jsonb, correct_answer = 1 WHERE id = 263;
UPDATE questions SET answers = '["am Rosenmontag", "am Maifeiertag", "beim Oktoberfest", "an Pfingsten"]'::jsonb, correct_answer = 1 WHERE id = 264;
UPDATE questions SET answers = '["zum Einwohnermeldeamt", "zum Ordnungsamt", "zur Agentur für Arbeit", "zum Standesamt"]'::jsonb, correct_answer = 4 WHERE id = 265;
UPDATE questions SET answers = '["wenn die Sonne untergeht", "um 22 Uhr", "wenn die Nachbarn schlafen gehen", "um 0 Uhr, Mitternacht"]'::jsonb, correct_answer = 2 WHERE id = 266;
UPDATE questions SET answers = '["Sie müssen die Entscheidung der volljährigen Tochter respektieren.", "Sie haben das Recht, die Tochter in die elterliche Wohnung zurückzuholen.", "Sie können zur Polizei gehen und die Tochter anzeigen.", "Sie suchen einen anderen Mann für die Tochter."]'::jsonb, correct_answer = 1 WHERE id = 267;
UPDATE questions SET answers = '["Sie muss mindestens zehn Jahre in Deutschland leben, bevor sie den Führerschein machen kann.", "Sie kann die Theorie-Prüfung vielleicht in ihrer Muttersprache machen. Es gibt mehr als zehn Sprachen zur Auswahl.", "Wenn sie kein Deutsch kann, darf sie keinen Führerschein haben.", "Sie muss den Führerschein in dem Land machen, in dem man ihre Sprache spricht."]'::jsonb, correct_answer = 2 WHERE id = 268;
UPDATE questions SET answers = '["monatliches Taschengeld.", "einen Kindergartenplatz.", "einen Platz in einem Sportverein.", "einen Ferienpass."]'::jsonb, correct_answer = 2 WHERE id = 269;
UPDATE questions SET answers = '["für den Religionsunterricht.", "nur für Jugendliche.", "zur Weiterbildung.", "nur für Rentner und Rentnerinnen."]'::jsonb, correct_answer = 3 WHERE id = 270;
UPDATE questions SET answers = '["bunte Eier verstecken", "einen Tannenbaum schmücken", "sich mit Masken und Kostümen verkleiden", "Kürbisse vor die Tür stellen"]'::jsonb, correct_answer = 2 WHERE id = 271;
UPDATE questions SET answers = '["Mann und Frau sind geschieden und leben mit neuen Partnern zusammen.", "Zwei Frauen leben zusammen.", "Ein alleinerziehender Vater lebt mit seinen zwei Kindern zusammen.", "Ein Mann ist mit zwei Frauen zur selben Zeit verheiratet."]'::jsonb, correct_answer = 4 WHERE id = 272;
UPDATE questions SET answers = '["zum Arzt / zur Ärztin.", "zum Gesundheitsamt.", "zum Einwohnermeldeamt.", "zum Jugendamt."]'::jsonb, correct_answer = 4 WHERE id = 273;
UPDATE questions SET answers = '["das Schweigerecht", "das Briefgeheimnis", "die Schweigepflicht", "die Meinungsfreiheit"]'::jsonb, correct_answer = 2 WHERE id = 274;
UPDATE questions SET answers = '["die Einwilligung der Eltern", "ein Attest eines Arztes / einer Ärztin", "die Einwilligung der Kinder", "die Unterstützung eines Anwalts / einer Anwältin"]'::jsonb, correct_answer = 4 WHERE id = 275;
UPDATE questions SET answers = '["Ich kann nichts tun.", "Ich muss mir diese Behandlung gefallen lassen.", "Ich drohe der Person.", "Ich kann mich beim Behördenleiter / bei der Behördenleiterin beschweren."]'::jsonb, correct_answer = 4 WHERE id = 276;
UPDATE questions SET answers = '["kein Englisch spricht.", "zu hohe Gehaltsvorstellungen hat.", "keine Erfahrungen in diesem Beruf hat.", "Mutter ist."]'::jsonb, correct_answer = 4 WHERE id = 277;
UPDATE questions SET answers = '["im Rollstuhl sitzt.", "keine Erfahrung hat.", "zu hohe Gehaltsvorstellungen hat.", "kein Englisch spricht."]'::jsonb, correct_answer = 1 WHERE id = 278;
UPDATE questions SET answers = '["Regeln für die Benutzung öffentlicher Verkehrsmittel.", "alle Mieter und Mieterinnen im Haus.", "Regeln, an die sich alle Bewohner und Bewohnerinnen halten müssen.", "die Adresse des nächsten Ordnungsamtes."]'::jsonb, correct_answer = 3 WHERE id = 279;
UPDATE questions SET answers = '["nichts machen.", "den Bescheid wegwerfen.", "Einspruch einlegen.", "warten, bis ein anderer Bescheid kommt."]'::jsonb, correct_answer = 3 WHERE id = 280;
UPDATE questions SET answers = '["Meinungsfreiheit", "Gleichbehandlung", "Versammlungsfreiheit", "Freizügigkeit"]'::jsonb, correct_answer = 2 WHERE id = 281;
UPDATE questions SET answers = '["Vereinstrainer / Vereinstrainerin", "Bibliotheksaufsicht", "Wahlhelfer / Wahlhelferin", "Lehrer / Lehrerin"]'::jsonb, correct_answer = 3 WHERE id = 282;
UPDATE questions SET answers = '["Ich lasse die Rechnung liegen.", "Ich lege Widerspruch bei der Behörde ein.", "Ich schicke die Rechnung an die Behörde zurück.", "Ich gehe mit der Rechnung zum Finanzamt."]'::jsonb, correct_answer = 2 WHERE id = 283;
UPDATE questions SET answers = '["Es ist egal, was man lernt.", "Kinder lernen in der Schule alles, was im Beruf wichtig ist. Nach der Schule muss man nicht weiter lernen.", "Erwachsene müssen auch nach der Ausbildung immer weiter lernen.", "Alle müssen früher aufhören zu arbeiten, weil sich alles ändert."]'::jsonb, correct_answer = 3 WHERE id = 284;
UPDATE questions SET answers = '["Umsatzsteuer", "Lohnsteuer", "Beiträge zur Arbeitslosenversicherung", "Beiträge zur Renten- und Krankenversicherung"]'::jsonb, correct_answer = 1 WHERE id = 285;
UPDATE questions SET answers = '["der Betriebsrat", "der Betriebsprüfer / die Betriebsprüferin", "die Betriebsgruppe", "das Betriebsmanagement"]'::jsonb, correct_answer = 1 WHERE id = 286;
UPDATE questions SET answers = '["die Gehaltszahlungen", "die Arbeitszeit", "die Kündigungsfrist", "die Versicherungspflicht"]'::jsonb, correct_answer = 3 WHERE id = 287;
UPDATE questions SET answers = '["beim Finanzamt", "beim Einwohnermeldeamt", "bei der Kommune (Stadt oder Gemeinde)", "beim Gesundheitsamt"]'::jsonb, correct_answer = 3 WHERE id = 288;
UPDATE questions SET answers = '["seine Deutschkenntnisse zu gering sind.", "er zu hohe Gehaltsvorstellungen hat.", "er eine dunkle Haut hat.", "er keine Erfahrungen im Beruf hat."]'::jsonb, correct_answer = 3 WHERE id = 289;
UPDATE questions SET answers = '["eine Anzeige schreiben", "den Fernseher reklamieren", "das Gerät ungefragt austauschen", "die Garantie verlängern"]'::jsonb, correct_answer = 2 WHERE id = 290;
UPDATE questions SET answers = '["das für die Statistik in Deutschland wichtig ist.", "es eine Kirchensteuer gibt, die an die Einkommen- und Lohnsteuer geknüpft ist.", "man mehr Steuern zahlen muss, wenn man nicht zu einer Kirche gehört.", "die Kirche für die Steuererklärung verantwortlich ist."]'::jsonb, correct_answer = 2 WHERE id = 291;
UPDATE questions SET answers = '["Es dürfen keine Moscheen gebaut werden.", "Alle Menschen glauben an Gott.", "Jeder kann glauben, was er möchte.", "Der Staat entscheidet, an welchen Gott die Menschen glauben."]'::jsonb, correct_answer = 3 WHERE id = 292;
UPDATE questions SET answers = '["Kürbisse vor die Tür stellen", "einen Tannenbaum schmücken", "Eier bemalen", "Raketen in die Luft schießen"]'::jsonb, correct_answer = 3 WHERE id = 293;
UPDATE questions SET answers = '["christlicher Feiertag.", "deutscher Gedenktag.", "internationaler Trauertag.", "bayerischer Brauch."]'::jsonb, correct_answer = 1 WHERE id = 294;
UPDATE questions SET answers = '["der Hinduismus", "das Christentum", "der Buddhismus", "der Islam"]'::jsonb, correct_answer = 2 WHERE id = 295;
UPDATE questions SET answers = '["den Buß- und Bettag.", "das Erntedankfest.", "die Adventszeit.", "Allerheiligen."]'::jsonb, correct_answer = 3 WHERE id = 296;
UPDATE questions SET answers = '["Italien", "Polen", "Marokko", "Türkei"]'::jsonb, correct_answer = 4 WHERE id = 297;
UPDATE questions SET answers = '["Vietnam, Polen, Mosambik.", "Frankreich, Rumänien, Somalia.", "Chile, Ungarn, Simbabwe.", "Nordkorea, Mexiko, Ägypten."]'::jsonb, correct_answer = 1 WHERE id = 298;
UPDATE questions SET answers = '["Schwarzarbeiter / Schwarzarbeiterinnen", "Gastarbeiter / Gastarbeiterinnen", "Zeitarbeiter / Zeitarbeiterinnen", "Schichtarbeiter / Schichtarbeiterinnen"]'::jsonb, correct_answer = 2 WHERE id = 299;
UPDATE questions SET answers = '["Italien", "Spanien", "Portugal", "Türkei"]'::jsonb, correct_answer = 1 WHERE id = 300;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 1 WHERE id = 301;
UPDATE questions SET answers = '["Neckar-Odenwald-Kreis", "Nordfriesland", "Nordfriesland", "Altötting"]'::jsonb, correct_answer = 1 WHERE id = 302;
UPDATE questions SET answers = '["3", "4", "5", "6"]'::jsonb, correct_answer = 3 WHERE id = 303;
UPDATE questions SET answers = '["14", "16", "18", "20"]'::jsonb, correct_answer = 2 WHERE id = 304;
UPDATE questions SET answers = '["blau-weiß-rot", "schwarz-gold", "weiß-blau", "grün-weiß-rot"]'::jsonb, correct_answer = 2 WHERE id = 305;
UPDATE questions SET answers = '["beim Ordnungsamt der Gemeinde", "bei der Verbraucherzentrale", "bei der Landeszentrale für politische Bildung", "bei den Kirchen"]'::jsonb, correct_answer = 3 WHERE id = 306;
UPDATE questions SET answers = '["Heidelberg.", "Stuttgart.", "Karlsruhe.", "Mannheim."]'::jsonb, correct_answer = 2 WHERE id = 307;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 2 WHERE id = 308;
UPDATE questions SET answers = '["Erster Minister / Erste Ministerin", "Premierminister / Premierministerin", "Bürgermeister / Bürgermeisterin", "Ministerpräsident / Ministerpräsidentin"]'::jsonb, correct_answer = 4 WHERE id = 309;
UPDATE questions SET answers = '["Finanzminister / Finanzministerin", "Justizminister / Justizministerin", "Innenminister / Innenministerin", "Außenminister / Außenministerin"]'::jsonb, correct_answer = 4 WHERE id = 310;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 2 WHERE id = 311;
UPDATE questions SET answers = '["Prignitz", "Rhein-Sieg-Kreis", "Nordfriesland", "Altötting"]'::jsonb, correct_answer = 4 WHERE id = 312;
UPDATE questions SET answers = '["3", "4", "5", "6"]'::jsonb, correct_answer = 3 WHERE id = 313;
UPDATE questions SET answers = '["14", "16", "18", "20"]'::jsonb, correct_answer = 3 WHERE id = 314;
UPDATE questions SET answers = '["blau-weiß-rot", "weiß-blau", "grün-weiß-rot", "schwarz-gelb"]'::jsonb, correct_answer = 2 WHERE id = 315;
UPDATE questions SET answers = '["beim Ordnungsamt der Gemeinde", "bei der Landeszentrale für politische Bildung", "bei der Verbraucherzentrale", "bei den Kirchen"]'::jsonb, correct_answer = 2 WHERE id = 316;
UPDATE questions SET answers = '["Ingolstadt.", "Regensburg.", "Nürnberg.", "München."]'::jsonb, correct_answer = 4 WHERE id = 317;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 4 WHERE id = 318;
UPDATE questions SET answers = '["Erster Minister / Erste Ministerin", "Premierminister / Premierministerin", "Bürgermeister / Bürgermeisterin", "Ministerpräsident / Ministerpräsidentin"]'::jsonb, correct_answer = 4 WHERE id = 319;
UPDATE questions SET answers = '["Justizminister / Justizministerin", "Außenminister / Außenministerin", "Finanzminister / Finanzministerin", "Innenminister / Innenministerin"]'::jsonb, correct_answer = 2 WHERE id = 320;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 4 WHERE id = 321;
UPDATE questions SET answers = '["Altona", "Prignitz", "Pankow", "Demmin"]'::jsonb, correct_answer = 3 WHERE id = 322;
UPDATE questions SET answers = '["3", "4", "5", "6"]'::jsonb, correct_answer = 3 WHERE id = 323;
UPDATE questions SET answers = '["14", "16", "18", "20"]'::jsonb, correct_answer = 2 WHERE id = 324;
UPDATE questions SET answers = '["blau-weiß-rot", "weiß-rot", "grün-weiß-rot", "schwarz-gold"]'::jsonb, correct_answer = 2 WHERE id = 325;
UPDATE questions SET answers = '["beim Ordnungsamt der Gemeinde", "bei den Kirchen", "bei der Verbraucherzentrale", "bei der Landeszentrale für politische Bildung"]'::jsonb, correct_answer = 4 WHERE id = 326;
UPDATE questions SET answers = '["Berlin", "Saarland", "Brandenburg", "Hessen"]'::jsonb, correct_answer = 1 WHERE id = 327;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 4 WHERE id = 328;
UPDATE questions SET answers = '["Ministerpräsident / Ministerpräsidentin", "Oberbürgermeister / Oberbürgermeisterin", "Präsident / Präsidentin des Senats", "Regierender Bürgermeister / Regierende Bürgermeisterin"]'::jsonb, correct_answer = 4 WHERE id = 329;
UPDATE questions SET answers = '["Finanzsenator / Finanzsenatorin", "Innensenator / Innensenatorin", "Senator / Senatorin für Außenbeziehungen", "Justizsenator / Justizsenatorin"]'::jsonb, correct_answer = 3 WHERE id = 330;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 1 WHERE id = 331;
UPDATE questions SET answers = '["Prignitz", "Rhein-Sieg-Kreis", "Vogtlandkreis", "Amberg-Sulzbach"]'::jsonb, correct_answer = 1 WHERE id = 332;
UPDATE questions SET answers = '["3", "4", "5", "6"]'::jsonb, correct_answer = 3 WHERE id = 333;
UPDATE questions SET answers = '["14", "18", "16", "20"]'::jsonb, correct_answer = 3 WHERE id = 334;
UPDATE questions SET answers = '["blau-weiß-rot", "rot-weiß", "grün-weiß-rot", "schwarz-gelb"]'::jsonb, correct_answer = 2 WHERE id = 335;
UPDATE questions SET answers = '["bei den Kirchen", "beim Ordnungsamt der Gemeinde", "bei der Landeszentrale für politische Bildung", "bei der Verbraucherzentrale"]'::jsonb, correct_answer = 3 WHERE id = 336;
UPDATE questions SET answers = '["Potsdam.", "Cottbus.", "Brandenburg.", "Frankfurt/Oder."]'::jsonb, correct_answer = 1 WHERE id = 337;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 4 WHERE id = 338;
UPDATE questions SET answers = '["Erster Minister / Erste Ministerin", "Premierminister / Premierministerin", "Bürgermeister / Bürgermeisterin", "Ministerpräsident / Ministerpräsidentin"]'::jsonb, correct_answer = 4 WHERE id = 339;
UPDATE questions SET answers = '["Justizminister / Justizministerin", "Außenminister / Außenministerin", "Finanzminister / Finanzministerin", "Innenminister / Innenministerin"]'::jsonb, correct_answer = 2 WHERE id = 340;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 3 WHERE id = 341;
UPDATE questions SET answers = '["Altona", "Hemelingen", "Pankow", "Babelsberg"]'::jsonb, correct_answer = 2 WHERE id = 342;
UPDATE questions SET answers = '["3", "4", "5", "6"]'::jsonb, correct_answer = 2 WHERE id = 343;
UPDATE questions SET answers = '["14", "16", "18", "20"]'::jsonb, correct_answer = 2 WHERE id = 344;
UPDATE questions SET answers = '["blau-weiß-rot", "rot-weiß", "grün-weiß-rot", "schwarz-gold"]'::jsonb, correct_answer = 2 WHERE id = 345;
UPDATE questions SET answers = '["beim Ordnungsamt der Gemeinde", "bei der Landeszentrale für politische Bildung", "bei den Kirchen", "bei der Verbraucherzentrale"]'::jsonb, correct_answer = 2 WHERE id = 346;
UPDATE questions SET answers = '["Bremen", "München", "Frankfurt", "Erfurt"]'::jsonb, correct_answer = 1 WHERE id = 347;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 1 WHERE id = 348;
UPDATE questions SET answers = '["Ministerpräsident / Ministerpräsidentin", "Erster Bürgermeister / Erste Bürgermeisterin", "Präsident / Präsidentin des Senats", "Regierender Bürgermeister / Regierende Bürgermeisterin"]'::jsonb, correct_answer = 3 WHERE id = 349;
UPDATE questions SET answers = '["Senator / Senatorin für Außenbeziehungen", "Finanzsenator / Finanzsenatorin", "Justizsenator / Justizsenatorin", "Innensenator / Innensenatorin"]'::jsonb, correct_answer = 1 WHERE id = 350;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 2 WHERE id = 351;
UPDATE questions SET answers = '["Altona", "Hemelingen", "Pankow", "Demmin"]'::jsonb, correct_answer = 1 WHERE id = 352;
UPDATE questions SET answers = '["3", "4", "5", "6"]'::jsonb, correct_answer = 3 WHERE id = 353;
UPDATE questions SET answers = '["14", "16", "18", "20"]'::jsonb, correct_answer = 2 WHERE id = 354;
UPDATE questions SET answers = '["blau-weiß-rot", "weiß-rot", "grün-weiß-rot", "schwarz-gelb"]'::jsonb, correct_answer = 2 WHERE id = 355;
UPDATE questions SET answers = '["beim Ordnungsamt der Gemeinde", "bei der Verbraucherzentrale", "bei den Kirchen", "bei der Landeszentrale für politische Bildung"]'::jsonb, correct_answer = 4 WHERE id = 356;
UPDATE questions SET answers = '["Hamburg", "Sachsen", "Bayern", "Thüringen"]'::jsonb, correct_answer = 1 WHERE id = 357;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 3 WHERE id = 358;
UPDATE questions SET answers = '["Ministerpräsident / Ministerpräsidentin", "Erster Bürgermeister / Erste Bürgermeisterin", "Regierender Senator / Regierende Senatorin", "Oberbürgermeister / Oberbürgermeisterin"]'::jsonb, correct_answer = 2 WHERE id = 359;
UPDATE questions SET answers = '["Justizsenator / Justizsenatorin", "Senator / Senatorin für Außenbeziehungen", "Finanzsenator / Finanzsenatorin", "Innensenator / Innensenatorin"]'::jsonb, correct_answer = 2 WHERE id = 360;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 1 WHERE id = 361;
UPDATE questions SET answers = '["Ammerland", "Altötting", "Prignitz", "Main-Taunus-Kreis"]'::jsonb, correct_answer = 4 WHERE id = 362;
UPDATE questions SET answers = '["3", "4", "5", "6"]'::jsonb, correct_answer = 3 WHERE id = 363;
UPDATE questions SET answers = '["14", "16", "18", "20"]'::jsonb, correct_answer = 3 WHERE id = 364;
UPDATE questions SET answers = '["blau-weiß-rot", "rot-weiß", "schwarz-gold", "grün-weiß-rot"]'::jsonb, correct_answer = 2 WHERE id = 365;
UPDATE questions SET answers = '["bei der Landeszentrale für politische Bildung", "bei der Verbraucherzentrale", "beim Ordnungsamt der Gemeinde", "bei den Kirchen"]'::jsonb, correct_answer = 1 WHERE id = 366;
UPDATE questions SET answers = '["Kassel.", "Darmstadt.", "Frankfurt.", "Wiesbaden."]'::jsonb, correct_answer = 4 WHERE id = 367;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 3 WHERE id = 368;
UPDATE questions SET answers = '["Erster Minister / Erste Ministerin", "Premierminister / Premierministerin", "Bürgermeister / Bürgermeisterin", "Ministerpräsident / Ministerpräsidentin"]'::jsonb, correct_answer = 4 WHERE id = 369;
UPDATE questions SET answers = '["Justizminister / Justizministerin", "Außenminister / Außenministerin", "Finanzminister / Finanzministerin", "Innenminister / Innenministerin"]'::jsonb, correct_answer = 2 WHERE id = 370;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 3 WHERE id = 371;
UPDATE questions SET answers = '["Prignitz", "Mecklenburgische Seenplatte", "Vogtlandkreis", "Rhein-Sieg-Kreis"]'::jsonb, correct_answer = 2 WHERE id = 372;
UPDATE questions SET answers = '["3", "4", "5", "6"]'::jsonb, correct_answer = 3 WHERE id = 373;
UPDATE questions SET answers = '["14", "16", "18", "20"]'::jsonb, correct_answer = 2 WHERE id = 374;
UPDATE questions SET answers = '["schwarz-rot-gold", "blau-weiß-gelb-rot", "grün-weiß-rot", "schwarz-gelb"]'::jsonb, correct_answer = 2 WHERE id = 375;
UPDATE questions SET answers = '["bei der Landeszentrale für politische Bildung", "bei den Kirchen", "beim Ordnungsamt der Gemeinde", "bei der Verbraucherzentrale"]'::jsonb, correct_answer = 1 WHERE id = 376;
UPDATE questions SET answers = '["Greifswald.", "Schwerin.", "Rostock.", "Wismar."]'::jsonb, correct_answer = 2 WHERE id = 377;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 3 WHERE id = 378;
UPDATE questions SET answers = '["Erster Minister / Erste Ministerin", "Premierminister / Premierministerin", "Bürgermeister / Bürgermeisterin", "Ministerpräsident / Ministerpräsidentin"]'::jsonb, correct_answer = 4 WHERE id = 379;
UPDATE questions SET answers = '["Justizminister / Justizministerin", "Außenminister / Außenministerin", "Finanzminister / Finanzministerin", "Innenminister / Innenministerin"]'::jsonb, correct_answer = 2 WHERE id = 380;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 3 WHERE id = 381;
UPDATE questions SET answers = '["Ammerland", "Rhein-Sieg-Kreis", "Nordfriesland", "Vogtlandkreis"]'::jsonb, correct_answer = 1 WHERE id = 382;
UPDATE questions SET answers = '["3", "4", "5", "6"]'::jsonb, correct_answer = 3 WHERE id = 383;
UPDATE questions SET answers = '["14", "16", "17", "20"]'::jsonb, correct_answer = 2 WHERE id = 384;
UPDATE questions SET answers = '["rot-weiß", "schwarz-rot-gold", "schwarz-gelb", "blau-weiß-rot"]'::jsonb, correct_answer = 2 WHERE id = 385;
UPDATE questions SET answers = '["beim Koordinator für politische Bildung im Kultusministerium", "beim Ordnungsamt der Gemeinde", "bei der Verbraucherzentrale", "bei den Kirchen"]'::jsonb, correct_answer = 1 WHERE id = 386;
UPDATE questions SET answers = '["Hannover.", "Braunschweig.", "Wolfsburg.", "Osnabrück."]'::jsonb, correct_answer = 1 WHERE id = 387;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 1 WHERE id = 388;
UPDATE questions SET answers = '["Erster Minister / Erste Ministerin", "Premierminister / Premierministerin", "Bürgermeister / Bürgermeisterin", "Ministerpräsident / Ministerpräsidentin"]'::jsonb, correct_answer = 4 WHERE id = 389;
UPDATE questions SET answers = '["Justizminister / Justizministerin", "Außenminister / Außenministerin", "Finanzminister / Finanzministerin", "Innenminister / Innenministerin"]'::jsonb, correct_answer = 2 WHERE id = 390;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 2 WHERE id = 391;
UPDATE questions SET answers = '["Ammerland", "Rhein-Sieg-Kreis", "Nordfriesland", "Vogtlandkreis"]'::jsonb, correct_answer = 2 WHERE id = 392;
UPDATE questions SET answers = '["3", "4", "5", "6"]'::jsonb, correct_answer = 3 WHERE id = 393;
UPDATE questions SET answers = '["14", "16", "18", "20"]'::jsonb, correct_answer = 2 WHERE id = 394;
UPDATE questions SET answers = '["rot-weiß", "grün-weiß-rot", "schwarz-gold", "blau-weiß-rot"]'::jsonb, correct_answer = 2 WHERE id = 395;
UPDATE questions SET answers = '["bei den Kirchen", "beim Ordnungsamt der Gemeinde", "bei der Verbraucherzentrale", "bei der Landeszentrale für politische Bildung"]'::jsonb, correct_answer = 4 WHERE id = 396;
UPDATE questions SET answers = '["Köln.", "Bonn.", "Düsseldorf.", "Dortmund."]'::jsonb, correct_answer = 3 WHERE id = 397;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 3 WHERE id = 398;
UPDATE questions SET answers = '["Erster Minister / Erste Ministerin", "Premierminister / Premierministerin", "Bürgermeister / Bürgermeisterin", "Ministerpräsident / Ministerpräsidentin"]'::jsonb, correct_answer = 4 WHERE id = 399;
UPDATE questions SET answers = '["Justizminister / Justizministerin", "Außenminister / Außenministerin", "Finanzminister / Finanzministerin", "Innenminister / Innenministerin"]'::jsonb, correct_answer = 2 WHERE id = 400;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 1 WHERE id = 401;
UPDATE questions SET answers = '["Westerwaldkreis", "Altötting", "Emsland", "Prignitz"]'::jsonb, correct_answer = 1 WHERE id = 402;
UPDATE questions SET answers = '["3", "4", "5", "6"]'::jsonb, correct_answer = 3 WHERE id = 403;
UPDATE questions SET answers = '["14", "16", "18", "20"]'::jsonb, correct_answer = 3 WHERE id = 404;
UPDATE questions SET answers = '["weiß-rot", "schwarz-rot-gold", "schwarz-gelb", "grün-weiß-rot"]'::jsonb, correct_answer = 2 WHERE id = 405;
UPDATE questions SET answers = '["bei den Kirchen", "bei der Verbraucherzentrale", "beim Ordnungsamt der Gemeinde", "bei der Landeszentrale für politische Bildung"]'::jsonb, correct_answer = 4 WHERE id = 406;
UPDATE questions SET answers = '["Mainz.", "Kaiserslautern.", "Ludwigshafen.", "Koblenz."]'::jsonb, correct_answer = 1 WHERE id = 407;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 1 WHERE id = 408;
UPDATE questions SET answers = '["Erster Minister / Erste Ministerin", "Premierminister / Premierministerin", "Bürgermeister / Bürgermeisterin", "Ministerpräsident / Ministerpräsidentin"]'::jsonb, correct_answer = 4 WHERE id = 409;
UPDATE questions SET answers = '["Justizminister / Justizministerin", "Außenminister / Außenministerin", "Finanzminister / Finanzministerin", "Innenminister / Innenministerin"]'::jsonb, correct_answer = 2 WHERE id = 410;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 4 WHERE id = 411;
UPDATE questions SET answers = '["Demmin", "Altötting", "Neunkirchen", "Rhein-Sieg-Kreis"]'::jsonb, correct_answer = 3 WHERE id = 412;
UPDATE questions SET answers = '["3", "4", "5", "6"]'::jsonb, correct_answer = 3 WHERE id = 413;
UPDATE questions SET answers = '["14", "16", "18", "20"]'::jsonb, correct_answer = 3 WHERE id = 414;
UPDATE questions SET answers = '["weiß-blau", "schwarz-rot-gold", "schwarz-gelb", "grün-weiß-rot"]'::jsonb, correct_answer = 2 WHERE id = 415;
UPDATE questions SET answers = '["bei den Kirchen", "bei der Landeszentrale für politische Bildung", "bei der Verbraucherzentrale", "beim Ordnungsamt der Gemeinde"]'::jsonb, correct_answer = 2 WHERE id = 416;
UPDATE questions SET answers = '["Neunkirchen.", "Homburg.", "Saarbrücken.", "Völklingen."]'::jsonb, correct_answer = 3 WHERE id = 417;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 2 WHERE id = 418;
UPDATE questions SET answers = '["Erster Minister / Erste Ministerin", "Premierminister / Premierministerin", "Bürgermeister / Bürgermeisterin", "Ministerpräsident / Ministerpräsidentin"]'::jsonb, correct_answer = 4 WHERE id = 419;
UPDATE questions SET answers = '["Justizminister / Justizministerin", "Außenminister / Außenministerin", "Finanzminister / Finanzministerin", "Innenminister / Innenministerin"]'::jsonb, correct_answer = 2 WHERE id = 420;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 4 WHERE id = 421;
UPDATE questions SET answers = '["Vogtlandkreis", "Altötting", "Uckermark", "Nordfriesland"]'::jsonb, correct_answer = 1 WHERE id = 422;
UPDATE questions SET answers = '["3", "4", "5", "6"]'::jsonb, correct_answer = 3 WHERE id = 423;
UPDATE questions SET answers = '["14", "16", "18", "20"]'::jsonb, correct_answer = 3 WHERE id = 424;
UPDATE questions SET answers = '["blau-weiß-rot", "weiß-grün", "grün-weiß-rot", "schwarz-gelb"]'::jsonb, correct_answer = 2 WHERE id = 425;
UPDATE questions SET answers = '["bei der Landeszentrale für politische Bildung", "beim Ordnungsamt der Gemeinde", "bei den Kirchen", "bei der Verbraucherzentrale"]'::jsonb, correct_answer = 1 WHERE id = 426;
UPDATE questions SET answers = '["Leipzig.", "Dresden.", "Chemnitz.", "Zwickau."]'::jsonb, correct_answer = 2 WHERE id = 427;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 4 WHERE id = 428;
UPDATE questions SET answers = '["Erster Minister / Erste Ministerin", "Premierminister / Premierministerin", "Bürgermeister / Bürgermeisterin", "Ministerpräsident / Ministerpräsidentin"]'::jsonb, correct_answer = 4 WHERE id = 429;
UPDATE questions SET answers = '["Justizminister / Justizministerin", "Außenminister / Außenministerin", "Finanzminister / Finanzministerin", "Innenminister / Innenministerin"]'::jsonb, correct_answer = 2 WHERE id = 430;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 4 WHERE id = 431;
UPDATE questions SET answers = '["Ammerland", "Altötting", "Uckermark", "Börde"]'::jsonb, correct_answer = 4 WHERE id = 432;
UPDATE questions SET answers = '["3", "4", "5", "6"]'::jsonb, correct_answer = 3 WHERE id = 433;
UPDATE questions SET answers = '["14", "16", "18", "20"]'::jsonb, correct_answer = 2 WHERE id = 434;
UPDATE questions SET answers = '["blau-weiß-rot", "gelb-schwarz", "grün-weiß-rot", "weiß-rot"]'::jsonb, correct_answer = 2 WHERE id = 435;
UPDATE questions SET answers = '["bei den Kirchen", "bei der Landeszentrale für politische Bildung", "beim Ordnungsamt der Gemeinde", "bei der Verbraucherzentrale"]'::jsonb, correct_answer = 2 WHERE id = 436;
UPDATE questions SET answers = '["Halle.", "Dessau.", "Magdeburg.", "Wittenberg."]'::jsonb, correct_answer = 3 WHERE id = 437;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 3 WHERE id = 438;
UPDATE questions SET answers = '["Erster Minister / Erste Ministerin", "Premierminister / Premierministerin", "Bürgermeister / Bürgermeisterin", "Ministerpräsident / Ministerpräsidentin"]'::jsonb, correct_answer = 4 WHERE id = 439;
UPDATE questions SET answers = '["Justizminister / Justizministerin", "Außenminister / Außenministerin", "Finanzminister / Finanzministerin", "Innenminister / Innenministerin"]'::jsonb, correct_answer = 2 WHERE id = 440;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 3 WHERE id = 441;
UPDATE questions SET answers = '["Ammerland", "Demmin", "Nordfriesland", "Rhein-Sieg-Kreis"]'::jsonb, correct_answer = 3 WHERE id = 442;
UPDATE questions SET answers = '["3", "4", "5", "6"]'::jsonb, correct_answer = 3 WHERE id = 443;
UPDATE questions SET answers = '["14", "16", "18", "20"]'::jsonb, correct_answer = 2 WHERE id = 444;
UPDATE questions SET answers = '["weiß-blau", "blau-weiß-rot", "weiß-rot", "grün-weiß-rot"]'::jsonb, correct_answer = 2 WHERE id = 445;
UPDATE questions SET answers = '["bei der Verbraucherzentrale", "beim Ordnungsamt der Gemeinde", "bei der Landeszentrale für politische Bildung", "bei den Kirchen"]'::jsonb, correct_answer = 3 WHERE id = 446;
UPDATE questions SET answers = '["Husum.", "Flensburg.", "Lübeck.", "Kiel."]'::jsonb, correct_answer = 4 WHERE id = 447;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 1 WHERE id = 448;
UPDATE questions SET answers = '["Erster Minister / Erste Ministerin", "Premierminister / Premierministerin", "Bürgermeister / Bürgermeisterin", "Ministerpräsident / Ministerpräsidentin"]'::jsonb, correct_answer = 4 WHERE id = 449;
UPDATE questions SET answers = '["Justizminister / Justizministerin", "Außenminister / Außenministerin", "Finanzminister / Finanzministerin", "Innenminister / Innenministerin"]'::jsonb, correct_answer = 2 WHERE id = 450;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 4 WHERE id = 451;
UPDATE questions SET answers = '["Ammerland", "Altötting", "Nordfriesland", "Wartburgkreis"]'::jsonb, correct_answer = 4 WHERE id = 452;
UPDATE questions SET answers = '["3", "4", "5", "6"]'::jsonb, correct_answer = 3 WHERE id = 453;
UPDATE questions SET answers = '["14", "18", "16", "20"]'::jsonb, correct_answer = 3 WHERE id = 454;
UPDATE questions SET answers = '["blau-weiß-rot", "weiß-rot", "grün-weiß-rot", "schwarz-gold"]'::jsonb, correct_answer = 2 WHERE id = 455;
UPDATE questions SET answers = '["bei den Kirchen", "bei der Verbraucherzentrale", "bei der Landeszentrale für politische Bildung", "beim Ordnungsamt der Gemeinde"]'::jsonb, correct_answer = 3 WHERE id = 456;
UPDATE questions SET answers = '["Eisenach.", "Erfurt.", "Gera.", "Jena."]'::jsonb, correct_answer = 2 WHERE id = 457;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 2 WHERE id = 458;
UPDATE questions SET answers = '["Erster Minister / Erste Ministerin", "Premierminister / Premierministerin", "Bürgermeister / Bürgermeisterin", "Ministerpräsident / Ministerpräsidentin"]'::jsonb, correct_answer = 4 WHERE id = 459;
UPDATE questions SET answers = '["Justizminister / Justizministerin", "Außenminister / Außenministerin", "Finanzminister / Finanzministerin", "Innenminister / Innenministerin"]'::jsonb, correct_answer = 2 WHERE id = 460;
