UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 1 WHERE id = 21;
UPDATE questions SET answers = '["Monarchie", "Diktatur", "Republik", "Fürstentum"]'::jsonb, correct_answer = 3 WHERE id = 22;
UPDATE questions SET answers = '["in kleinen Familienunternehmen beschäftigt.", "ehrenamtlich für ein Bundesland tätig.", "selbstständig mit einer eigenen Firma tätig.", "bei einer Firma oder Behörde beschäftigt."]'::jsonb, correct_answer = 4 WHERE id = 23;
UPDATE questions SET answers = '["14", "15", "16", "17"]'::jsonb, correct_answer = 3 WHERE id = 24;
UPDATE questions SET answers = '["Elsass-Lothringen", "Nordrhein-Westfalen", "Mecklenburg-Vorpommern", "Sachsen-Anhalt"]'::jsonb, correct_answer = 1 WHERE id = 25;
UPDATE questions SET answers = '["eine kommunistische Republik.", "ein demokratischer und sozialer Bundesstaat.", "eine kapitalistische und soziale Monarchie.", "ein sozialer und sozialistischer Bundesstaat."]'::jsonb, correct_answer = 2 WHERE id = 26;
UPDATE questions SET answers = '["ein sozialistischer Staat.", "ein Bundesstaat.", "eine Diktatur.", "eine Monarchie."]'::jsonb, correct_answer = 2 WHERE id = 27;
UPDATE questions SET answers = '["das Militär", "die Wirtschaft", "das wahlberechtigte Volk", "die Verwaltung"]'::jsonb, correct_answer = 3 WHERE id = 28;
UPDATE questions SET answers = '["Löwe", "Adler", "Bär", "Pferd"]'::jsonb, correct_answer = 2 WHERE id = 29;
UPDATE questions SET answers = '["regelmäßige Wahlen", "Pressezensur", "Meinungsfreiheit", "verschiedene Parteien"]'::jsonb, correct_answer = 2 WHERE id = 30;
UPDATE questions SET answers = '["Einheit.", "Koalition.", "Ministerium.", "Fraktion."]'::jsonb, correct_answer = 2 WHERE id = 31;
UPDATE questions SET answers = '["Gesetzgebung", "Regierung", "Presse", "Rechtsprechung"]'::jsonb, correct_answer = 3 WHERE id = 32;
UPDATE questions SET answers = '["sind Staat und Religionsgemeinschaften voneinander getrennt.", "bilden die Religionsgemeinschaften den Staat.", "ist der Staat abhängig von den Religionsgemeinschaften.", "bilden Staat und Religionsgemeinschaften eine Einheit."]'::jsonb, correct_answer = 1 WHERE id = 33;
UPDATE questions SET answers = '["eine Demokratie", "ein Rechtsstaat", "eine Monarchie", "ein Sozialstaat"]'::jsonb, correct_answer = 3 WHERE id = 34;
UPDATE questions SET answers = '["Kirchensteuer", "Sozialabgaben", "Spendengeldern", "Vereinsbeiträgen"]'::jsonb, correct_answer = 2 WHERE id = 35;
UPDATE questions SET answers = '["die Krankenversicherung", "die Autoversicherung", "die Gebäudeversicherung", "die Haftpflichtversicherung"]'::jsonb, correct_answer = 1 WHERE id = 36;
UPDATE questions SET answers = '["Erste Ministerin/Erster Minister", "Premierministerin/Premierminister", "Senatorin/Senator", "Ministerpräsidentin/Ministerpräsident"]'::jsonb, correct_answer = 4 WHERE id = 37;
UPDATE questions SET answers = '["Staatenverbund", "Bundesstaat", "Staatenbund", "Zentralstaat"]'::jsonb, correct_answer = 2 WHERE id = 38;
UPDATE questions SET answers = '["einen eigenen Außenminister / eine eigene Außenministerin", "eine eigene Währung", "eine eigene Armee", "eine eigene Regierung"]'::jsonb, correct_answer = 4 WHERE id = 39;
UPDATE questions SET answers = '["Völker, hört die Signale …", "Einigkeit und Recht und Freiheit …", "Freude schöner Götterfunken …", "Deutschland einig Vaterland …"]'::jsonb, correct_answer = 2 WHERE id = 40;
