UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 3 WHERE id = 381;
UPDATE questions SET answers = '["Ammerland", "Rhein-Sieg-Kreis", "Nordfriesland", "Vogtlandkreis"]'::jsonb, correct_answer = 1 WHERE id = 382;
UPDATE questions SET answers = '["3", "4", "5", "6"]'::jsonb, correct_answer = 3 WHERE id = 383;
UPDATE questions SET answers = '["14", "16", "17", "20"]'::jsonb, correct_answer = 2 WHERE id = 384;
UPDATE questions SET answers = '["rot-weiß", "schwarz-rot-gold", "schwarz-gelb", "blau-weiß-rot"]'::jsonb, correct_answer = 2 WHERE id = 385;
UPDATE questions SET answers = '["beim Koordinator für politische Bildung im Kultusministerium", "beim Ordnungsamt der Gemeinde", "bei der Verbraucherzentrale", "bei den Kirchen"]'::jsonb, correct_answer = 1 WHERE id = 386;
UPDATE questions SET answers = '["Hannover.", "Braunschweig.", "Wolfsburg.", "Osnabrück."]'::jsonb, correct_answer = 1 WHERE id = 387;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 1 WHERE id = 388;
UPDATE questions SET answers = '["Erster Minister / Erste Ministerin", "Premierminister / Premierministerin", "Bürgermeister / Bürgermeisterin", "Ministerpräsident / Ministerpräsidentin"]'::jsonb, correct_answer = 4 WHERE id = 389;
UPDATE questions SET answers = '["Justizminister / Justizministerin", "Außenminister / Außenministerin", "Finanzminister / Finanzministerin", "Innenminister / Innenministerin"]'::jsonb, correct_answer = 2 WHERE id = 390;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 2 WHERE id = 391;
UPDATE questions SET answers = '["Ammerland", "Rhein-Sieg-Kreis", "Nordfriesland", "Vogtlandkreis"]'::jsonb, correct_answer = 2 WHERE id = 392;
UPDATE questions SET answers = '["3", "4", "5", "6"]'::jsonb, correct_answer = 3 WHERE id = 393;
UPDATE questions SET answers = '["14", "16", "18", "20"]'::jsonb, correct_answer = 2 WHERE id = 394;
UPDATE questions SET answers = '["rot-weiß", "grün-weiß-rot", "schwarz-gold", "blau-weiß-rot"]'::jsonb, correct_answer = 2 WHERE id = 395;
UPDATE questions SET answers = '["bei den Kirchen", "beim Ordnungsamt der Gemeinde", "bei der Verbraucherzentrale", "bei der Landeszentrale für politische Bildung"]'::jsonb, correct_answer = 4 WHERE id = 396;
UPDATE questions SET answers = '["Köln.", "Bonn.", "Düsseldorf.", "Dortmund."]'::jsonb, correct_answer = 3 WHERE id = 397;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 3 WHERE id = 398;
UPDATE questions SET answers = '["Erster Minister / Erste Ministerin", "Premierminister / Premierministerin", "Bürgermeister / Bürgermeisterin", "Ministerpräsident / Ministerpräsidentin"]'::jsonb, correct_answer = 4 WHERE id = 399;
UPDATE questions SET answers = '["Justizminister / Justizministerin", "Außenminister / Außenministerin", "Finanzminister / Finanzministerin", "Innenminister / Innenministerin"]'::jsonb, correct_answer = 2 WHERE id = 400;
