UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 1 WHERE id = 301;
UPDATE questions SET answers = '["Neckar-Odenwald-Kreis", "Nordfriesland", "Nordfriesland", "Altötting"]'::jsonb, correct_answer = 1 WHERE id = 302;
UPDATE questions SET answers = '["3", "4", "5", "6"]'::jsonb, correct_answer = 3 WHERE id = 303;
UPDATE questions SET answers = '["14", "16", "18", "20"]'::jsonb, correct_answer = 2 WHERE id = 304;
UPDATE questions SET answers = '["blau-weiß-rot", "schwarz-gold", "weiß-blau", "grün-weiß-rot"]'::jsonb, correct_answer = 2 WHERE id = 305;
UPDATE questions SET answers = '["beim Ordnungsamt der Gemeinde", "bei der Verbraucherzentrale", "bei der Landeszentrale für politische Bildung", "bei den Kirchen"]'::jsonb, correct_answer = 3 WHERE id = 306;
UPDATE questions SET answers = '["Heidelberg.", "Stuttgart.", "Karlsruhe.", "Mannheim."]'::jsonb, correct_answer = 2 WHERE id = 307;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 2 WHERE id = 308;
UPDATE questions SET answers = '["Erster Minister / Erste Ministerin", "Premierminister / Premierministerin", "Bürgermeister / Bürgermeisterin", "Ministerpräsident / Ministerpräsidentin"]'::jsonb, correct_answer = 4 WHERE id = 309;
UPDATE questions SET answers = '["Finanzminister / Finanzministerin", "Justizminister / Justizministerin", "Innenminister / Innenministerin", "Außenminister / Außenministerin"]'::jsonb, correct_answer = 4 WHERE id = 310;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 2 WHERE id = 311;
UPDATE questions SET answers = '["Prignitz", "Rhein-Sieg-Kreis", "Nordfriesland", "Altötting"]'::jsonb, correct_answer = 4 WHERE id = 312;
UPDATE questions SET answers = '["3", "4", "5", "6"]'::jsonb, correct_answer = 3 WHERE id = 313;
UPDATE questions SET answers = '["14", "16", "18", "20"]'::jsonb, correct_answer = 3 WHERE id = 314;
UPDATE questions SET answers = '["blau-weiß-rot", "weiß-blau", "grün-weiß-rot", "schwarz-gelb"]'::jsonb, correct_answer = 2 WHERE id = 315;
UPDATE questions SET answers = '["beim Ordnungsamt der Gemeinde", "bei der Landeszentrale für politische Bildung", "bei der Verbraucherzentrale", "bei den Kirchen"]'::jsonb, correct_answer = 2 WHERE id = 316;
UPDATE questions SET answers = '["Ingolstadt.", "Regensburg.", "Nürnberg.", "München."]'::jsonb, correct_answer = 4 WHERE id = 317;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 4 WHERE id = 318;
UPDATE questions SET answers = '["Erster Minister / Erste Ministerin", "Premierminister / Premierministerin", "Bürgermeister / Bürgermeisterin", "Ministerpräsident / Ministerpräsidentin"]'::jsonb, correct_answer = 4 WHERE id = 319;
UPDATE questions SET answers = '["Justizminister / Justizministerin", "Außenminister / Außenministerin", "Finanzminister / Finanzministerin", "Innenminister / Innenministerin"]'::jsonb, correct_answer = 2 WHERE id = 320;
