UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 4 WHERE id = 421;
UPDATE questions SET answers = '["Vogtlandkreis", "Altötting", "Uckermark", "Nordfriesland"]'::jsonb, correct_answer = 1 WHERE id = 422;
UPDATE questions SET answers = '["3", "4", "5", "6"]'::jsonb, correct_answer = 3 WHERE id = 423;
UPDATE questions SET answers = '["14", "16", "18", "20"]'::jsonb, correct_answer = 3 WHERE id = 424;
UPDATE questions SET answers = '["blau-weiß-rot", "weiß-grün", "grün-weiß-rot", "schwarz-gelb"]'::jsonb, correct_answer = 2 WHERE id = 425;
UPDATE questions SET answers = '["bei der Landeszentrale für politische Bildung", "beim Ordnungsamt der Gemeinde", "bei den Kirchen", "bei der Verbraucherzentrale"]'::jsonb, correct_answer = 1 WHERE id = 426;
UPDATE questions SET answers = '["Leipzig.", "Dresden.", "Chemnitz.", "Zwickau."]'::jsonb, correct_answer = 2 WHERE id = 427;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 4 WHERE id = 428;
UPDATE questions SET answers = '["Erster Minister / Erste Ministerin", "Premierminister / Premierministerin", "Bürgermeister / Bürgermeisterin", "Ministerpräsident / Ministerpräsidentin"]'::jsonb, correct_answer = 4 WHERE id = 429;
UPDATE questions SET answers = '["Justizminister / Justizministerin", "Außenminister / Außenministerin", "Finanzminister / Finanzministerin", "Innenminister / Innenministerin"]'::jsonb, correct_answer = 2 WHERE id = 430;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 4 WHERE id = 431;
UPDATE questions SET answers = '["Ammerland", "Altötting", "Uckermark", "Börde"]'::jsonb, correct_answer = 4 WHERE id = 432;
UPDATE questions SET answers = '["3", "4", "5", "6"]'::jsonb, correct_answer = 3 WHERE id = 433;
UPDATE questions SET answers = '["14", "16", "18", "20"]'::jsonb, correct_answer = 2 WHERE id = 434;
UPDATE questions SET answers = '["blau-weiß-rot", "gelb-schwarz", "grün-weiß-rot", "weiß-rot"]'::jsonb, correct_answer = 2 WHERE id = 435;
UPDATE questions SET answers = '["bei den Kirchen", "bei der Landeszentrale für politische Bildung", "beim Ordnungsamt der Gemeinde", "bei der Verbraucherzentrale"]'::jsonb, correct_answer = 2 WHERE id = 436;
UPDATE questions SET answers = '["Halle.", "Dessau.", "Magdeburg.", "Wittenberg."]'::jsonb, correct_answer = 3 WHERE id = 437;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 3 WHERE id = 438;
UPDATE questions SET answers = '["Erster Minister / Erste Ministerin", "Premierminister / Premierministerin", "Bürgermeister / Bürgermeisterin", "Ministerpräsident / Ministerpräsidentin"]'::jsonb, correct_answer = 4 WHERE id = 439;
UPDATE questions SET answers = '["Justizminister / Justizministerin", "Außenminister / Außenministerin", "Finanzminister / Finanzministerin", "Innenminister / Innenministerin"]'::jsonb, correct_answer = 2 WHERE id = 440;
