UPDATE questions SET answers = '["Er hat sich den ehemaligen Alliierten unterworfen.", "Er bat Polen und die polnischen Juden um Vergebung.", "Er zeigte seine Demut vor dem Warschauer Pakt.", "Er sprach ein Gebet am Grab des Unbekannten Soldaten."]'::jsonb, correct_answer = 2 WHERE id = 181;
UPDATE questions SET answers = '["KPD und SPD", "SPD und CDU", "CDU und FDP", "KPD und CSU"]'::jsonb, correct_answer = 1 WHERE id = 182;
UPDATE questions SET answers = '["40er Jahre", "50er Jahre", "70er Jahre", "80er Jahre"]'::jsonb, correct_answer = 2 WHERE id = 183;
UPDATE questions SET answers = '["Damit wird die Zeit nach der Wende im Jahr 1989 bezeichnet.", "Damit wurde der Beginn des Zweiten Weltkrieges bezeichnet.", "Darunter verstand man das Ende des Zweiten Weltkrieges und den Beginn des Wiederaufbaus.", "Damit ist die Stunde gemeint, in der die Uhr von der Sommerzeit auf die Winterzeit umgestellt wird."]'::jsonb, correct_answer = 3 WHERE id = 184;
UPDATE questions SET answers = '["des Warschauer Pakts gegen den Westen.", "Norddeutschlands gegen Süddeutschland.", "Nazi-Deutschlands gegen die Alliierten.", "Europas gegen die USA."]'::jsonb, correct_answer = 1 WHERE id = 185;
UPDATE questions SET answers = '["45413", "45460", "45493", "45605"]'::jsonb, correct_answer = 2 WHERE id = 186;
UPDATE questions SET answers = '["Preußen", "Bundesrepublik Deutschland", "DDR", "„Drittes Reich“"]'::jsonb, correct_answer = 3 WHERE id = 187;
UPDATE questions SET answers = '["1953", "1956", "1959", "1961"]'::jsonb, correct_answer = 4 WHERE id = 188;
UPDATE questions SET answers = '["1919", "1933", "1961", "1990"]'::jsonb, correct_answer = 3 WHERE id = 189;
UPDATE questions SET answers = '["Dritter Deutscher Rundfunk", "Die Deutsche Republik", "Dritte Deutsche Republik", "Deutsche Demokratische Republik"]'::jsonb, correct_answer = 4 WHERE id = 190;
UPDATE questions SET answers = '["1987", "1989", "1992", "1995"]'::jsonb, correct_answer = 2 WHERE id = 191;
UPDATE questions SET answers = '["Brandenburg", "Bayern", "Saarland", "Hessen"]'::jsonb, correct_answer = 1 WHERE id = 192;
UPDATE questions SET answers = '["ohne Bürgermeister.", "ein eigener Staat.", "durch eine Mauer geteilt.", "nur mit dem Flugzeug erreichbar."]'::jsonb, correct_answer = 3 WHERE id = 193;
UPDATE questions SET answers = '["Einheit.", "Nation.", "Bundesländer.", "Städte."]'::jsonb, correct_answer = 1 WHERE id = 194;
UPDATE questions SET answers = '["Hessen", "Sachsen-Anhalt", "Nordrhein-Westfalen", "Saarland"]'::jsonb, correct_answer = 2 WHERE id = 195;
UPDATE questions SET answers = '["von einer Diktatur zur Demokratie.", "von einer liberalen Marktwirtschaft zum Sozialismus.", "von einer Monarchie zur Sozialdemokratie.", "von einem religiösen Staat zu einem kommunistischen Staat."]'::jsonb, correct_answer = 1 WHERE id = 196;
UPDATE questions SET answers = '["Thüringen", "Hessen", "Bayern", "Bremen"]'::jsonb, correct_answer = 1 WHERE id = 197;
UPDATE questions SET answers = '["Bayern", "Niedersachsen", "Sachsen", "Baden-Württemberg"]'::jsonb, correct_answer = 3 WHERE id = 198;
UPDATE questions SET answers = '["das Parlament.", "das Ministerium für Staatssicherheit.", "eine regierende Partei.", "das Ministerium für Volksbildung."]'::jsonb, correct_answer = 2 WHERE id = 199;
UPDATE questions SET answers = '["Hessen", "Schleswig-Holstein", "Mecklenburg-Vorpommern", "Saarland"]'::jsonb, correct_answer = 3 WHERE id = 200;
