UPDATE questions SET answers = '["ein Rechtsanwalt / eine Rechtsanwältin", "ein Richter / eine Richterin", "ein Schöffe / eine Schöffin", "ein Staatsanwalt / eine Staatsanwältin"]'::jsonb, correct_answer = 1 WHERE id = 141;
UPDATE questions SET answers = '["vertritt Bürger und Bürgerinnen vor einem Gericht.", "arbeitet an einem Gericht und spricht Urteile.", "ändert Gesetze.", "betreut Jugendliche vor Gericht."]'::jsonb, correct_answer = 2 WHERE id = 142;
UPDATE questions SET answers = '["Judikative.", "Exekutive.", "Operative.", "Legislative."]'::jsonb, correct_answer = 1 WHERE id = 143;
UPDATE questions SET answers = '["vollziehenden Gewalt.", "rechtsprechenden Gewalt.", "planenden Gewalt.", "gesetzgebenden Gewalt."]'::jsonb, correct_answer = 2 WHERE id = 144;
UPDATE questions SET answers = '["Judikative.", "Exekutive.", "Presse.", "Legislative."]'::jsonb, correct_answer = 1 WHERE id = 145;
UPDATE questions SET answers = '["Programm", "Prozedur", "Protokoll", "Prozess"]'::jsonb, correct_answer = 4 WHERE id = 146;
UPDATE questions SET answers = '["Deutschland regieren", "Recht sprechen", "Pläne erstellen", "Gesetze erlassen"]'::jsonb, correct_answer = 2 WHERE id = 147;
UPDATE questions SET answers = '["das Land zu verteidigen", "die Bürgerinnen und Bürger abzuhören", "die Gesetze zu beschließen", "die Einhaltung von Gesetzen zu überwachen"]'::jsonb, correct_answer = 4 WHERE id = 148;
UPDATE questions SET answers = '["alle in Deutschland geborenen Einwohner / Einwohnerinnen über 18 Jahre", "alle deutschen Staatsangehörigen älter als 24 und jünger als 70 Jahre", "alle Personen, die seit mindestens 5 Jahren in Deutschland leben", "nur Personen mit einem abgeschlossenen Jurastudium"]'::jsonb, correct_answer = 2 WHERE id = 149;
UPDATE questions SET answers = '["der Stellvertreter / die Stellvertreterin des Stadtoberhaupts.", "ein ehrenamtlicher Richter / eine ehrenamtliche Richterin.", "ein Mitglied eines Gemeinderats.", "eine Person, die Jura studiert hat."]'::jsonb, correct_answer = 2 WHERE id = 150;
UPDATE questions SET answers = '["Großbritannien", "die Bundesrepublik Deutschland", "die DDR", "die USA"]'::jsonb, correct_answer = 3 WHERE id = 151;
UPDATE questions SET answers = '["1918 bis 1923", "1932 bis 1950", "1933 bis 1945", "1945 bis 1989"]'::jsonb, correct_answer = 3 WHERE id = 152;
UPDATE questions SET answers = '["Tod Adolf Hitlers", "Beginn des Berliner Mauerbaus", "Wahl von Konrad Adenauer zum Bundeskanzler", "Ende des Zweiten Weltkriegs in Europa"]'::jsonb, correct_answer = 4 WHERE id = 153;
UPDATE questions SET answers = '["1933", "1945", "1949", "1961"]'::jsonb, correct_answer = 2 WHERE id = 154;
UPDATE questions SET answers = '["1888 bis 1918", "1921 bis 1934", "1933 bis 1945", "1949 bis 1963"]'::jsonb, correct_answer = 3 WHERE id = 155;
UPDATE questions SET answers = '["1923", "1927", "1933", "1936"]'::jsonb, correct_answer = 3 WHERE id = 156;
UPDATE questions SET answers = '["eine Diktatur.", "einen demokratischen Staat.", "eine Monarchie.", "ein Fürstentum."]'::jsonb, correct_answer = 1 WHERE id = 157;
UPDATE questions SET answers = '["Diktatur", "Demokratie.", "Monarchie.", "Räterepublik."]'::jsonb, correct_answer = 1 WHERE id = 158;
UPDATE questions SET answers = '["freie Wahlen", "Pressezensur", "willkürliche Verhaftungen", "Verfolgung der Juden"]'::jsonb, correct_answer = 1 WHERE id = 159;
UPDATE questions SET answers = '["der Erste Weltkrieg", "der Zweite Weltkrieg", "der Vietnamkrieg", "der Golfkrieg"]'::jsonb, correct_answer = 2 WHERE id = 160;
