UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 3 WHERE id = 341;
UPDATE questions SET answers = '["Altona", "Hemelingen", "Pankow", "Babelsberg"]'::jsonb, correct_answer = 2 WHERE id = 342;
UPDATE questions SET answers = '["3", "4", "5", "6"]'::jsonb, correct_answer = 2 WHERE id = 343;
UPDATE questions SET answers = '["14", "16", "18", "20"]'::jsonb, correct_answer = 2 WHERE id = 344;
UPDATE questions SET answers = '["blau-weiß-rot", "rot-weiß", "grün-weiß-rot", "schwarz-gold"]'::jsonb, correct_answer = 2 WHERE id = 345;
UPDATE questions SET answers = '["beim Ordnungsamt der Gemeinde", "bei der Landeszentrale für politische Bildung", "bei den Kirchen", "bei der Verbraucherzentrale"]'::jsonb, correct_answer = 2 WHERE id = 346;
UPDATE questions SET answers = '["Bremen", "München", "Frankfurt", "Erfurt"]'::jsonb, correct_answer = 1 WHERE id = 347;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 1 WHERE id = 348;
UPDATE questions SET answers = '["Ministerpräsident / Ministerpräsidentin", "Erster Bürgermeister / Erste Bürgermeisterin", "Präsident / Präsidentin des Senats", "Regierender Bürgermeister / Regierende Bürgermeisterin"]'::jsonb, correct_answer = 3 WHERE id = 349;
UPDATE questions SET answers = '["Senator / Senatorin für Außenbeziehungen", "Finanzsenator / Finanzsenatorin", "Justizsenator / Justizsenatorin", "Innensenator / Innensenatorin"]'::jsonb, correct_answer = 1 WHERE id = 350;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 2 WHERE id = 351;
UPDATE questions SET answers = '["Altona", "Hemelingen", "Pankow", "Demmin"]'::jsonb, correct_answer = 1 WHERE id = 352;
UPDATE questions SET answers = '["3", "4", "5", "6"]'::jsonb, correct_answer = 3 WHERE id = 353;
UPDATE questions SET answers = '["14", "16", "18", "20"]'::jsonb, correct_answer = 2 WHERE id = 354;
UPDATE questions SET answers = '["blau-weiß-rot", "weiß-rot", "grün-weiß-rot", "schwarz-gelb"]'::jsonb, correct_answer = 2 WHERE id = 355;
UPDATE questions SET answers = '["beim Ordnungsamt der Gemeinde", "bei der Verbraucherzentrale", "bei den Kirchen", "bei der Landeszentrale für politische Bildung"]'::jsonb, correct_answer = 4 WHERE id = 356;
UPDATE questions SET answers = '["Hamburg", "Sachsen", "Bayern", "Thüringen"]'::jsonb, correct_answer = 1 WHERE id = 357;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 3 WHERE id = 358;
UPDATE questions SET answers = '["Ministerpräsident / Ministerpräsidentin", "Erster Bürgermeister / Erste Bürgermeisterin", "Regierender Senator / Regierende Senatorin", "Oberbürgermeister / Oberbürgermeisterin"]'::jsonb, correct_answer = 2 WHERE id = 359;
UPDATE questions SET answers = '["Justizsenator / Justizsenatorin", "Senator / Senatorin für Außenbeziehungen", "Finanzsenator / Finanzsenatorin", "Innensenator / Innensenatorin"]'::jsonb, correct_answer = 2 WHERE id = 360;
