UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 1 WHERE id = 361;
UPDATE questions SET answers = '["Ammerland", "Altötting", "Prignitz", "Main-Taunus-Kreis"]'::jsonb, correct_answer = 4 WHERE id = 362;
UPDATE questions SET answers = '["3", "4", "5", "6"]'::jsonb, correct_answer = 3 WHERE id = 363;
UPDATE questions SET answers = '["14", "16", "18", "20"]'::jsonb, correct_answer = 3 WHERE id = 364;
UPDATE questions SET answers = '["blau-weiß-rot", "rot-weiß", "schwarz-gold", "grün-weiß-rot"]'::jsonb, correct_answer = 2 WHERE id = 365;
UPDATE questions SET answers = '["bei der Landeszentrale für politische Bildung", "bei der Verbraucherzentrale", "beim Ordnungsamt der Gemeinde", "bei den Kirchen"]'::jsonb, correct_answer = 1 WHERE id = 366;
UPDATE questions SET answers = '["Kassel.", "Darmstadt.", "Frankfurt.", "Wiesbaden."]'::jsonb, correct_answer = 4 WHERE id = 367;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 3 WHERE id = 368;
UPDATE questions SET answers = '["Erster Minister / Erste Ministerin", "Premierminister / Premierministerin", "Bürgermeister / Bürgermeisterin", "Ministerpräsident / Ministerpräsidentin"]'::jsonb, correct_answer = 4 WHERE id = 369;
UPDATE questions SET answers = '["Justizminister / Justizministerin", "Außenminister / Außenministerin", "Finanzminister / Finanzministerin", "Innenminister / Innenministerin"]'::jsonb, correct_answer = 2 WHERE id = 370;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 3 WHERE id = 371;
UPDATE questions SET answers = '["Prignitz", "Mecklenburgische Seenplatte", "Vogtlandkreis", "Rhein-Sieg-Kreis"]'::jsonb, correct_answer = 2 WHERE id = 372;
UPDATE questions SET answers = '["3", "4", "5", "6"]'::jsonb, correct_answer = 3 WHERE id = 373;
UPDATE questions SET answers = '["14", "16", "18", "20"]'::jsonb, correct_answer = 2 WHERE id = 374;
UPDATE questions SET answers = '["schwarz-rot-gold", "blau-weiß-gelb-rot", "grün-weiß-rot", "schwarz-gelb"]'::jsonb, correct_answer = 2 WHERE id = 375;
UPDATE questions SET answers = '["bei der Landeszentrale für politische Bildung", "bei den Kirchen", "beim Ordnungsamt der Gemeinde", "bei der Verbraucherzentrale"]'::jsonb, correct_answer = 1 WHERE id = 376;
UPDATE questions SET answers = '["Greifswald.", "Schwerin.", "Rostock.", "Wismar."]'::jsonb, correct_answer = 2 WHERE id = 377;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 3 WHERE id = 378;
UPDATE questions SET answers = '["Erster Minister / Erste Ministerin", "Premierminister / Premierministerin", "Bürgermeister / Bürgermeisterin", "Ministerpräsident / Ministerpräsidentin"]'::jsonb, correct_answer = 4 WHERE id = 379;
UPDATE questions SET answers = '["Justizminister / Justizministerin", "Außenminister / Außenministerin", "Finanzminister / Finanzministerin", "Innenminister / Innenministerin"]'::jsonb, correct_answer = 2 WHERE id = 380;
