UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 4 WHERE id = 321;
UPDATE questions SET answers = '["Altona", "Prignitz", "Pankow", "Demmin"]'::jsonb, correct_answer = 3 WHERE id = 322;
UPDATE questions SET answers = '["3", "4", "5", "6"]'::jsonb, correct_answer = 3 WHERE id = 323;
UPDATE questions SET answers = '["14", "16", "18", "20"]'::jsonb, correct_answer = 2 WHERE id = 324;
UPDATE questions SET answers = '["blau-weiß-rot", "weiß-rot", "grün-weiß-rot", "schwarz-gold"]'::jsonb, correct_answer = 2 WHERE id = 325;
UPDATE questions SET answers = '["beim Ordnungsamt der Gemeinde", "bei den Kirchen", "bei der Verbraucherzentrale", "bei der Landeszentrale für politische Bildung"]'::jsonb, correct_answer = 4 WHERE id = 326;
UPDATE questions SET answers = '["Berlin", "Saarland", "Brandenburg", "Hessen"]'::jsonb, correct_answer = 1 WHERE id = 327;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 4 WHERE id = 328;
UPDATE questions SET answers = '["Ministerpräsident / Ministerpräsidentin", "Oberbürgermeister / Oberbürgermeisterin", "Präsident / Präsidentin des Senats", "Regierender Bürgermeister / Regierende Bürgermeisterin"]'::jsonb, correct_answer = 4 WHERE id = 329;
UPDATE questions SET answers = '["Finanzsenator / Finanzsenatorin", "Innensenator / Innensenatorin", "Senator / Senatorin für Außenbeziehungen", "Justizsenator / Justizsenatorin"]'::jsonb, correct_answer = 3 WHERE id = 330;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 1 WHERE id = 331;
UPDATE questions SET answers = '["Prignitz", "Rhein-Sieg-Kreis", "Vogtlandkreis", "Amberg-Sulzbach"]'::jsonb, correct_answer = 1 WHERE id = 332;
UPDATE questions SET answers = '["3", "4", "5", "6"]'::jsonb, correct_answer = 3 WHERE id = 333;
UPDATE questions SET answers = '["14", "18", "16", "20"]'::jsonb, correct_answer = 3 WHERE id = 334;
UPDATE questions SET answers = '["blau-weiß-rot", "rot-weiß", "grün-weiß-rot", "schwarz-gelb"]'::jsonb, correct_answer = 2 WHERE id = 335;
UPDATE questions SET answers = '["bei den Kirchen", "beim Ordnungsamt der Gemeinde", "bei der Landeszentrale für politische Bildung", "bei der Verbraucherzentrale"]'::jsonb, correct_answer = 3 WHERE id = 336;
UPDATE questions SET answers = '["Potsdam.", "Cottbus.", "Brandenburg.", "Frankfurt/Oder."]'::jsonb, correct_answer = 1 WHERE id = 337;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 4 WHERE id = 338;
UPDATE questions SET answers = '["Erster Minister / Erste Ministerin", "Premierminister / Premierministerin", "Bürgermeister / Bürgermeisterin", "Ministerpräsident / Ministerpräsidentin"]'::jsonb, correct_answer = 4 WHERE id = 339;
UPDATE questions SET answers = '["Justizminister / Justizministerin", "Außenminister / Außenministerin", "Finanzminister / Finanzministerin", "Innenminister / Innenministerin"]'::jsonb, correct_answer = 2 WHERE id = 340;
