UPDATE questions SET answers = '["Niedersachsen, Nordrhein-Westfalen, Hessen, Schleswig-Holstein, Brandenburg", "Mecklenburg-Vorpommern, Brandenburg, Sachsen, Sachsen-Anhalt, Thüringen", "Bayern, Baden-Württemberg, Rheinland-Pfalz, Thüringen, Sachsen", "Sachsen, Thüringen, Hessen, Niedersachsen, Brandenburg"]'::jsonb, correct_answer = 2 WHERE id = 201;
UPDATE questions SET answers = '["zu den Westmächten", "zum Warschauer Pakt", "zur NATO", "zu den blockfreien Staaten"]'::jsonb, correct_answer = 2 WHERE id = 202;
UPDATE questions SET answers = '["Marktwirtschaft", "Planwirtschaft", "Angebot und Nachfrage", "Kapitalismus"]'::jsonb, correct_answer = 2 WHERE id = 203;
UPDATE questions SET answers = '["Die Bundesrepublik Deutschland hat die DDR besetzt.", "Die heutigen fünf östlichen Bundesländer sind der Bundesrepublik Deutschland beigetreten.", "Die westlichen Bundesländer sind der DDR beigetreten.", "Die DDR hat die Bundesrepublik Deutschland besetzt."]'::jsonb, correct_answer = 2 WHERE id = 204;
UPDATE questions SET answers = '["zur Europäischen Union.", "zum Warschauer Pakt.", "zur OPEC.", "zur Europäischen Verteidigungsgemeinschaft."]'::jsonb, correct_answer = 1 WHERE id = 205;
UPDATE questions SET answers = '["In der Bundesrepublik waren Demonstrationen nur am Montag erlaubt.", "Montags waren Demonstrationen gegen das DDR-Regime.", "Am ersten Montag im Monat trafen sich in der Bundesrepublik Deutschland Demonstranten.", "Montags demonstrierte man in der DDR gegen den Westen."]'::jsonb, correct_answer = 2 WHERE id = 206;
UPDATE questions SET answers = '["in der NATO", "im Rheinbund", "im Warschauer Pakt", "im Europabündnis"]'::jsonb, correct_answer = 3 WHERE id = 207;
UPDATE questions SET answers = '["der Geheimdienst im „Dritten Reich“", "eine berühmte deutsche Gedenkstätte", "der Geheimdienst der DDR", "ein deutscher Sportverein während des Zweiten Weltkrieges"]'::jsonb, correct_answer = 3 WHERE id = 208;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 1 WHERE id = 209;
UPDATE questions SET answers = '["der feierliche Beitritt zum Warschauer Pakt", "landesweite Streiks und ein Volksaufstand", "der 1. SED-Parteitag", "der erste Besuch Fidel Castros"]'::jsonb, correct_answer = 2 WHERE id = 210;
UPDATE questions SET answers = '["Helmut Kohl", "Willy Brandt", "Michail Gorbatschow", "Ludwig Erhard"]'::jsonb, correct_answer = 2 WHERE id = 211;
UPDATE questions SET answers = '["Bundesstaat Deutschland", "Bundesländer Deutschland", "Bundesrepublik Deutschland", "Bundesbezirk Deutschland"]'::jsonb, correct_answer = 3 WHERE id = 212;
UPDATE questions SET answers = '["70 Millionen", "78 Millionen", "80 Millionen", "90 Millionen"]'::jsonb, correct_answer = 3 WHERE id = 213;
UPDATE questions SET answers = '["schwarz-rot-gold", "rot-weiß-schwarz", "schwarz-rot-grün", "schwarz-gelb-rot"]'::jsonb, correct_answer = 1 WHERE id = 214;
UPDATE questions SET answers = '["Gerhard Schröder", "Helmut Kohl", "Konrad Adenauer", "Helmut Schmidt"]'::jsonb, correct_answer = 2 WHERE id = 215;
UPDATE questions SET answers = '["die Fahne der Stadt Berlin.", "der Bundesadler.", "der Reichsadler.", "die Reichskrone."]'::jsonb, correct_answer = 2 WHERE id = 216;
UPDATE questions SET answers = '["1919 bis 1927", "1933 bis 1945", "1949 bis 1990", "1945 bis 1961"]'::jsonb, correct_answer = 3 WHERE id = 217;
UPDATE questions SET answers = '["4", "5", "6", "7"]'::jsonb, correct_answer = 2 WHERE id = 218;
UPDATE questions SET answers = '["1933.", "1949.", "1971.", "1990."]'::jsonb, correct_answer = 4 WHERE id = 219;
UPDATE questions SET answers = '["an das Ende des Zweiten Weltkrieges", "an die Verabschiedung des Grundgesetzes", "an die Wiedervereinigung Deutschlands", "an die Opfer des Nationalsozialismus"]'::jsonb, correct_answer = 4 WHERE id = 220;
