UPDATE questions SET answers = '["Deutsche können in viele Länder Europas ohne Passkontrolle reisen. ", "Alle Menschen können ohne Personenkontrolle in Deutschland einreisen.", "Deutsche können ohne Passkontrolle in jedes Land reisen.", "Deutsche können in jedem Land mit dem Euro bezahlen."]'::jsonb, correct_answer = 1 WHERE id = 221;
UPDATE questions SET answers = '["Ungarn", "Portugal", "Spanien", "Schweiz"]'::jsonb, correct_answer = 4 WHERE id = 222;
UPDATE questions SET answers = '["Rumänien", "Bulgarien", "Polen", "Griechenland"]'::jsonb, correct_answer = 3 WHERE id = 223;
UPDATE questions SET answers = '["Europäische Unternehmen", "Europäische Union", "Einheitliche Union", "Euro Union"]'::jsonb, correct_answer = 2 WHERE id = 224;
UPDATE questions SET answers = '["Tschechien", "Norwegen", "Spanien", "Österreich"]'::jsonb, correct_answer = 4 WHERE id = 225;
UPDATE questions SET answers = '["2", "1", "4", "3"]'::jsonb, correct_answer = 1 WHERE id = 226;
UPDATE questions SET answers = '["Finnland", "Dänemark", "Norwegen", "Schweden"]'::jsonb, correct_answer = 2 WHERE id = 227;
UPDATE questions SET answers = '["NATO-Osterweiterung", "EU-Osterweiterung", "Europäische Gemeinschaft", "Europäische Gemeinschaft"]'::jsonb, correct_answer = 1 WHERE id = 228;
UPDATE questions SET answers = '["Spanien", "Bulgarien", "Norwegen", "Luxemburg"]'::jsonb, correct_answer = 4 WHERE id = 229;
UPDATE questions SET answers = '["5 Jahre.", "6 Jahre.", "7 Jahre.", "8 Jahre."]'::jsonb, correct_answer = 1 WHERE id = 230;
UPDATE questions SET answers = '["Damit sind amerikanische Einwanderer in Europa gemeint.", "Der Begriff meint den Einwanderungsstopp nach Europa.", "Damit sind europäische Auswanderer in den USA gemeint.", "Der Begriff meint den Zusammenschluss europäischer Staaten zur EU."]'::jsonb, correct_answer = 4 WHERE id = 231;
UPDATE questions SET answers = '["die Europäische Kommission", "die Länder, die in die EU eintreten dürfen", "die europäische Verfassung", "die Abgeordneten des Europäischen Parlaments"]'::jsonb, correct_answer = 4 WHERE id = 232;
UPDATE questions SET answers = '["Tschechien", "Bulgarien", "Griechenland", "Portugal"]'::jsonb, correct_answer = 1 WHERE id = 233;
UPDATE questions SET answers = '["London", "Paris", "Berlin", "Straßburg"]'::jsonb, correct_answer = 4 WHERE id = 234;
UPDATE questions SET answers = '["Freundschaft zwischen England und Deutschland", "Reisefreiheit in alle Länder der EU", "Frieden und Sicherheit in den Ländern der EU", "einheitliche Feiertage in den Ländern der EU"]'::jsonb, correct_answer = 3 WHERE id = 235;
UPDATE questions SET answers = '["21", "23", "25", "27"]'::jsonb, correct_answer = 4 WHERE id = 236;
UPDATE questions SET answers = '["Beitritt Deutschlands zur NATO", "Gründung der Europäischen Wirtschaftsgemeinschaft (EWG)", "Verpflichtung Deutschlands zu Reparationsleistungen", "Festlegung der Oder-Neiße-Linie als Ostgrenze"]'::jsonb, correct_answer = 2 WHERE id = 237;
UPDATE questions SET answers = '["Paris, London und Den Haag", "Straßburg, Luxemburg und Brüssel", "Rom, Bern und Wien", "Bonn, Zürich und Mailand"]'::jsonb, correct_answer = 2 WHERE id = 238;
UPDATE questions SET answers = '["durch die „Hamburger Verträge“", "durch die „Römischen Verträge“", "durch die „Pariser Verträge“", "durch die „Londoner Verträge“"]'::jsonb, correct_answer = 2 WHERE id = 239;
UPDATE questions SET answers = '["1995", "1998", "2002", "2005"]'::jsonb, correct_answer = 3 WHERE id = 240;
