UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 1 WHERE id = 401;
UPDATE questions SET answers = '["Westerwaldkreis", "Altötting", "Emsland", "Prignitz"]'::jsonb, correct_answer = 1 WHERE id = 402;
UPDATE questions SET answers = '["3", "4", "5", "6"]'::jsonb, correct_answer = 3 WHERE id = 403;
UPDATE questions SET answers = '["14", "16", "18", "20"]'::jsonb, correct_answer = 3 WHERE id = 404;
UPDATE questions SET answers = '["weiß-rot", "schwarz-rot-gold", "schwarz-gelb", "grün-weiß-rot"]'::jsonb, correct_answer = 2 WHERE id = 405;
UPDATE questions SET answers = '["bei den Kirchen", "bei der Verbraucherzentrale", "beim Ordnungsamt der Gemeinde", "bei der Landeszentrale für politische Bildung"]'::jsonb, correct_answer = 4 WHERE id = 406;
UPDATE questions SET answers = '["Mainz.", "Kaiserslautern.", "Ludwigshafen.", "Koblenz."]'::jsonb, correct_answer = 1 WHERE id = 407;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 1 WHERE id = 408;
UPDATE questions SET answers = '["Erster Minister / Erste Ministerin", "Premierminister / Premierministerin", "Bürgermeister / Bürgermeisterin", "Ministerpräsident / Ministerpräsidentin"]'::jsonb, correct_answer = 4 WHERE id = 409;
UPDATE questions SET answers = '["Justizminister / Justizministerin", "Außenminister / Außenministerin", "Finanzminister / Finanzministerin", "Innenminister / Innenministerin"]'::jsonb, correct_answer = 2 WHERE id = 410;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 4 WHERE id = 411;
UPDATE questions SET answers = '["Demmin", "Altötting", "Neunkirchen", "Rhein-Sieg-Kreis"]'::jsonb, correct_answer = 3 WHERE id = 412;
UPDATE questions SET answers = '["3", "4", "5", "6"]'::jsonb, correct_answer = 3 WHERE id = 413;
UPDATE questions SET answers = '["14", "16", "18", "20"]'::jsonb, correct_answer = 3 WHERE id = 414;
UPDATE questions SET answers = '["weiß-blau", "schwarz-rot-gold", "schwarz-gelb", "grün-weiß-rot"]'::jsonb, correct_answer = 2 WHERE id = 415;
UPDATE questions SET answers = '["bei den Kirchen", "bei der Landeszentrale für politische Bildung", "bei der Verbraucherzentrale", "beim Ordnungsamt der Gemeinde"]'::jsonb, correct_answer = 2 WHERE id = 416;
UPDATE questions SET answers = '["Neunkirchen.", "Homburg.", "Saarbrücken.", "Völklingen."]'::jsonb, correct_answer = 3 WHERE id = 417;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 2 WHERE id = 418;
UPDATE questions SET answers = '["Erster Minister / Erste Ministerin", "Premierminister / Premierministerin", "Bürgermeister / Bürgermeisterin", "Ministerpräsident / Ministerpräsidentin"]'::jsonb, correct_answer = 4 WHERE id = 419;
UPDATE questions SET answers = '["Justizminister / Justizministerin", "Außenminister / Außenministerin", "Finanzminister / Finanzministerin", "Innenminister / Innenministerin"]'::jsonb, correct_answer = 2 WHERE id = 420;
