UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 1 WHERE id = 21;
UPDATE questions SET answers = '["Monarchie", "Diktatur", "Republik", "Fürstentum"]'::jsonb, correct_answer = 3 WHERE id = 22;
UPDATE questions SET answers = '["in kleinen Familienunternehmen beschäftigt.", "ehrenamtlich für ein Bundesland tätig.", "selbstständig mit einer eigenen Firma tätig.", "bei einer Firma oder Behörde beschäftigt."]'::jsonb, correct_answer = 4 WHERE id = 23;
UPDATE questions SET answers = '["14", "15", "16", "17"]'::jsonb, correct_answer = 3 WHERE id = 24;
UPDATE questions SET answers = '["Elsass-Lothringen", "Nordrhein-Westfalen", "Mecklenburg-Vorpommern", "Sachsen-Anhalt"]'::jsonb, correct_answer = 1 WHERE id = 25;
UPDATE questions SET answers = '["eine kommunistische Republik.", "ein demokratischer und sozialer Bundesstaat.", "eine kapitalistische und soziale Monarchie.", "ein sozialer und sozialistischer Bundesstaat."]'::jsonb, correct_answer = 2 WHERE id = 26;
UPDATE questions SET answers = '["ein sozialistischer Staat.", "ein Bundesstaat.", "eine Diktatur.", "eine Monarchie."]'::jsonb, correct_answer = 2 WHERE id = 27;
UPDATE questions SET answers = '["das Militär", "die Wirtschaft", "das wahlberechtigte Volk", "die Verwaltung"]'::jsonb, correct_answer = 3 WHERE id = 28;
UPDATE questions SET answers = '["Löwe", "Adler", "Bär", "Pferd"]'::jsonb, correct_answer = 2 WHERE id = 29;
UPDATE questions SET answers = '["regelmäßige Wahlen", "Pressezensur", "Meinungsfreiheit", "verschiedene Parteien"]'::jsonb, correct_answer = 2 WHERE id = 30;
UPDATE questions SET answers = '["Einheit.", "Koalition.", "Ministerium.", "Fraktion."]'::jsonb, correct_answer = 2 WHERE id = 31;
UPDATE questions SET answers = '["Gesetzgebung", "Regierung", "Presse", "Rechtsprechung"]'::jsonb, correct_answer = 3 WHERE id = 32;
UPDATE questions SET answers = '["sind Staat und Religionsgemeinschaften voneinander getrennt.", "bilden die Religionsgemeinschaften den Staat.", "ist der Staat abhängig von den Religionsgemeinschaften.", "bilden Staat und Religionsgemeinschaften eine Einheit."]'::jsonb, correct_answer = 1 WHERE id = 33;
UPDATE questions SET answers = '["eine Demokratie", "ein Rechtsstaat", "eine Monarchie", "ein Sozialstaat"]'::jsonb, correct_answer = 3 WHERE id = 34;
UPDATE questions SET answers = '["Kirchensteuer", "Sozialabgaben", "Spendengeldern", "Vereinsbeiträgen"]'::jsonb, correct_answer = 2 WHERE id = 35;
UPDATE questions SET answers = '["die Krankenversicherung", "die Autoversicherung", "die Gebäudeversicherung", "die Haftpflichtversicherung"]'::jsonb, correct_answer = 1 WHERE id = 36;
UPDATE questions SET answers = '["Erste Ministerin/Erster Minister", "Premierministerin/Premierminister", "Senatorin/Senator", "Ministerpräsidentin/Ministerpräsident"]'::jsonb, correct_answer = 4 WHERE id = 37;
UPDATE questions SET answers = '["Staatenverbund", "Bundesstaat", "Staatenbund", "Zentralstaat"]'::jsonb, correct_answer = 2 WHERE id = 38;
UPDATE questions SET answers = '["einen eigenen Außenminister / eine eigene Außenministerin", "eine eigene Währung", "eine eigene Armee", "eine eigene Regierung"]'::jsonb, correct_answer = 4 WHERE id = 39;
UPDATE questions SET answers = '["Völker, hört die Signale …", "Einigkeit und Recht und Freiheit …", "Freude schöner Götterfunken …", "Deutschland einig Vaterland …"]'::jsonb, correct_answer = 2 WHERE id = 40;
UPDATE questions SET answers = '["weil dadurch die unterschiedlichen Meinungen der Bürger und Bürgerinnen vertreten werden", "damit Bestechung in der Politik begrenzt wird", "um politische Demonstrationen zu verhindern", "um wirtschaftlichen Wettbewerb anzuregen"]'::jsonb, correct_answer = 1 WHERE id = 41;
UPDATE questions SET answers = '["die Regierung", "das Parlament", "die Gerichte", "die Polizei"]'::jsonb, correct_answer = 2 WHERE id = 42;
UPDATE questions SET answers = '["wenn ihr Wahlkampf zu teuer ist", "wenn sie gegen die Verfassung kämpft", "wenn sie Kritik am Staatsoberhaupt äußert", "wenn ihr Programm eine neue Richtung vorschlägt"]'::jsonb, correct_answer = 2 WHERE id = 43;
UPDATE questions SET answers = '["Abgeordnete des EU-Parlaments", "den Bundespräsidenten / die Bundespräsidentin", "Landtagsabgeordnete", "Bundestagsabgeordnete"]'::jsonb, correct_answer = 2 WHERE id = 44;
UPDATE questions SET answers = '["Sozialversicherung", "Unfallversicherung", "Hausratversicherung", "Haftpflicht- und Feuerversicherung"]'::jsonb, correct_answer = 1 WHERE id = 45;
UPDATE questions SET answers = '["Er baut Straßen und Schulen.", "Er verkauft Lebensmittel und Kleidung.", "Er versorgt alle Einwohner und Einwohnerinnen kostenlos mit Zeitungen.", "Er produziert Autos und Busse."]'::jsonb, correct_answer = 1 WHERE id = 46;
UPDATE questions SET answers = '["Er bezahlt für alle Staatsangehörigen Urlaubsreisen.", "Er zahlt Kindergeld.", "Er unterstützt Museen.", "Er fördert Sportler und Sportlerinnen."]'::jsonb, correct_answer = 1 WHERE id = 47;
UPDATE questions SET answers = '["der Bundesrat", "der Bundespräsident / die Bundespräsidentin", "die Bürgerversammlung", "die Regierung"]'::jsonb, correct_answer = 3 WHERE id = 48;
UPDATE questions SET answers = '["die Lehrer und Lehrerinnen", "die Bundesländer", "das Familienministerium", "die Universitäten"]'::jsonb, correct_answer = 2 WHERE id = 49;
UPDATE questions SET answers = '["freie Zentralwirtschaft.", "soziale Marktwirtschaft.", "gelenkte Zentralwirtschaft.", "Planwirtschaft."]'::jsonb, correct_answer = 2 WHERE id = 50;
UPDATE questions SET answers = '["Menschen sich kritisch über die Regierung äußern können.", "Bürger friedlich demonstrieren gehen dürfen.", "Menschen von einer Privatpolizei ohne Grund verhaftet werden.", "jemand ein Verbrechen begeht und deshalb verhaftet wird."]'::jsonb, correct_answer = 3 WHERE id = 51;
UPDATE questions SET answers = '["Volke aus.", "Bundestag aus.", "preußischen König aus.", "Bundesverfassungsgericht aus."]'::jsonb, correct_answer = 1 WHERE id = 52;
UPDATE questions SET answers = '["Der Staat hat Recht.", "Es gibt nur rechte Parteien.", "Die Bürger und Bürgerinnen entscheiden über Gesetze.", "Der Staat muss die Gesetze einhalten."]'::jsonb, correct_answer = 4 WHERE id = 53;
UPDATE questions SET answers = '["Legislative", "Judikative", "Exekutive", "Direktive "]'::jsonb, correct_answer = 4 WHERE id = 54;
UPDATE questions SET answers = '["den Bundestagssitz in Berlin", "das Bundesverfassungsgericht in Karlsruhe", "das Bundesratsgebäude in Berlin", "das Bundeskanzleramt in Berlin"]'::jsonb, correct_answer = 1 WHERE id = 55;
UPDATE questions SET answers = '["Pfarramt", "Ordnungsamt", "Finanzamt", "Auswärtiges Amt"]'::jsonb, correct_answer = 2 WHERE id = 56;
UPDATE questions SET answers = '["der / die älteste Abgeordnete im Parlament", "der Ministerpräsident / die Ministerpräsidentin des größten Bundeslandes", "ein Abgeordneter / eine Abgeordnete der stärksten Fraktion", "ein ehemaliger Bundeskanzler / eine ehemalige Bundeskanzlerin"]'::jsonb, correct_answer = 3 WHERE id = 57;
UPDATE questions SET answers = '["der Präsident / die Präsidentin des Bundesverfassungsgerichtes", "der Bundespräsident / die Bundespräsidentin", "der Bundesratspräsident / die Bundesratspräsidentin", "der Bundestagspräsident / die Bundestagspräsidentin"]'::jsonb, correct_answer = 2 WHERE id = 58;
UPDATE questions SET answers = '["CDU und SSW", "PDS und WASG", "CSU und FDP", "Bündnis 90/Die Grünen und SPD"]'::jsonb, correct_answer = 2 WHERE id = 59;
UPDATE questions SET answers = '["Exekutive.", "Legislative.", "Direktive.", "Judikative."]'::jsonb, correct_answer = 2 WHERE id = 60;
UPDATE questions SET answers = '["Der König / die Königin herrscht über das Volk.", "Das Bundesverfassungsgericht steht über der Verfassung.", "Die Interessenverbände üben die Souveränität zusammen mit der Regierung aus. ", "Die Staatsgewalt geht vom Volke aus."]'::jsonb, correct_answer = 4 WHERE id = 61;
UPDATE questions SET answers = '["Kommunalwahl.", "Landtagswahl.", "Europawahl.", "Bundestagswahl."]'::jsonb, correct_answer = 2 WHERE id = 62;
UPDATE questions SET answers = '["die Polizei", "die Gerichte", "das Finanzamt", "die Ministerien"]'::jsonb, correct_answer = 2 WHERE id = 63;
UPDATE questions SET answers = '["vier Besatzungszonen.", "einen Oststaat und einen Weststaat.", "16 Kantone.", "Bund, Länder und Kommunen."]'::jsonb, correct_answer = 4 WHERE id = 64;
UPDATE questions SET answers = '["Gesetze zu entwerfen.", "die Bundesregierung zu kontrollieren.", "den Bundeskanzler / die Bundeskanzlerin zu wählen.", "das Bundeskabinett zu bilden."]'::jsonb, correct_answer = 4 WHERE id = 65;
UPDATE questions SET answers = '["Friedrich von Schiller", "Clemens Brentano", "Johann Wolfgang von Goethe", "Heinrich Hoffmann von Fallersleben"]'::jsonb, correct_answer = 4 WHERE id = 66;
UPDATE questions SET answers = '["Verteidigungspolitik", "Außenpolitik", "Wirtschaftspolitik", "Schulpolitik"]'::jsonb, correct_answer = 4 WHERE id = 67;
UPDATE questions SET answers = '["weil es in Deutschland nur staatliche Schulen gibt", "weil alle Schüler und Schülerinnen einen Schulabschluss haben müssen", "weil es in den Bundesländern verschiedene Schulen gibt", "weil es nach dem Grundgesetz seine Aufgabe ist"]'::jsonb, correct_answer = 4 WHERE id = 68;
UPDATE questions SET answers = '["Stadträte", "Landräte", "Gemeinden und Kommunen", "Bezirksämter"]'::jsonb, correct_answer = 3 WHERE id = 69;
UPDATE questions SET answers = '["Er / Sie führt die Regierungsgeschäfte.", "Er / Sie kontrolliert die Regierungspartei.", "Er / Sie wählt die Minister / Ministerinnen aus.", "Er / Sie schlägt den Kanzler / die Kanzlerin zur Wahl vor."]'::jsonb, correct_answer = 4 WHERE id = 70;
UPDATE questions SET answers = '["in Bonn, weil sich dort das Bundeskanzleramt und der Bundestag befinden.", "in Berlin, weil sich dort das Bundeskanzleramt und der Bundestag befinden.", "auf Schloss Meseberg, dem Gästehaus der Bundesregierung, um Staatsgäste zu empfangen.", "auf Schloss Bellevue, dem Amtssitz des Bundespräsidenten / der Bundespräsidentin, um Staatsgäste zu empfangen."]'::jsonb, correct_answer = 2 WHERE id = 71;
UPDATE questions SET answers = '["Gerhard Schröder", "Jürgen Rüttgers", "Klaus Wowereit", "Olaf Scholz"]'::jsonb, correct_answer = 4 WHERE id = 72;
UPDATE questions SET answers = '["CDU/CSU und SPD.", "Die Linke und Bündnis 90/Die Grünen.", "FDP und SPD.", "Die Linke und FDP."]'::jsonb, correct_answer = 1 WHERE id = 73;
UPDATE questions SET answers = '["Bundesversammlung", "Volkskammer", "Bundestag", "Bundesgerichtshof"]'::jsonb, correct_answer = 3 WHERE id = 74;
UPDATE questions SET answers = '["Frank-Walter Steinmeier", "Norbert Lammert", "Wolfgang Thierse", "Edmund Stoiber"]'::jsonb, correct_answer = 1 WHERE id = 75;
UPDATE questions SET answers = '["Christliche Deutsche Union", "Club Deutscher Unternehmer", "Christlicher Deutscher Umweltschutz", "Christlich Demokratische Union"]'::jsonb, correct_answer = 4 WHERE id = 76;
UPDATE questions SET answers = '["die deutsche Polizei", "ein deutscher Hafen", "eine deutsche Bürgerinitiative", "die deutsche Armee"]'::jsonb, correct_answer = 4 WHERE id = 77;
UPDATE questions SET answers = '["Sozialistische Partei Deutschlands", "Sozialpolitische Partei Deutschlands", "Sozialdemokratische Partei Deutschlands", "Sozialgerechte Partei Deutschlands"]'::jsonb, correct_answer = 3 WHERE id = 78;
UPDATE questions SET answers = '["Friedliche Demonstrative Partei", "Freie Deutschland Partei", "Führende Demokratische Partei", "Freie Demokratische Partei"]'::jsonb, correct_answer = 4 WHERE id = 79;
UPDATE questions SET answers = '["Oberlandesgericht", "Amtsgericht", "Bundesverfassungsgericht", "Verwaltungsgericht"]'::jsonb, correct_answer = 3 WHERE id = 80;
UPDATE questions SET answers = '["der Bundesrat", "die Bundesversammlung", "das Volk", "der Bundestag"]'::jsonb, correct_answer = 4 WHERE id = 81;
UPDATE questions SET answers = '["der Bundestagspräsident / die Bundestagspräsidentin", "der Bundespräsident / die Bundespräsidentin", "der Bundeskanzler / die Bundeskanzlerin", "der Bundesratspräsident / die Bundesratspräsidentin"]'::jsonb, correct_answer = 3 WHERE id = 82;
UPDATE questions SET answers = '["das Volk", "die Bundesversammlung", "der Bundestag", "die Bundesregierung"]'::jsonb, correct_answer = 3 WHERE id = 83;
UPDATE questions SET answers = '["regiert das Land.", "entwirft die Gesetze.", "repräsentiert das Land.", "überwacht die Einhaltung der Gesetze."]'::jsonb, correct_answer = 3 WHERE id = 84;
UPDATE questions SET answers = '["die Abgeordneten des Bundestages", "die Minister und Ministerinnen der Bundesregierung", "die Regierungsvertreter der Bundesländer", "die Parteimitglieder"]'::jsonb, correct_answer = 3 WHERE id = 85;
UPDATE questions SET answers = '["die Bundesversammlung", "der Bundesrat", "das Bundesparlament", "das Bundesverfassungsgericht"]'::jsonb, correct_answer = 1 WHERE id = 86;
UPDATE questions SET answers = '["der Bundeskanzler / die Bundeskanzlerin", "der Bundespräsident / die Bundespräsidentin", "der Bundesratspräsident / die Bundesratspräsidentin", "der Bundestagspräsident / die Bundestagspräsidentin"]'::jsonb, correct_answer = 2 WHERE id = 87;
UPDATE questions SET answers = '["kontrolliert die Regierung.", "entscheidet, wer Bundesminister / Bundesministerin wird.", "bestimmt, wer im Bundesrat sitzt.", "schlägt die Regierungschefs / Regierungschefinnen der Länder vor."]'::jsonb, correct_answer = 1 WHERE id = 88;
UPDATE questions SET answers = '["Verband", "Ältestenrat", "Fraktion", "Opposition"]'::jsonb, correct_answer = 3 WHERE id = 89;
UPDATE questions SET answers = '["den Bundesrat.", "die Bundesversammlung.", "den Bundestag.", "die Bundesregierung."]'::jsonb, correct_answer = 1 WHERE id = 90;
UPDATE questions SET answers = '["schwieriger, wenn sich dadurch die Mehrheit im Bundestag ändert.", "leichter, wenn dadurch neue Parteien in den Bundesrat kommen.", "schwieriger, wenn dadurch die Mehrheit im Bundesrat verändert wird.", "leichter, wenn es sich um ein reiches Bundesland handelt."]'::jsonb, correct_answer = 3 WHERE id = 91;
UPDATE questions SET answers = '["Christlich Sichere Union", "Christlich Süddeutsche Union", "Christlich Sozialer Unternehmerverband", "Christlich Soziale Union"]'::jsonb, correct_answer = 4 WHERE id = 92;
UPDATE questions SET answers = '["mehr Sitze erhält die Partei im Parlament.", "weniger Erststimmen kann sie haben.", "mehr Direktkandidaten der Partei ziehen ins Parlament ein.", "größer ist das Risiko, eine Koalition bilden zu müssen."]'::jsonb, correct_answer = 1 WHERE id = 93;
UPDATE questions SET answers = '["16", "18", "21", "23"]'::jsonb, correct_answer = 2 WHERE id = 94;
UPDATE questions SET answers = '["Wahlpflicht", "Schulpflicht", "Schweigepflicht", "Religionspflicht"]'::jsonb, correct_answer = 2 WHERE id = 95;
UPDATE questions SET answers = '["einen Reisepass", "einen Personalausweis", "einen Sozialversicherungsausweis", "einen Führerschein"]'::jsonb, correct_answer = 2 WHERE id = 96;
UPDATE questions SET answers = '["Sozialversicherung", "Sozialhilfe", "Kindergeld", "Wohngeld"]'::jsonb, correct_answer = 1 WHERE id = 97;
UPDATE questions SET answers = '["kann die Regierung ihre Mehrheit verlieren.", "dürfen sie nicht mehr an den Sitzungen des Parlaments teilnehmen.", "muss der Bundespräsident / die Bundespräsidentin zuvor sein / ihr Einverständnis geben.", "dürfen die Wähler / Wählerinnen dieser Abgeordneten noch einmal wählen."]'::jsonb, correct_answer = 1 WHERE id = 98;
UPDATE questions SET answers = '["Arbeitgeber / Arbeitgeberinnen und Arbeitnehmer / Arbeitnehmerinnen", "nur Arbeitnehmer / Arbeitnehmerinnen", "alle Staatsangehörigen", "nur Arbeitgeber / Arbeitgeberinnen"]'::jsonb, correct_answer = 1 WHERE id = 99;
UPDATE questions SET answers = '["die gesetzliche Rentenversicherung", "die Lebensversicherung", "die Arbeitslosenversicherung", "die Pflegeversicherung"]'::jsonb, correct_answer = 2 WHERE id = 100;
