UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 1 WHERE id = 401;
UPDATE questions SET answers = '["Westerwaldkreis", "Altötting", "Emsland", "Prignitz"]'::jsonb, correct_answer = 1 WHERE id = 402;
UPDATE questions SET answers = '["3", "4", "5", "6"]'::jsonb, correct_answer = 3 WHERE id = 403;
UPDATE questions SET answers = '["14", "16", "18", "20"]'::jsonb, correct_answer = 3 WHERE id = 404;
UPDATE questions SET answers = '["weiß-rot", "schwarz-rot-gold", "schwarz-gelb", "grün-weiß-rot"]'::jsonb, correct_answer = 2 WHERE id = 405;
UPDATE questions SET answers = '["bei den Kirchen", "bei der Verbraucherzentrale", "beim Ordnungsamt der Gemeinde", "bei der Landeszentrale für politische Bildung"]'::jsonb, correct_answer = 4 WHERE id = 406;
UPDATE questions SET answers = '["Mainz.", "Kaiserslautern.", "Ludwigshafen.", "Koblenz."]'::jsonb, correct_answer = 1 WHERE id = 407;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 1 WHERE id = 408;
UPDATE questions SET answers = '["Erster Minister / Erste Ministerin", "Premierminister / Premierministerin", "Bürgermeister / Bürgermeisterin", "Ministerpräsident / Ministerpräsidentin"]'::jsonb, correct_answer = 4 WHERE id = 409;
UPDATE questions SET answers = '["Justizminister / Justizministerin", "Außenminister / Außenministerin", "Finanzminister / Finanzministerin", "Innenminister / Innenministerin"]'::jsonb, correct_answer = 2 WHERE id = 410;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 4 WHERE id = 411;
UPDATE questions SET answers = '["Demmin", "Altötting", "Neunkirchen", "Rhein-Sieg-Kreis"]'::jsonb, correct_answer = 3 WHERE id = 412;
UPDATE questions SET answers = '["3", "4", "5", "6"]'::jsonb, correct_answer = 3 WHERE id = 413;
UPDATE questions SET answers = '["14", "16", "18", "20"]'::jsonb, correct_answer = 3 WHERE id = 414;
UPDATE questions SET answers = '["weiß-blau", "schwarz-rot-gold", "schwarz-gelb", "grün-weiß-rot"]'::jsonb, correct_answer = 2 WHERE id = 415;
UPDATE questions SET answers = '["bei den Kirchen", "bei der Landeszentrale für politische Bildung", "bei der Verbraucherzentrale", "beim Ordnungsamt der Gemeinde"]'::jsonb, correct_answer = 2 WHERE id = 416;
UPDATE questions SET answers = '["Neunkirchen.", "Homburg.", "Saarbrücken.", "Völklingen."]'::jsonb, correct_answer = 3 WHERE id = 417;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 2 WHERE id = 418;
UPDATE questions SET answers = '["Erster Minister / Erste Ministerin", "Premierminister / Premierministerin", "Bürgermeister / Bürgermeisterin", "Ministerpräsident / Ministerpräsidentin"]'::jsonb, correct_answer = 4 WHERE id = 419;
UPDATE questions SET answers = '["Justizminister / Justizministerin", "Außenminister / Außenministerin", "Finanzminister / Finanzministerin", "Innenminister / Innenministerin"]'::jsonb, correct_answer = 2 WHERE id = 420;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 4 WHERE id = 421;
UPDATE questions SET answers = '["Vogtlandkreis", "Altötting", "Uckermark", "Nordfriesland"]'::jsonb, correct_answer = 1 WHERE id = 422;
UPDATE questions SET answers = '["3", "4", "5", "6"]'::jsonb, correct_answer = 3 WHERE id = 423;
UPDATE questions SET answers = '["14", "16", "18", "20"]'::jsonb, correct_answer = 3 WHERE id = 424;
UPDATE questions SET answers = '["blau-weiß-rot", "weiß-grün", "grün-weiß-rot", "schwarz-gelb"]'::jsonb, correct_answer = 2 WHERE id = 425;
UPDATE questions SET answers = '["bei der Landeszentrale für politische Bildung", "beim Ordnungsamt der Gemeinde", "bei den Kirchen", "bei der Verbraucherzentrale"]'::jsonb, correct_answer = 1 WHERE id = 426;
UPDATE questions SET answers = '["Leipzig.", "Dresden.", "Chemnitz.", "Zwickau."]'::jsonb, correct_answer = 2 WHERE id = 427;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 4 WHERE id = 428;
UPDATE questions SET answers = '["Erster Minister / Erste Ministerin", "Premierminister / Premierministerin", "Bürgermeister / Bürgermeisterin", "Ministerpräsident / Ministerpräsidentin"]'::jsonb, correct_answer = 4 WHERE id = 429;
UPDATE questions SET answers = '["Justizminister / Justizministerin", "Außenminister / Außenministerin", "Finanzminister / Finanzministerin", "Innenminister / Innenministerin"]'::jsonb, correct_answer = 2 WHERE id = 430;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 4 WHERE id = 431;
UPDATE questions SET answers = '["Ammerland", "Altötting", "Uckermark", "Börde"]'::jsonb, correct_answer = 4 WHERE id = 432;
UPDATE questions SET answers = '["3", "4", "5", "6"]'::jsonb, correct_answer = 3 WHERE id = 433;
UPDATE questions SET answers = '["14", "16", "18", "20"]'::jsonb, correct_answer = 2 WHERE id = 434;
UPDATE questions SET answers = '["blau-weiß-rot", "gelb-schwarz", "grün-weiß-rot", "weiß-rot"]'::jsonb, correct_answer = 2 WHERE id = 435;
UPDATE questions SET answers = '["bei den Kirchen", "bei der Landeszentrale für politische Bildung", "beim Ordnungsamt der Gemeinde", "bei der Verbraucherzentrale"]'::jsonb, correct_answer = 2 WHERE id = 436;
UPDATE questions SET answers = '["Halle.", "Dessau.", "Magdeburg.", "Wittenberg."]'::jsonb, correct_answer = 3 WHERE id = 437;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 3 WHERE id = 438;
UPDATE questions SET answers = '["Erster Minister / Erste Ministerin", "Premierminister / Premierministerin", "Bürgermeister / Bürgermeisterin", "Ministerpräsident / Ministerpräsidentin"]'::jsonb, correct_answer = 4 WHERE id = 439;
UPDATE questions SET answers = '["Justizminister / Justizministerin", "Außenminister / Außenministerin", "Finanzminister / Finanzministerin", "Innenminister / Innenministerin"]'::jsonb, correct_answer = 2 WHERE id = 440;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 3 WHERE id = 441;
UPDATE questions SET answers = '["Ammerland", "Demmin", "Nordfriesland", "Rhein-Sieg-Kreis"]'::jsonb, correct_answer = 3 WHERE id = 442;
UPDATE questions SET answers = '["3", "4", "5", "6"]'::jsonb, correct_answer = 3 WHERE id = 443;
UPDATE questions SET answers = '["14", "16", "18", "20"]'::jsonb, correct_answer = 2 WHERE id = 444;
UPDATE questions SET answers = '["weiß-blau", "blau-weiß-rot", "weiß-rot", "grün-weiß-rot"]'::jsonb, correct_answer = 2 WHERE id = 445;
UPDATE questions SET answers = '["bei der Verbraucherzentrale", "beim Ordnungsamt der Gemeinde", "bei der Landeszentrale für politische Bildung", "bei den Kirchen"]'::jsonb, correct_answer = 3 WHERE id = 446;
UPDATE questions SET answers = '["Husum.", "Flensburg.", "Lübeck.", "Kiel."]'::jsonb, correct_answer = 4 WHERE id = 447;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 1 WHERE id = 448;
UPDATE questions SET answers = '["Erster Minister / Erste Ministerin", "Premierminister / Premierministerin", "Bürgermeister / Bürgermeisterin", "Ministerpräsident / Ministerpräsidentin"]'::jsonb, correct_answer = 4 WHERE id = 449;
UPDATE questions SET answers = '["Justizminister / Justizministerin", "Außenminister / Außenministerin", "Finanzminister / Finanzministerin", "Innenminister / Innenministerin"]'::jsonb, correct_answer = 2 WHERE id = 450;
