UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 2 WHERE id = 351;
UPDATE questions SET answers = '["Altona", "Hemelingen", "Pankow", "Demmin"]'::jsonb, correct_answer = 1 WHERE id = 352;
UPDATE questions SET answers = '["3", "4", "5", "6"]'::jsonb, correct_answer = 3 WHERE id = 353;
UPDATE questions SET answers = '["14", "16", "18", "20"]'::jsonb, correct_answer = 2 WHERE id = 354;
UPDATE questions SET answers = '["blau-weiß-rot", "weiß-rot", "grün-weiß-rot", "schwarz-gelb"]'::jsonb, correct_answer = 2 WHERE id = 355;
UPDATE questions SET answers = '["beim Ordnungsamt der Gemeinde", "bei der Verbraucherzentrale", "bei den Kirchen", "bei der Landeszentrale für politische Bildung"]'::jsonb, correct_answer = 4 WHERE id = 356;
UPDATE questions SET answers = '["Hamburg", "Sachsen", "Bayern", "Thüringen"]'::jsonb, correct_answer = 1 WHERE id = 357;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 3 WHERE id = 358;
UPDATE questions SET answers = '["Ministerpräsident / Ministerpräsidentin", "Erster Bürgermeister / Erste Bürgermeisterin", "Regierender Senator / Regierende Senatorin", "Oberbürgermeister / Oberbürgermeisterin"]'::jsonb, correct_answer = 2 WHERE id = 359;
UPDATE questions SET answers = '["Justizsenator / Justizsenatorin", "Senator / Senatorin für Außenbeziehungen", "Finanzsenator / Finanzsenatorin", "Innensenator / Innensenatorin"]'::jsonb, correct_answer = 2 WHERE id = 360;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 1 WHERE id = 361;
UPDATE questions SET answers = '["Ammerland", "Altötting", "Prignitz", "Main-Taunus-Kreis"]'::jsonb, correct_answer = 4 WHERE id = 362;
UPDATE questions SET answers = '["3", "4", "5", "6"]'::jsonb, correct_answer = 3 WHERE id = 363;
UPDATE questions SET answers = '["14", "16", "18", "20"]'::jsonb, correct_answer = 3 WHERE id = 364;
UPDATE questions SET answers = '["blau-weiß-rot", "rot-weiß", "schwarz-gold", "grün-weiß-rot"]'::jsonb, correct_answer = 2 WHERE id = 365;
UPDATE questions SET answers = '["bei der Landeszentrale für politische Bildung", "bei der Verbraucherzentrale", "beim Ordnungsamt der Gemeinde", "bei den Kirchen"]'::jsonb, correct_answer = 1 WHERE id = 366;
UPDATE questions SET answers = '["Kassel.", "Darmstadt.", "Frankfurt.", "Wiesbaden."]'::jsonb, correct_answer = 4 WHERE id = 367;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 3 WHERE id = 368;
UPDATE questions SET answers = '["Erster Minister / Erste Ministerin", "Premierminister / Premierministerin", "Bürgermeister / Bürgermeisterin", "Ministerpräsident / Ministerpräsidentin"]'::jsonb, correct_answer = 4 WHERE id = 369;
UPDATE questions SET answers = '["Justizminister / Justizministerin", "Außenminister / Außenministerin", "Finanzminister / Finanzministerin", "Innenminister / Innenministerin"]'::jsonb, correct_answer = 2 WHERE id = 370;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 3 WHERE id = 371;
UPDATE questions SET answers = '["Prignitz", "Mecklenburgische Seenplatte", "Vogtlandkreis", "Rhein-Sieg-Kreis"]'::jsonb, correct_answer = 2 WHERE id = 372;
UPDATE questions SET answers = '["3", "4", "5", "6"]'::jsonb, correct_answer = 3 WHERE id = 373;
UPDATE questions SET answers = '["14", "16", "18", "20"]'::jsonb, correct_answer = 2 WHERE id = 374;
UPDATE questions SET answers = '["schwarz-rot-gold", "blau-weiß-gelb-rot", "grün-weiß-rot", "schwarz-gelb"]'::jsonb, correct_answer = 2 WHERE id = 375;
UPDATE questions SET answers = '["bei der Landeszentrale für politische Bildung", "bei den Kirchen", "beim Ordnungsamt der Gemeinde", "bei der Verbraucherzentrale"]'::jsonb, correct_answer = 1 WHERE id = 376;
UPDATE questions SET answers = '["Greifswald.", "Schwerin.", "Rostock.", "Wismar."]'::jsonb, correct_answer = 2 WHERE id = 377;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 3 WHERE id = 378;
UPDATE questions SET answers = '["Erster Minister / Erste Ministerin", "Premierminister / Premierministerin", "Bürgermeister / Bürgermeisterin", "Ministerpräsident / Ministerpräsidentin"]'::jsonb, correct_answer = 4 WHERE id = 379;
UPDATE questions SET answers = '["Justizminister / Justizministerin", "Außenminister / Außenministerin", "Finanzminister / Finanzministerin", "Innenminister / Innenministerin"]'::jsonb, correct_answer = 2 WHERE id = 380;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 3 WHERE id = 381;
UPDATE questions SET answers = '["Ammerland", "Rhein-Sieg-Kreis", "Nordfriesland", "Vogtlandkreis"]'::jsonb, correct_answer = 1 WHERE id = 382;
UPDATE questions SET answers = '["3", "4", "5", "6"]'::jsonb, correct_answer = 3 WHERE id = 383;
UPDATE questions SET answers = '["14", "16", "17", "20"]'::jsonb, correct_answer = 2 WHERE id = 384;
UPDATE questions SET answers = '["rot-weiß", "schwarz-rot-gold", "schwarz-gelb", "blau-weiß-rot"]'::jsonb, correct_answer = 2 WHERE id = 385;
UPDATE questions SET answers = '["beim Koordinator für politische Bildung im Kultusministerium", "beim Ordnungsamt der Gemeinde", "bei der Verbraucherzentrale", "bei den Kirchen"]'::jsonb, correct_answer = 1 WHERE id = 386;
UPDATE questions SET answers = '["Hannover.", "Braunschweig.", "Wolfsburg.", "Osnabrück."]'::jsonb, correct_answer = 1 WHERE id = 387;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 1 WHERE id = 388;
UPDATE questions SET answers = '["Erster Minister / Erste Ministerin", "Premierminister / Premierministerin", "Bürgermeister / Bürgermeisterin", "Ministerpräsident / Ministerpräsidentin"]'::jsonb, correct_answer = 4 WHERE id = 389;
UPDATE questions SET answers = '["Justizminister / Justizministerin", "Außenminister / Außenministerin", "Finanzminister / Finanzministerin", "Innenminister / Innenministerin"]'::jsonb, correct_answer = 2 WHERE id = 390;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 2 WHERE id = 391;
UPDATE questions SET answers = '["Ammerland", "Rhein-Sieg-Kreis", "Nordfriesland", "Vogtlandkreis"]'::jsonb, correct_answer = 2 WHERE id = 392;
UPDATE questions SET answers = '["3", "4", "5", "6"]'::jsonb, correct_answer = 3 WHERE id = 393;
UPDATE questions SET answers = '["14", "16", "18", "20"]'::jsonb, correct_answer = 2 WHERE id = 394;
UPDATE questions SET answers = '["rot-weiß", "grün-weiß-rot", "schwarz-gold", "blau-weiß-rot"]'::jsonb, correct_answer = 2 WHERE id = 395;
UPDATE questions SET answers = '["bei den Kirchen", "beim Ordnungsamt der Gemeinde", "bei der Verbraucherzentrale", "bei der Landeszentrale für politische Bildung"]'::jsonb, correct_answer = 4 WHERE id = 396;
UPDATE questions SET answers = '["Köln.", "Bonn.", "Düsseldorf.", "Dortmund."]'::jsonb, correct_answer = 3 WHERE id = 397;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 3 WHERE id = 398;
UPDATE questions SET answers = '["Erster Minister / Erste Ministerin", "Premierminister / Premierministerin", "Bürgermeister / Bürgermeisterin", "Ministerpräsident / Ministerpräsidentin"]'::jsonb, correct_answer = 4 WHERE id = 399;
UPDATE questions SET answers = '["Justizminister / Justizministerin", "Außenminister / Außenministerin", "Finanzminister / Finanzministerin", "Innenminister / Innenministerin"]'::jsonb, correct_answer = 2 WHERE id = 400;
