UPDATE questions SET answers = '["Großbritannien", "die Bundesrepublik Deutschland", "die DDR", "die USA"]'::jsonb, correct_answer = 3 WHERE id = 151;
UPDATE questions SET answers = '["1918 bis 1923", "1932 bis 1950", "1933 bis 1945", "1945 bis 1989"]'::jsonb, correct_answer = 3 WHERE id = 152;
UPDATE questions SET answers = '["Tod Adolf Hitlers", "Beginn des Berliner Mauerbaus", "Wahl von Konrad Adenauer zum Bundeskanzler", "Ende des Zweiten Weltkriegs in Europa"]'::jsonb, correct_answer = 4 WHERE id = 153;
UPDATE questions SET answers = '["1933", "1945", "1949", "1961"]'::jsonb, correct_answer = 2 WHERE id = 154;
UPDATE questions SET answers = '["1888 bis 1918", "1921 bis 1934", "1933 bis 1945", "1949 bis 1963"]'::jsonb, correct_answer = 3 WHERE id = 155;
UPDATE questions SET answers = '["1923", "1927", "1933", "1936"]'::jsonb, correct_answer = 3 WHERE id = 156;
UPDATE questions SET answers = '["eine Diktatur.", "einen demokratischen Staat.", "eine Monarchie.", "ein Fürstentum."]'::jsonb, correct_answer = 1 WHERE id = 157;
UPDATE questions SET answers = '["Diktatur", "Demokratie.", "Monarchie.", "Räterepublik."]'::jsonb, correct_answer = 1 WHERE id = 158;
UPDATE questions SET answers = '["freie Wahlen", "Pressezensur", "willkürliche Verhaftungen", "Verfolgung der Juden"]'::jsonb, correct_answer = 1 WHERE id = 159;
UPDATE questions SET answers = '["der Erste Weltkrieg", "der Zweite Weltkrieg", "der Vietnamkrieg", "der Golfkrieg"]'::jsonb, correct_answer = 2 WHERE id = 160;
UPDATE questions SET answers = '["des staatlichen Rassismus", "der Meinungsfreiheit", "der allgemeinen Religionsfreiheit", "der Entwicklung der Demokratie"]'::jsonb, correct_answer = 1 WHERE id = 161;
UPDATE questions SET answers = '["eine Goldmedaille bei den Olympischen Spielen 1936.", "den Bau des Reichstagsgebäudes.", "den Aufbau der Wehrmacht.", "das Attentat auf Hitler am 20. Juli 1944."]'::jsonb, correct_answer = 4 WHERE id = 162;
UPDATE questions SET answers = '["1925", "1930", "1938", "1945"]'::jsonb, correct_answer = 3 WHERE id = 163;
UPDATE questions SET answers = '["Mit dem Angriff auf Polen beginnt der Zweite Weltkrieg.", "Die Nationalsozialisten verlieren eine Wahl und lösen den Reichstag auf.", "Jüdische Geschäfte und Synagogen werden durch Nationalsozialisten und ihre Anhänger zerstört.", "Hitler wird Reichspräsident und lässt alle Parteien verbieten."]'::jsonb, correct_answer = 3 WHERE id = 164;
UPDATE questions SET answers = '["Konrad Adenauer", "Kurt Georg Kiesinger", "Helmut Schmidt", "Willy Brandt"]'::jsonb, correct_answer = 1 WHERE id = 165;
UPDATE questions SET answers = '["bei den Montagsdemonstrationen 1989 in der DDR", "beim Arbeiteraufstand 1953 in der DDR", "bei den Demonstrationen 1968 in der Bundesrepublik Deutschland", "bei den Anti-Atomkraft-Demonstrationen 1985 in der Bundesrepublik Deutschland"]'::jsonb, correct_answer = 1 WHERE id = 166;
UPDATE questions SET answers = '["Sowjetunion, Großbritannien, Polen, Schweden", "Frankreich, Sowjetunion, Italien, Japan", "USA, Sowjetunion, Spanien, Portugal", "USA, Sowjetunion, Großbritannien, Frankreich"]'::jsonb, correct_answer = 4 WHERE id = 167;
UPDATE questions SET answers = '["USA", "Sowjetunion", "Frankreich", "Japan"]'::jsonb, correct_answer = 4 WHERE id = 168;
UPDATE questions SET answers = '["1939", "1945", "1949", "1951"]'::jsonb, correct_answer = 3 WHERE id = 169;
UPDATE questions SET answers = '["das Recht zur freien Entfaltung der Persönlichkeit", "Pressefreiheit", "das Verbot von Parteien", "den Schutz der Menschenwürde"]'::jsonb, correct_answer = 3 WHERE id = 170;
UPDATE questions SET answers = '["steuert sich allein nach Angebot und Nachfrage.", "wird vom Staat geplant und gesteuert, Angebot und Nachfrage werden nicht berücksichtigt.", "richtet sich nach der Nachfrage im Ausland.", "richtet sich nach Angebot und Nachfrage, aber der Staat sorgt für einen sozialen Ausgleich."]'::jsonb, correct_answer = 4 WHERE id = 171;
UPDATE questions SET answers = '["amerikanischen Besatzungszone.", "französischen Besatzungszone.", "britischen Besatzungszone.", "sowjetischen Besatzungszone."]'::jsonb, correct_answer = 4 WHERE id = 172;
UPDATE questions SET answers = '["des Nordatlantikpakts (NATO).", "der Vereinten Nationen (VN).", "der Europäischen Union (EU).", "des Warschauer Pakts."]'::jsonb, correct_answer = 3 WHERE id = 173;
UPDATE questions SET answers = '["1947", "1949", "1953", "1956"]'::jsonb, correct_answer = 2 WHERE id = 174;
UPDATE questions SET answers = '["3", "4", "5", "6"]'::jsonb, correct_answer = 2 WHERE id = 175;
UPDATE questions SET answers = '["1=Großbritannien, 2=Sowjetunion, 3=Frankreich, 4=USA", "1=Sowjetunion, 2=Großbritannien, 3=USA, 4=Frankreich", "1=Großbritannien, 2=Sowjetunion, 3=USA, 4=Frankreich", "1=Großbritannien, 2=USA, 3=Sowjetunion, 4=Frankreich"]'::jsonb, correct_answer = 3 WHERE id = 176;
UPDATE questions SET answers = '["München", "Berlin", "Dresden", "Frankfurt/Oder"]'::jsonb, correct_answer = 2 WHERE id = 177;
UPDATE questions SET answers = '["Für Frankreich war eine Versorgung der West-Berliner Bevölkerung mit dem Flugzeug kostengünstiger.", "Die amerikanischen Soldaten / Soldatinnen hatten beim Landtransport Angst vor Überfällen.", "Für Großbritannien war die Versorgung über die Luftbrücke schneller.", "Die Sowjetunion unterbrach den gesamten Verkehr auf dem Landwege."]'::jsonb, correct_answer = 4 WHERE id = 178;
UPDATE questions SET answers = '["mit dem Tod Adolf Hitlers", "durch die bedingungslose Kapitulation Deutschlands", "mit dem Rückzug der Deutschen aus den besetzten Gebieten", "durch eine Revolution in Deutschland"]'::jsonb, correct_answer = 2 WHERE id = 179;
UPDATE questions SET answers = '["Ludwig Erhard.", "Willy Brandt.", "Konrad Adenauer.", "Gerhard Schröder."]'::jsonb, correct_answer = 3 WHERE id = 180;
UPDATE questions SET answers = '["Er hat sich den ehemaligen Alliierten unterworfen.", "Er bat Polen und die polnischen Juden um Vergebung.", "Er zeigte seine Demut vor dem Warschauer Pakt.", "Er sprach ein Gebet am Grab des Unbekannten Soldaten."]'::jsonb, correct_answer = 2 WHERE id = 181;
UPDATE questions SET answers = '["KPD und SPD", "SPD und CDU", "CDU und FDP", "KPD und CSU"]'::jsonb, correct_answer = 1 WHERE id = 182;
UPDATE questions SET answers = '["40er Jahre", "50er Jahre", "70er Jahre", "80er Jahre"]'::jsonb, correct_answer = 2 WHERE id = 183;
UPDATE questions SET answers = '["Damit wird die Zeit nach der Wende im Jahr 1989 bezeichnet.", "Damit wurde der Beginn des Zweiten Weltkrieges bezeichnet.", "Darunter verstand man das Ende des Zweiten Weltkrieges und den Beginn des Wiederaufbaus.", "Damit ist die Stunde gemeint, in der die Uhr von der Sommerzeit auf die Winterzeit umgestellt wird."]'::jsonb, correct_answer = 3 WHERE id = 184;
UPDATE questions SET answers = '["des Warschauer Pakts gegen den Westen.", "Norddeutschlands gegen Süddeutschland.", "Nazi-Deutschlands gegen die Alliierten.", "Europas gegen die USA."]'::jsonb, correct_answer = 1 WHERE id = 185;
UPDATE questions SET answers = '["45413", "45460", "45493", "45605"]'::jsonb, correct_answer = 2 WHERE id = 186;
UPDATE questions SET answers = '["Preußen", "Bundesrepublik Deutschland", "DDR", "„Drittes Reich“"]'::jsonb, correct_answer = 3 WHERE id = 187;
UPDATE questions SET answers = '["1953", "1956", "1959", "1961"]'::jsonb, correct_answer = 4 WHERE id = 188;
UPDATE questions SET answers = '["1919", "1933", "1961", "1990"]'::jsonb, correct_answer = 3 WHERE id = 189;
UPDATE questions SET answers = '["Dritter Deutscher Rundfunk", "Die Deutsche Republik", "Dritte Deutsche Republik", "Deutsche Demokratische Republik"]'::jsonb, correct_answer = 4 WHERE id = 190;
UPDATE questions SET answers = '["1987", "1989", "1992", "1995"]'::jsonb, correct_answer = 2 WHERE id = 191;
UPDATE questions SET answers = '["Brandenburg", "Bayern", "Saarland", "Hessen"]'::jsonb, correct_answer = 1 WHERE id = 192;
UPDATE questions SET answers = '["ohne Bürgermeister.", "ein eigener Staat.", "durch eine Mauer geteilt.", "nur mit dem Flugzeug erreichbar."]'::jsonb, correct_answer = 3 WHERE id = 193;
UPDATE questions SET answers = '["Einheit.", "Nation.", "Bundesländer.", "Städte."]'::jsonb, correct_answer = 1 WHERE id = 194;
UPDATE questions SET answers = '["Hessen", "Sachsen-Anhalt", "Nordrhein-Westfalen", "Saarland"]'::jsonb, correct_answer = 2 WHERE id = 195;
UPDATE questions SET answers = '["von einer Diktatur zur Demokratie.", "von einer liberalen Marktwirtschaft zum Sozialismus.", "von einer Monarchie zur Sozialdemokratie.", "von einem religiösen Staat zu einem kommunistischen Staat."]'::jsonb, correct_answer = 1 WHERE id = 196;
UPDATE questions SET answers = '["Thüringen", "Hessen", "Bayern", "Bremen"]'::jsonb, correct_answer = 1 WHERE id = 197;
UPDATE questions SET answers = '["Bayern", "Niedersachsen", "Sachsen", "Baden-Württemberg"]'::jsonb, correct_answer = 3 WHERE id = 198;
UPDATE questions SET answers = '["das Parlament.", "das Ministerium für Staatssicherheit.", "eine regierende Partei.", "das Ministerium für Volksbildung."]'::jsonb, correct_answer = 2 WHERE id = 199;
UPDATE questions SET answers = '["Hessen", "Schleswig-Holstein", "Mecklenburg-Vorpommern", "Saarland"]'::jsonb, correct_answer = 3 WHERE id = 200;
