UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 1 WHERE id = 301;
UPDATE questions SET answers = '["Neckar-Odenwald-Kreis", "Nordfriesland", "Nordfriesland", "Altötting"]'::jsonb, correct_answer = 1 WHERE id = 302;
UPDATE questions SET answers = '["3", "4", "5", "6"]'::jsonb, correct_answer = 3 WHERE id = 303;
UPDATE questions SET answers = '["14", "16", "18", "20"]'::jsonb, correct_answer = 2 WHERE id = 304;
UPDATE questions SET answers = '["blau-weiß-rot", "schwarz-gold", "weiß-blau", "grün-weiß-rot"]'::jsonb, correct_answer = 2 WHERE id = 305;
UPDATE questions SET answers = '["beim Ordnungsamt der Gemeinde", "bei der Verbraucherzentrale", "bei der Landeszentrale für politische Bildung", "bei den Kirchen"]'::jsonb, correct_answer = 3 WHERE id = 306;
UPDATE questions SET answers = '["Heidelberg.", "Stuttgart.", "Karlsruhe.", "Mannheim."]'::jsonb, correct_answer = 2 WHERE id = 307;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 2 WHERE id = 308;
UPDATE questions SET answers = '["Erster Minister / Erste Ministerin", "Premierminister / Premierministerin", "Bürgermeister / Bürgermeisterin", "Ministerpräsident / Ministerpräsidentin"]'::jsonb, correct_answer = 4 WHERE id = 309;
UPDATE questions SET answers = '["Finanzminister / Finanzministerin", "Justizminister / Justizministerin", "Innenminister / Innenministerin", "Außenminister / Außenministerin"]'::jsonb, correct_answer = 4 WHERE id = 310;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 2 WHERE id = 311;
UPDATE questions SET answers = '["Prignitz", "Rhein-Sieg-Kreis", "Nordfriesland", "Altötting"]'::jsonb, correct_answer = 4 WHERE id = 312;
UPDATE questions SET answers = '["3", "4", "5", "6"]'::jsonb, correct_answer = 3 WHERE id = 313;
UPDATE questions SET answers = '["14", "16", "18", "20"]'::jsonb, correct_answer = 3 WHERE id = 314;
UPDATE questions SET answers = '["blau-weiß-rot", "weiß-blau", "grün-weiß-rot", "schwarz-gelb"]'::jsonb, correct_answer = 2 WHERE id = 315;
UPDATE questions SET answers = '["beim Ordnungsamt der Gemeinde", "bei der Landeszentrale für politische Bildung", "bei der Verbraucherzentrale", "bei den Kirchen"]'::jsonb, correct_answer = 2 WHERE id = 316;
UPDATE questions SET answers = '["Ingolstadt.", "Regensburg.", "Nürnberg.", "München."]'::jsonb, correct_answer = 4 WHERE id = 317;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 4 WHERE id = 318;
UPDATE questions SET answers = '["Erster Minister / Erste Ministerin", "Premierminister / Premierministerin", "Bürgermeister / Bürgermeisterin", "Ministerpräsident / Ministerpräsidentin"]'::jsonb, correct_answer = 4 WHERE id = 319;
UPDATE questions SET answers = '["Justizminister / Justizministerin", "Außenminister / Außenministerin", "Finanzminister / Finanzministerin", "Innenminister / Innenministerin"]'::jsonb, correct_answer = 2 WHERE id = 320;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 4 WHERE id = 321;
UPDATE questions SET answers = '["Altona", "Prignitz", "Pankow", "Demmin"]'::jsonb, correct_answer = 3 WHERE id = 322;
UPDATE questions SET answers = '["3", "4", "5", "6"]'::jsonb, correct_answer = 3 WHERE id = 323;
UPDATE questions SET answers = '["14", "16", "18", "20"]'::jsonb, correct_answer = 2 WHERE id = 324;
UPDATE questions SET answers = '["blau-weiß-rot", "weiß-rot", "grün-weiß-rot", "schwarz-gold"]'::jsonb, correct_answer = 2 WHERE id = 325;
UPDATE questions SET answers = '["beim Ordnungsamt der Gemeinde", "bei den Kirchen", "bei der Verbraucherzentrale", "bei der Landeszentrale für politische Bildung"]'::jsonb, correct_answer = 4 WHERE id = 326;
UPDATE questions SET answers = '["Berlin", "Saarland", "Brandenburg", "Hessen"]'::jsonb, correct_answer = 1 WHERE id = 327;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 4 WHERE id = 328;
UPDATE questions SET answers = '["Ministerpräsident / Ministerpräsidentin", "Oberbürgermeister / Oberbürgermeisterin", "Präsident / Präsidentin des Senats", "Regierender Bürgermeister / Regierende Bürgermeisterin"]'::jsonb, correct_answer = 4 WHERE id = 329;
UPDATE questions SET answers = '["Finanzsenator / Finanzsenatorin", "Innensenator / Innensenatorin", "Senator / Senatorin für Außenbeziehungen", "Justizsenator / Justizsenatorin"]'::jsonb, correct_answer = 3 WHERE id = 330;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 1 WHERE id = 331;
UPDATE questions SET answers = '["Prignitz", "Rhein-Sieg-Kreis", "Vogtlandkreis", "Amberg-Sulzbach"]'::jsonb, correct_answer = 1 WHERE id = 332;
UPDATE questions SET answers = '["3", "4", "5", "6"]'::jsonb, correct_answer = 3 WHERE id = 333;
UPDATE questions SET answers = '["14", "18", "16", "20"]'::jsonb, correct_answer = 3 WHERE id = 334;
UPDATE questions SET answers = '["blau-weiß-rot", "rot-weiß", "grün-weiß-rot", "schwarz-gelb"]'::jsonb, correct_answer = 2 WHERE id = 335;
UPDATE questions SET answers = '["bei den Kirchen", "beim Ordnungsamt der Gemeinde", "bei der Landeszentrale für politische Bildung", "bei der Verbraucherzentrale"]'::jsonb, correct_answer = 3 WHERE id = 336;
UPDATE questions SET answers = '["Potsdam.", "Cottbus.", "Brandenburg.", "Frankfurt/Oder."]'::jsonb, correct_answer = 1 WHERE id = 337;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 4 WHERE id = 338;
UPDATE questions SET answers = '["Erster Minister / Erste Ministerin", "Premierminister / Premierministerin", "Bürgermeister / Bürgermeisterin", "Ministerpräsident / Ministerpräsidentin"]'::jsonb, correct_answer = 4 WHERE id = 339;
UPDATE questions SET answers = '["Justizminister / Justizministerin", "Außenminister / Außenministerin", "Finanzminister / Finanzministerin", "Innenminister / Innenministerin"]'::jsonb, correct_answer = 2 WHERE id = 340;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 3 WHERE id = 341;
UPDATE questions SET answers = '["Altona", "Hemelingen", "Pankow", "Babelsberg"]'::jsonb, correct_answer = 2 WHERE id = 342;
UPDATE questions SET answers = '["3", "4", "5", "6"]'::jsonb, correct_answer = 2 WHERE id = 343;
UPDATE questions SET answers = '["14", "16", "18", "20"]'::jsonb, correct_answer = 2 WHERE id = 344;
UPDATE questions SET answers = '["blau-weiß-rot", "rot-weiß", "grün-weiß-rot", "schwarz-gold"]'::jsonb, correct_answer = 2 WHERE id = 345;
UPDATE questions SET answers = '["beim Ordnungsamt der Gemeinde", "bei der Landeszentrale für politische Bildung", "bei den Kirchen", "bei der Verbraucherzentrale"]'::jsonb, correct_answer = 2 WHERE id = 346;
UPDATE questions SET answers = '["Bremen", "München", "Frankfurt", "Erfurt"]'::jsonb, correct_answer = 1 WHERE id = 347;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 1 WHERE id = 348;
UPDATE questions SET answers = '["Ministerpräsident / Ministerpräsidentin", "Erster Bürgermeister / Erste Bürgermeisterin", "Präsident / Präsidentin des Senats", "Regierender Bürgermeister / Regierende Bürgermeisterin"]'::jsonb, correct_answer = 3 WHERE id = 349;
UPDATE questions SET answers = '["Senator / Senatorin für Außenbeziehungen", "Finanzsenator / Finanzsenatorin", "Justizsenator / Justizsenatorin", "Innensenator / Innensenatorin"]'::jsonb, correct_answer = 1 WHERE id = 350;
