UPDATE questions SET answers = '["Niedersachsen, Nordrhein-Westfalen, Hessen, Schleswig-Holstein, Brandenburg", "Mecklenburg-Vorpommern, Brandenburg, Sachsen, Sachsen-Anhalt, Thüringen", "Bayern, Baden-Württemberg, Rheinland-Pfalz, Thüringen, Sachsen", "Sachsen, Thüringen, Hessen, Niedersachsen, Brandenburg"]'::jsonb, correct_answer = 2 WHERE id = 201;
UPDATE questions SET answers = '["zu den Westmächten", "zum Warschauer Pakt", "zur NATO", "zu den blockfreien Staaten"]'::jsonb, correct_answer = 2 WHERE id = 202;
UPDATE questions SET answers = '["Marktwirtschaft", "Planwirtschaft", "Angebot und Nachfrage", "Kapitalismus"]'::jsonb, correct_answer = 2 WHERE id = 203;
UPDATE questions SET answers = '["Die Bundesrepublik Deutschland hat die DDR besetzt.", "Die heutigen fünf östlichen Bundesländer sind der Bundesrepublik Deutschland beigetreten.", "Die westlichen Bundesländer sind der DDR beigetreten.", "Die DDR hat die Bundesrepublik Deutschland besetzt."]'::jsonb, correct_answer = 2 WHERE id = 204;
UPDATE questions SET answers = '["zur Europäischen Union.", "zum Warschauer Pakt.", "zur OPEC.", "zur Europäischen Verteidigungsgemeinschaft."]'::jsonb, correct_answer = 1 WHERE id = 205;
UPDATE questions SET answers = '["In der Bundesrepublik waren Demonstrationen nur am Montag erlaubt.", "Montags waren Demonstrationen gegen das DDR-Regime.", "Am ersten Montag im Monat trafen sich in der Bundesrepublik Deutschland Demonstranten.", "Montags demonstrierte man in der DDR gegen den Westen."]'::jsonb, correct_answer = 2 WHERE id = 206;
UPDATE questions SET answers = '["in der NATO", "im Rheinbund", "im Warschauer Pakt", "im Europabündnis"]'::jsonb, correct_answer = 3 WHERE id = 207;
UPDATE questions SET answers = '["der Geheimdienst im „Dritten Reich“", "eine berühmte deutsche Gedenkstätte", "der Geheimdienst der DDR", "ein deutscher Sportverein während des Zweiten Weltkrieges"]'::jsonb, correct_answer = 3 WHERE id = 208;
UPDATE questions SET answers = '["1", "2", "3", "4"]'::jsonb, correct_answer = 1 WHERE id = 209;
UPDATE questions SET answers = '["der feierliche Beitritt zum Warschauer Pakt", "landesweite Streiks und ein Volksaufstand", "der 1. SED-Parteitag", "der erste Besuch Fidel Castros"]'::jsonb, correct_answer = 2 WHERE id = 210;
UPDATE questions SET answers = '["Helmut Kohl", "Willy Brandt", "Michail Gorbatschow", "Ludwig Erhard"]'::jsonb, correct_answer = 2 WHERE id = 211;
UPDATE questions SET answers = '["Bundesstaat Deutschland", "Bundesländer Deutschland", "Bundesrepublik Deutschland", "Bundesbezirk Deutschland"]'::jsonb, correct_answer = 3 WHERE id = 212;
UPDATE questions SET answers = '["70 Millionen", "78 Millionen", "80 Millionen", "90 Millionen"]'::jsonb, correct_answer = 3 WHERE id = 213;
UPDATE questions SET answers = '["schwarz-rot-gold", "rot-weiß-schwarz", "schwarz-rot-grün", "schwarz-gelb-rot"]'::jsonb, correct_answer = 1 WHERE id = 214;
UPDATE questions SET answers = '["Gerhard Schröder", "Helmut Kohl", "Konrad Adenauer", "Helmut Schmidt"]'::jsonb, correct_answer = 2 WHERE id = 215;
UPDATE questions SET answers = '["die Fahne der Stadt Berlin.", "der Bundesadler.", "der Reichsadler.", "die Reichskrone."]'::jsonb, correct_answer = 2 WHERE id = 216;
UPDATE questions SET answers = '["1919 bis 1927", "1933 bis 1945", "1949 bis 1990", "1945 bis 1961"]'::jsonb, correct_answer = 3 WHERE id = 217;
UPDATE questions SET answers = '["4", "5", "6", "7"]'::jsonb, correct_answer = 2 WHERE id = 218;
UPDATE questions SET answers = '["1933.", "1949.", "1971.", "1990."]'::jsonb, correct_answer = 4 WHERE id = 219;
UPDATE questions SET answers = '["an das Ende des Zweiten Weltkrieges", "an die Verabschiedung des Grundgesetzes", "an die Wiedervereinigung Deutschlands", "an die Opfer des Nationalsozialismus"]'::jsonb, correct_answer = 4 WHERE id = 220;
UPDATE questions SET answers = '["Deutsche können in viele Länder Europas ohne Passkontrolle reisen.", "Alle Menschen können ohne Personenkontrolle in Deutschland einreisen.", "Deutsche können ohne Passkontrolle in jedes Land reisen.", "Deutsche können in jedem Land mit dem Euro bezahlen."]'::jsonb, correct_answer = 1 WHERE id = 221;
UPDATE questions SET answers = '["Ungarn", "Portugal", "Spanien", "Schweiz"]'::jsonb, correct_answer = 4 WHERE id = 222;
UPDATE questions SET answers = '["Rumänien", "Bulgarien", "Polen", "Griechenland"]'::jsonb, correct_answer = 3 WHERE id = 223;
UPDATE questions SET answers = '["Europäische Unternehmen", "Europäische Union", "Einheitliche Union", "Euro Union"]'::jsonb, correct_answer = 2 WHERE id = 224;
UPDATE questions SET answers = '["Tschechien", "Norwegen", "Spanien", "Österreich"]'::jsonb, correct_answer = 4 WHERE id = 225;
UPDATE questions SET answers = '["2", "1", "4", "3"]'::jsonb, correct_answer = 1 WHERE id = 226;
UPDATE questions SET answers = '["Finnland", "Dänemark", "Norwegen", "Schweden"]'::jsonb, correct_answer = 2 WHERE id = 227;
UPDATE questions SET answers = '["NATO-Osterweiterung", "EU-Osterweiterung", "Europäische Gemeinschaft", "Europäische Gemeinschaft"]'::jsonb, correct_answer = 1 WHERE id = 228;
UPDATE questions SET answers = '["Spanien", "Bulgarien", "Norwegen", "Luxemburg"]'::jsonb, correct_answer = 4 WHERE id = 229;
UPDATE questions SET answers = '["5 Jahre.", "6 Jahre.", "7 Jahre.", "8 Jahre."]'::jsonb, correct_answer = 1 WHERE id = 230;
UPDATE questions SET answers = '["Damit sind amerikanische Einwanderer in Europa gemeint.", "Der Begriff meint den Einwanderungsstopp nach Europa.", "Damit sind europäische Auswanderer in den USA gemeint.", "Der Begriff meint den Zusammenschluss europäischer Staaten zur EU."]'::jsonb, correct_answer = 4 WHERE id = 231;
UPDATE questions SET answers = '["die Europäische Kommission", "die Länder, die in die EU eintreten dürfen", "die europäische Verfassung", "die Abgeordneten des Europäischen Parlaments"]'::jsonb, correct_answer = 4 WHERE id = 232;
UPDATE questions SET answers = '["Tschechien", "Bulgarien", "Griechenland", "Portugal"]'::jsonb, correct_answer = 1 WHERE id = 233;
UPDATE questions SET answers = '["London", "Paris", "Berlin", "Straßburg"]'::jsonb, correct_answer = 4 WHERE id = 234;
UPDATE questions SET answers = '["Freundschaft zwischen England und Deutschland", "Reisefreiheit in alle Länder der EU", "Frieden und Sicherheit in den Ländern der EU", "einheitliche Feiertage in den Ländern der EU"]'::jsonb, correct_answer = 3 WHERE id = 235;
UPDATE questions SET answers = '["21", "23", "25", "27"]'::jsonb, correct_answer = 4 WHERE id = 236;
UPDATE questions SET answers = '["Beitritt Deutschlands zur NATO", "Gründung der Europäischen Wirtschaftsgemeinschaft (EWG)", "Verpflichtung Deutschlands zu Reparationsleistungen", "Festlegung der Oder-Neiße-Linie als Ostgrenze"]'::jsonb, correct_answer = 2 WHERE id = 237;
UPDATE questions SET answers = '["Paris, London und Den Haag", "Straßburg, Luxemburg und Brüssel", "Rom, Bern und Wien", "Bonn, Zürich und Mailand"]'::jsonb, correct_answer = 2 WHERE id = 238;
UPDATE questions SET answers = '["durch die „Hamburger Verträge“", "durch die „Römischen Verträge“", "durch die „Pariser Verträge“", "durch die „Londoner Verträge“"]'::jsonb, correct_answer = 2 WHERE id = 239;
UPDATE questions SET answers = '["1995", "1998", "2002", "2005"]'::jsonb, correct_answer = 3 WHERE id = 240;
UPDATE questions SET answers = '["Sie muss an ihre Krankenkasse schreiben.", "Sie muss nichts tun, denn sie bekommt automatisch Elterngeld.", "Sie muss einen Antrag bei der Elterngeldstelle stellen.", "Sie muss das Arbeitsamt um Erlaubnis bitten."]'::jsonb, correct_answer = 3 WHERE id = 241;
UPDATE questions SET answers = '["der Staat", "die Bundesländer", "die Eltern / die Erziehungsberechtigten", "die Schulen"]'::jsonb, correct_answer = 3 WHERE id = 242;
UPDATE questions SET answers = '["Sie müssen nichts tun. Man darf in Deutschland jederzeit überall demonstrieren.", "Sie müssen die Demonstration anmelden.", "Sie können gar nichts tun, denn Demonstrationen sind in Deutschland grundsätzlich verboten.", "Maik und Sybille müssen einen neuen Verein gründen, weil nur Vereine demonstrieren dürfen."]'::jsonb, correct_answer = 2 WHERE id = 243;
UPDATE questions SET answers = '["das Abitur", "ein Diplom", "die Prokura", "eine Gesellenprüfung"]'::jsonb, correct_answer = 1 WHERE id = 244;
UPDATE questions SET answers = '["Hans (20 Jahre) und Marie (19 Jahre)", "Tom (20 Jahre) und Klaus (45 Jahre)", "Sofie (35 Jahre) und Lisa (40 Jahre)", "Anne (13 Jahre) und Tim (25 Jahre)"]'::jsonb, correct_answer = 4 WHERE id = 245;
UPDATE questions SET answers = '["16", "18", "19", "21"]'::jsonb, correct_answer = 2 WHERE id = 246;
UPDATE questions SET answers = '["Elternzeit", "Geburtsvorbereitung", "Mutterschutz", "Wochenbett"]'::jsonb, correct_answer = 3 WHERE id = 247;
UPDATE questions SET answers = '["des Staates.", "der Eltern.", "der Großeltern.", "der Schulen."]'::jsonb, correct_answer = 2 WHERE id = 248;
UPDATE questions SET answers = '["der Staat", "die Eltern", "die Verwandten", "die Schulen"]'::jsonb, correct_answer = 2 WHERE id = 249;
UPDATE questions SET answers = '["katholisch ist.", "gut ausgebildet ist.", "eine Frau ist.", "Mitglied einer Partei ist."]'::jsonb, correct_answer = 2 WHERE id = 250;
